//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "cancellation_conformance.rs"]
mod cancellation_conformance;

#[path = "clip_preprocess_parity.rs"]
mod clip_preprocess_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "fp16_fast_path.rs"]
mod fp16_fast_path;

#[path = "image_encoder_parity.rs"]
mod image_encoder_parity;

#[path = "pipeline_parity.rs"]
mod pipeline_parity;

#[path = "registration.rs"]
mod registration;

#[path = "scheduler_parity.rs"]
mod scheduler_parity;

#[path = "unet_parity.rs"]
mod unet_parity;

#[path = "vae_parity.rs"]
mod vae_parity;
