//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "adaln_cache.rs"]
mod adaln_cache;

#[path = "adaln_evict_memory.rs"]
mod adaln_evict_memory;

#[path = "adaln_evict_real_weights.rs"]
mod adaln_evict_real_weights;

#[path = "audio_vae_encode_parity.rs"]
mod audio_vae_encode_parity;

#[path = "audio_vae_parity.rs"]
mod audio_vae_parity;

#[path = "block_window.rs"]
mod block_window;

#[path = "block_window_real.rs"]
mod block_window_real;

#[path = "bounded_attention.rs"]
mod bounded_attention;

#[path = "bounded_attention_real.rs"]
mod bounded_attention_real;

#[path = "cross_backend_record.rs"]
mod cross_backend_record;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_io.rs"]
mod dit_io;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "duration_sweep_real.rs"]
mod duration_sweep_real;

#[path = "first_light.rs"]
mod first_light;

#[path = "fl2va_conditioning.rs"]
mod fl2va_conditioning;

#[path = "fl2va_first_light.rs"]
mod fl2va_first_light;

#[path = "joint_denoise.rs"]
mod joint_denoise;

#[path = "pipeline.rs"]
mod pipeline;

#[path = "quant_policy.rs"]
mod quant_policy;

#[path = "quant_tiers_real.rs"]
mod quant_tiers_real;

#[path = "real_weights.rs"]
mod real_weights;

#[path = "ref2va_checkpoint.rs"]
mod ref2va_checkpoint;

#[path = "ref2va_conditioning.rs"]
mod ref2va_conditioning;

#[path = "sequence_cost_real.rs"]
mod sequence_cost_real;

#[path = "staged_residency.rs"]
mod staged_residency;

#[path = "streamed_generate_real.rs"]
mod streamed_generate_real;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "te_tier_generate_stages.rs"]
mod te_tier_generate_stages;

#[path = "te_tier_real_weights.rs"]
mod te_tier_real_weights;

#[path = "turbo_lora.rs"]
mod turbo_lora;

#[path = "video_vae_encode_parity.rs"]
mod video_vae_encode_parity;

#[path = "video_vae_parity.rs"]
mod video_vae_parity;
