//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "adapter_real_weights.rs"]
mod adapter_real_weights;

#[path = "adapter_routing.rs"]
mod adapter_routing;

#[path = "attention_budget_dit.rs"]
mod attention_budget_dit;

#[path = "base_control_real_weights.rs"]
mod base_control_real_weights;

#[path = "base_t2i_real_weights.rs"]
mod base_t2i_real_weights;

#[path = "bench_z_image.rs"]
mod bench_z_image;

#[path = "block_residency_real_weights.rs"]
mod block_residency_real_weights;

#[path = "block_window_dit.rs"]
mod block_window_dit;

#[path = "bounded_attention_real_weights.rs"]
mod bounded_attention_real_weights;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "compile_parity.rs"]
mod compile_parity;

#[path = "component_scope_real_weights.rs"]
mod component_scope_real_weights;

#[path = "conformance.rs"]
mod conformance;

#[path = "control_real_weights.rs"]
mod control_real_weights;

#[path = "deferred_materialization_real_weights.rs"]
mod deferred_materialization_real_weights;

#[path = "denoise_loop.rs"]
mod denoise_loop;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "img2img_real_weights.rs"]
mod img2img_real_weights;

#[path = "lokr_loader.rs"]
mod lokr_loader;

#[path = "perf.rs"]
mod perf;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "pipeline.rs"]
mod pipeline;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "q8_xemb_diag.rs"]
mod q8_xemb_diag;

#[path = "qmm_smallk.rs"]
mod qmm_smallk;

#[path = "registry.rs"]
mod registry;

#[path = "request_scoped_residency_real_weights.rs"]
mod request_scoped_residency_real_weights;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "text_encoder.rs"]
mod text_encoder;

#[path = "text_encoder_layer.rs"]
mod text_encoder_layer;

#[path = "text_encoder_residency_real_weights.rs"]
mod text_encoder_residency_real_weights;

#[path = "text_encoder_window_real_weights.rs"]
mod text_encoder_window_real_weights;

#[path = "trainer_conformance.rs"]
mod trainer_conformance;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;

#[path = "vae_decoder.rs"]
mod vae_decoder;

#[path = "vae_submodules.rs"]
mod vae_submodules;

#[path = "vae_tiling_real_weights.rs"]
mod vae_tiling_real_weights;

#[path = "z_control_transformer.rs"]
mod z_control_transformer;

#[path = "z_image_block.rs"]
mod z_image_block;

#[path = "z_submodules.rs"]
mod z_submodules;

#[path = "z_transformer.rs"]
mod z_transformer;
