//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "adapter_real_weights.rs"]
mod adapter_real_weights;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "config.rs"]
mod config;

#[path = "control_real_weights.rs"]
mod control_real_weights;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "full_real_weights.rs"]
mod full_real_weights;

#[path = "generate_real_weights.rs"]
mod generate_real_weights;

#[path = "hyper_flux_real_weights.rs"]
mod hyper_flux_real_weights;

#[path = "ip_adapter_real_weights.rs"]
mod ip_adapter_real_weights;

#[path = "ip_generate_real_weights.rs"]
mod ip_generate_real_weights;

#[path = "ip_image_encoder_real_weights.rs"]
mod ip_image_encoder_real_weights;

#[path = "perf.rs"]
mod perf;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "registry.rs"]
mod registry;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "text_real_weights.rs"]
mod text_real_weights;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "vae_tiling_inheritance.rs"]
mod vae_tiling_inheritance;
