//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "decode_parity.rs"]
mod decode_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "encode_parity.rs"]
mod encode_parity;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "ladder_declaration_reachability.rs"]
mod ladder_declaration_reachability;

#[path = "memory_ladder_real_weights.rs"]
mod memory_ladder_real_weights;

#[path = "pipeline_contract.rs"]
mod pipeline_contract;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "smoke_decode.rs"]
mod smoke_decode;

#[path = "sprint_contract.rs"]
mod sprint_contract;

#[path = "sprint_scm_parity.rs"]
mod sprint_scm_parity;

#[path = "text_encoder.rs"]
mod text_encoder;

#[path = "transformer_parity.rs"]
mod transformer_parity;

#[path = "vae_tiled_decode.rs"]
mod vae_tiled_decode;
