//! Explicit, terminal-only LTX-2.5 quant measurement controller (sc-18777).
//!
//! This module is compiled only with `terminal-quant-measurement`; no runtime bundle enables that
//! feature. One invocation creates a new evidence directory, renders one immutable case through the
//! unadmitted measurement seam, writes the generated bytes, transcript and exact model inventory,
//! then seals a receipt over those files. Candidate modes require a sealed bf16 reference from the
//! same code/model/GPU/driver/fixture identity. Partial or failed directories never contain a receipt.

use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
#[cfg(feature = "cuda")]
use std::process::Command;
use std::time::Instant;

#[cfg(feature = "cuda")]
use candle_gen::candle_core::Device;
use candle_gen::gen_core::{
    AudioTrack, GenerationOutput, GenerationRequest, Image, LoadSpec, Progress, Quant,
    WeightsSource,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};

use crate::dev_sampler::TransformerVariant;
use crate::quant_eval::{
    bundle_identity_sha256, inventory_for_snapshot, measurement_case, snapshot_inventory_sha256,
    Ltx25GpuGeneration, Ltx25QuantMeasurementDraft, Ltx25QuantMeasurementReceipt, Ltx25QuantMode,
    Ltx25QuantQuality, Ltx25QuantRuntimeIdentity, RUNTIME_BINDING_FILE,
};

pub const TERMINAL_ACKNOWLEDGEMENT: &str = "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY";
pub const HARNESS_VERSION: &str = "sc-18777-terminal-v4";
const PROMPT: &str =
    "a red fox walking through snowy pines, slow cinematic dolly, detailed natural motion";
const OUTPUT_MAGIC: &[u8] = b"LTX25-QUANT-OUTPUT-V1\0";

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

#[derive(Clone, Debug)]
pub struct TerminalMeasurementConfig {
    pub acknowledgement: String,
    pub case_id: String,
    pub snapshot: PathBuf,
    pub model_revision: String,
    pub output_dir: PathBuf,
    pub reference_snapshot: Option<PathBuf>,
    pub reference_model_revision: Option<String>,
    pub reference_output: Option<PathBuf>,
    pub reference_receipt: Option<PathBuf>,
}

struct ReferenceEvidence {
    output: CapturedOutput,
    output_sha256: String,
    receipt_sha256: String,
    model_revision: String,
    model_inventory_sha256: String,
    runtime_bundle_sha256: String,
    artifacts: Vec<EvidenceArtifact>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceArtifact {
    path: String,
    bytes: u64,
    sha256: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceManifest {
    schema_version: &'static str,
    case_id: String,
    run_nonce_sha256: String,
    artifacts: Vec<EvidenceArtifact>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct CapturedOutput {
    frames: Vec<ImageRecord>,
    fps: u32,
    audio: Option<AudioRecord>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct ImageRecord {
    width: u32,
    height: u32,
    pixels: Vec<u8>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct AudioRecord {
    samples: Vec<f32>,
    sample_rate: u32,
    channels: u16,
}

#[derive(Clone, Debug)]
struct HardwareIdentity {
    gpu_name: String,
    driver_version: String,
    compute_cap: (i32, i32),
    generation: Ltx25GpuGeneration,
    physical_ordinal: usize,
}

/// Execute one case and return the same receipt written to `<output-dir>/receipt.json`.
pub fn run(config: TerminalMeasurementConfig) -> Result<Ltx25QuantMeasurementReceipt> {
    if config.acknowledgement != TERMINAL_ACKNOWLEDGEMENT {
        return Err(invalid(format!(
            "terminal-only acknowledgement must equal {TERMINAL_ACKNOWLEDGEMENT:?}"
        ))
        .into());
    }
    let case = measurement_case(&config.case_id)
        .ok_or_else(|| invalid(format!("unknown terminal case {:?}", config.case_id)))?;
    require_lower_hex("model revision", &config.model_revision, 40)?;
    if !config.output_dir.is_absolute() {
        return Err(invalid("output directory must be an absolute path").into());
    }
    if config.output_dir.exists() {
        return Err(invalid(format!(
            "output directory {} already exists; evidence runs never append or overwrite",
            config.output_dir.display()
        ))
        .into());
    }

    if env!("LTX25_BUILD_SOURCE_DIRTY") != "0" {
        return Err(invalid(
            "terminal measurement executable was built from a dirty source tree; rebuild from the committed revision",
        )
        .into());
    }
    let inference_revision = env!("LTX25_BUILD_INFERENCE_REVISION").to_owned();
    require_lower_hex("build-time inference revision", &inference_revision, 40)?;
    let executable_contract_sha256 = env!("LTX25_EXECUTABLE_CONTRACT_SHA256").to_owned();
    require_lower_hex(
        "executable contract SHA-256",
        &executable_contract_sha256,
        64,
    )?;
    let executable = fs::canonicalize(std::env::current_exe()?)?;
    let executable_sha256 = sha256_file(&executable)?;
    let snapshot = canonical_snapshot(&config.snapshot, &config.model_revision, "candidate")?;
    let output_parent = config
        .output_dir
        .parent()
        .ok_or_else(|| invalid("output directory has no parent"))?;
    fs::create_dir_all(output_parent)?;
    let output_parent = fs::canonicalize(output_parent)?;
    if output_parent.starts_with(&snapshot) {
        return Err(invalid("evidence output must be outside the model snapshot").into());
    }

    let hardware = hardware_identity()?;
    if hardware.generation != case.gpu {
        return Err(invalid(format!(
            "case {} requires {}, detected {} (sm_{}{})",
            case.id,
            case.gpu.id(),
            hardware.generation.id(),
            hardware.compute_cap.0,
            hardware.compute_cap.1,
        ))
        .into());
    }
    if case.mode == Ltx25QuantMode::Nvfp4 && hardware.compute_cap != (12, 0) {
        return Err(invalid(
            "NVFP4 is restricted to exact consumer Blackwell sm_120; datacenter Blackwell is not accepted",
        )
        .into());
    }

    fs::create_dir(&config.output_dir)?;
    let nonce = rand::random::<[u8; 32]>();
    let run_nonce_sha256 = sha256_hex(&nonce);

    let inventory_path = config.output_dir.join("model-inventory.json");
    let inventory = inventory_for_snapshot(&snapshot)?;
    write_json(&inventory_path, &inventory)?;
    let model_inventory_sha256 = sha256_file(&inventory_path)?;
    if model_inventory_sha256 != snapshot_inventory_sha256(&inventory)? {
        return Err(invalid(
            "serialized model inventory hash disagrees with runtime inventory hash",
        )
        .into());
    }

    let mut inspection_spec = LoadSpec::new(WeightsSource::Dir(snapshot.clone()));
    inspection_spec.quantize = match case.mode {
        Ltx25QuantMode::Bf16 => None,
        Ltx25QuantMode::Q4 => Some(Quant::Q4),
        Ltx25QuantMode::PackedQ8 | Ltx25QuantMode::Int8ConvRot => Some(Quant::Q8),
        Ltx25QuantMode::Nvfp4 => Some(Quant::Nvfp4),
    };
    let resolved = crate::bundle::resolve_split_bundle(&inspection_spec)?;
    let observed_variant = TransformerVariant::from_bundle(&resolved)?;
    if observed_variant != case.transformer_variant {
        return Err(invalid(format!(
            "case {} requires transformer variant {}, bundle declares {}",
            case.id,
            case.transformer_variant.id(),
            observed_variant.id()
        ))
        .into());
    }
    let transformer = resolved
        .require(candle_gen::gen_core::LtxComponent::Transformer)?
        .path();
    let source_inspection =
        crate::advanced_quant::inspect_transformer_source(transformer, case.mode)?;
    let runtime_bundle_sha256 = bundle_identity_sha256(
        &resolved,
        &snapshot,
        &inventory,
        &model_inventory_sha256,
        observed_variant,
        case.mode,
    )?;

    let mut transcript = vec![
        json!({
            "event": "start",
            "harnessVersion": HARNESS_VERSION,
            "caseId": case.id,
            "runNonceSha256": run_nonce_sha256,
            "inferenceRevision": inference_revision,
            "executableContractSha256": executable_contract_sha256,
            "executableSha256": executable_sha256,
            "modelRevision": config.model_revision,
            "transformerVariant": observed_variant.id(),
            "runtimeBundleSha256": runtime_bundle_sha256,
        }),
        json!({
            "event": "hardware",
            "gpuName": hardware.gpu_name,
            "driverVersion": hardware.driver_version,
            "physicalOrdinal": hardware.physical_ordinal,
            "computeCapability": format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
            "generation": hardware.generation.id(),
        }),
        json!({
            "event": "fixture",
            "fixture": case.fixture,
            "mode": case.mode.id(),
            "width": case.width,
            "height": case.height,
            "frames": case.frames,
            "fps": case.fps,
            "seed": case.seed,
            "promptSha256": sha256_hex(PROMPT.as_bytes()),
            "modelInventorySha256": model_inventory_sha256,
        }),
    ];

    let baseline_mib = candle_gen::testkit::used_mib(hardware.physical_ordinal)
        .ok_or_else(|| invalid("trusted nvidia-smi could not read the pre-run VRAM baseline"))?;
    let sampler = candle_gen::testkit::PeakSampler::start(hardware.physical_ordinal);
    let started = Instant::now();
    crate::advanced_quant::begin_operator_attestation(case.mode);
    let spec = inspection_spec;
    let generator = crate::load_25_for_terminal_measurement(&spec, case)?;
    let request = GenerationRequest {
        prompt: PROMPT.to_owned(),
        width: case.width,
        height: case.height,
        count: 1,
        seed: Some(case.seed),
        frames: Some(case.frames),
        fps: Some(case.fps),
        sampler: Some("rectified-flow".to_owned()),
        ..Default::default()
    };
    let mut progress = Vec::new();
    let output = generator.generate(&request, &mut |event: Progress| {
        progress.push(format!("{event:?}"));
    })?;
    let operator = crate::advanced_quant::finish_operator_attestation()?;
    let wall_clock_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);
    let peak_mib = sampler.stop();
    if peak_mib == 0 || peak_mib < baseline_mib {
        return Err(invalid(format!(
            "invalid VRAM samples: baseline={baseline_mib} MiB peak={peak_mib} MiB"
        ))
        .into());
    }
    let captured = capture_output(output)?;
    let observed = observed_geometry(&captured)?;
    if observed != (case.width, case.height, case.frames, case.fps) {
        return Err(invalid(format!(
            "observed output geometry {}x{}x{}@{} does not equal case {}x{}x{}@{}",
            observed.0,
            observed.1,
            observed.2,
            observed.3,
            case.width,
            case.height,
            case.frames,
            case.fps
        ))
        .into());
    }
    let post_inventory = inventory_for_snapshot(&snapshot)?;
    if post_inventory != inventory {
        return Err(invalid(
            "model inventory changed during generation, including a file or followed symlink target",
        )
        .into());
    }
    let output_path = config.output_dir.join("generated-output.bin");
    write_captured_output(&output_path, &captured)?;
    let output_sha256 = sha256_file(&output_path)?;

    let mut reference = if case.mode == Ltx25QuantMode::Bf16 {
        ReferenceEvidence {
            output: captured.clone(),
            output_sha256: output_sha256.clone(),
            receipt_sha256: sha256_hex(b"bf16-self-reference-no-prior-receipt"),
            model_revision: config.model_revision.clone(),
            model_inventory_sha256: model_inventory_sha256.clone(),
            runtime_bundle_sha256: runtime_bundle_sha256.clone(),
            artifacts: Vec::new(),
        }
    } else {
        load_and_copy_reference(
            &config,
            &config.output_dir,
            case,
            &hardware,
            &inference_revision,
            &executable_sha256,
        )?
    };
    let quality = compare_outputs(&captured, &reference.output)?;
    if !quality.silent_zero_video_passed || !quality.silent_zero_audio_passed {
        return Err(invalid("generated output failed the video or audio silent-zero gate").into());
    }

    transcript.push(json!({
        "event": "result",
        "progress": progress,
        "baselineVramBytes": baseline_mib * 1024 * 1024,
        "peakVramBytes": peak_mib * 1024 * 1024,
        "wallClockMs": wall_clock_ms,
        "outputSha256": output_sha256,
        "referenceOutputSha256": reference.output_sha256,
        "referenceReceiptSha256": reference.receipt_sha256,
        "referenceModelRevision": reference.model_revision,
        "referenceModelInventorySha256": reference.model_inventory_sha256,
        "referenceRuntimeBundleSha256": reference.runtime_bundle_sha256,
        "quality": quality,
        "observedWidth": observed.0,
        "observedHeight": observed.1,
        "observedFrames": observed.2,
        "observedFps": observed.3,
        "operatorKind": operator.operator_kind,
        "executedProjectionCount": operator.executed_projection_count,
        "declaredProjectionCount": operator.declared_projection_count,
        "operatorWeightInventorySha256": operator.weight_inventory_sha256,
    }));
    let transcript_path = config.output_dir.join("transcript.jsonl");
    write_transcript(&transcript_path, &transcript)?;
    let transcript_sha256 = sha256_file(&transcript_path)?;

    let mut artifacts = vec![
        artifact(&config.output_dir, &inventory_path)?,
        artifact(&config.output_dir, &output_path)?,
        artifact(&config.output_dir, &transcript_path)?,
    ];
    artifacts.append(&mut reference.artifacts);
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    let evidence_manifest = EvidenceManifest {
        schema_version: "sceneworks-ltx25-quant-evidence-v3",
        case_id: case.id.to_owned(),
        run_nonce_sha256: run_nonce_sha256.clone(),
        artifacts,
    };
    let manifest_path = config.output_dir.join("evidence-manifest.json");
    write_json(&manifest_path, &evidence_manifest)?;
    let evidence_manifest_sha256 = sha256_file(&manifest_path)?;

    let receipt = Ltx25QuantMeasurementReceipt::seal(Ltx25QuantMeasurementDraft {
        case_id: case.id.to_owned(),
        mode: case.mode,
        gpu_generation: case.gpu,
        transformer_variant: observed_variant,
        fixture: case.fixture.to_owned(),
        observed_width: observed.0,
        observed_height: observed.1,
        observed_frames: observed.2,
        observed_fps: observed.3,
        seed: case.seed,
        inference_revision,
        executable_contract_sha256,
        executable_sha256,
        model_revision: config.model_revision,
        model_inventory_sha256,
        runtime_bundle_sha256,
        reference_model_revision: reference.model_revision,
        reference_model_inventory_sha256: reference.model_inventory_sha256,
        reference_runtime_bundle_sha256: reference.runtime_bundle_sha256,
        gpu_name: hardware.gpu_name,
        compute_capability: format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
        driver_version: hardware.driver_version,
        harness_version: HARNESS_VERSION.to_owned(),
        run_nonce_sha256,
        transcript_sha256,
        evidence_manifest_sha256,
        output_sha256,
        reference_output_sha256: reference.output_sha256,
        reference_receipt_sha256: reference.receipt_sha256,
        operator_kind: operator.operator_kind,
        operator_contract_sha256: source_inspection.operator_contract_sha256,
        operator_weight_inventory_sha256: operator.weight_inventory_sha256,
        executed_projection_count: operator.executed_projection_count,
        declared_projection_count: operator.declared_projection_count,
        baseline_vram_bytes: baseline_mib * 1024 * 1024,
        peak_vram_bytes: peak_mib * 1024 * 1024,
        wall_clock_ms,
        quality,
    });
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "refusing to write invalid receipt: {}",
            errors.join("; ")
        ))
        .into());
    }
    write_json(&config.output_dir.join("receipt.json"), &receipt)?;
    let runtime_binding = Ltx25QuantRuntimeIdentity {
        mode: receipt.mode,
        transformer_variant: receipt.transformer_variant,
        inference_revision: receipt.inference_revision.clone(),
        executable_contract_sha256: receipt.executable_contract_sha256.clone(),
        executable_sha256: receipt.executable_sha256.clone(),
        model_revision: receipt.model_revision.clone(),
        model_inventory_sha256: receipt.model_inventory_sha256.clone(),
        runtime_bundle_sha256: receipt.runtime_bundle_sha256.clone(),
        reference_model_revision: receipt.reference_model_revision.clone(),
        reference_model_inventory_sha256: receipt.reference_model_inventory_sha256.clone(),
        reference_runtime_bundle_sha256: receipt.reference_runtime_bundle_sha256.clone(),
        receipt_sha256: receipt.receipt_sha256.clone(),
        transcript_sha256: receipt.transcript_sha256.clone(),
        evidence_manifest_sha256: receipt.evidence_manifest_sha256.clone(),
        output_sha256: receipt.output_sha256.clone(),
        reference_output_sha256: receipt.reference_output_sha256.clone(),
        reference_receipt_sha256: receipt.reference_receipt_sha256.clone(),
        operator_kind: receipt.operator_kind.clone(),
        operator_contract_sha256: receipt.operator_contract_sha256.clone(),
        operator_weight_inventory_sha256: receipt.operator_weight_inventory_sha256.clone(),
    };
    write_json(
        &config.output_dir.join(RUNTIME_BINDING_FILE),
        &runtime_binding,
    )?;
    Ok(receipt)
}

#[cfg(feature = "cuda")]
fn hardware_identity() -> Result<HardwareIdentity> {
    use candle_gen::candle_core::cuda::cudarc::driver::sys::CUdevice_attribute as Attr;
    let device = candle_gen::default_device()?;
    let Device::Cuda(cuda) = &device else {
        return Err(invalid("terminal quant measurement requires a CUDA device").into());
    };
    let context = cuda.cuda_stream().context();
    let major = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR)?;
    let minor = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR)?;
    let generation = Ltx25GpuGeneration::from_compute_cap(Some((major, minor)));
    let physical_ordinal = candle_gen::testkit::probe_gpu();
    let nvidia_smi = candle_gen::gpu::resolve_nvidia_smi()
        .ok_or_else(|| invalid("trusted absolute nvidia-smi path is unavailable"))?;
    let output = Command::new(nvidia_smi)
        .args([
            "--query-gpu=name,driver_version",
            "--format=csv,noheader,nounits",
            "-i",
            &physical_ordinal.to_string(),
        ])
        .output()?;
    if !output.status.success() {
        return Err(invalid(format!(
            "nvidia-smi identity query failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
        .into());
    }
    let line = String::from_utf8(output.stdout)?;
    let (gpu_name, driver_version) = line
        .trim()
        .split_once(',')
        .ok_or_else(|| invalid(format!("malformed nvidia-smi identity row {line:?}")))?;
    if gpu_name.trim().is_empty() || driver_version.trim().is_empty() {
        return Err(invalid("nvidia-smi returned an empty GPU name or driver version").into());
    }
    Ok(HardwareIdentity {
        gpu_name: gpu_name.trim().to_owned(),
        driver_version: driver_version.trim().to_owned(),
        compute_cap: (major, minor),
        generation,
        physical_ordinal,
    })
}

#[cfg(not(feature = "cuda"))]
fn hardware_identity() -> Result<HardwareIdentity> {
    Err(invalid("terminal quant measurement requires the cuda feature").into())
}

fn canonical_snapshot(path: &Path, revision: &str, label: &str) -> Result<PathBuf> {
    require_lower_hex(&format!("{label} model revision"), revision, 40)?;
    let root = fs::canonicalize(path).map_err(|error| {
        invalid(format!(
            "cannot canonicalize {label} snapshot {}: {error}",
            path.display()
        ))
    })?;
    if !root.is_dir() {
        return Err(invalid(format!(
            "{label} snapshot {} is not a directory",
            root.display()
        ))
        .into());
    }
    if root.file_name().is_none_or(|name| name != revision)
        || root.parent().and_then(Path::file_name) != Some(std::ffi::OsStr::new("snapshots"))
    {
        return Err(invalid(format!(
            "{label} snapshot {} must be the exact Hugging Face <repo>/snapshots/{revision} directory",
            root.display()
        ))
        .into());
    }
    Ok(root)
}

fn observed_geometry(output: &CapturedOutput) -> Result<(u32, u32, u32, u32)> {
    let first = output
        .frames
        .first()
        .ok_or_else(|| invalid("LTX terminal output contained zero frames"))?;
    if first.width == 0 || first.height == 0 || output.fps == 0 {
        return Err(invalid("LTX terminal output reported zero width, height, or FPS").into());
    }
    for frame in &output.frames {
        if frame.width != first.width
            || frame.height != first.height
            || frame.pixels.len() != frame.width as usize * frame.height as usize * 3
        {
            return Err(invalid(
                "LTX terminal output frame dimensions are inconsistent or malformed",
            )
            .into());
        }
    }
    Ok((
        first.width,
        first.height,
        u32::try_from(output.frames.len())?,
        output.fps,
    ))
}

fn capture_output(output: GenerationOutput) -> Result<CapturedOutput> {
    let GenerationOutput::Video { frames, fps, audio } = output else {
        return Err(invalid("LTX terminal measurement expected a video output").into());
    };
    let frames = frames
        .into_iter()
        .map(
            |Image {
                 width,
                 height,
                 pixels,
             }| ImageRecord {
                width,
                height,
                pixels,
            },
        )
        .collect();
    let audio = audio
        .map(
            |AudioTrack {
                 samples,
                 sample_rate,
                 channels,
                 stems,
             }| {
                if !stems.is_empty() {
                    return Err(invalid(
                        "LTX terminal output unexpectedly contained source-separated stems",
                    ));
                }
                if samples.iter().any(|sample| !sample.is_finite()) {
                    return Err(invalid(
                        "LTX terminal output audio contains NaN or infinity",
                    ));
                }
                Ok(AudioRecord {
                    samples,
                    sample_rate,
                    channels,
                })
            },
        )
        .transpose()?;
    Ok(CapturedOutput { frames, fps, audio })
}

fn write_captured_output(path: &Path, output: &CapturedOutput) -> Result<()> {
    let payload = serde_json::to_vec(output)?;
    let mut file = File::create(path)?;
    file.write_all(OUTPUT_MAGIC)?;
    file.write_all(&(payload.len() as u64).to_le_bytes())?;
    file.write_all(&payload)?;
    file.sync_all()?;
    Ok(())
}

fn read_captured_output(path: &Path) -> Result<CapturedOutput> {
    let bytes = fs::read(path)?;
    let header = OUTPUT_MAGIC.len() + 8;
    if bytes.len() < header || &bytes[..OUTPUT_MAGIC.len()] != OUTPUT_MAGIC {
        return Err(invalid(format!(
            "{} is not an LTX25 output artifact",
            path.display()
        ))
        .into());
    }
    let declared = u64::from_le_bytes(bytes[OUTPUT_MAGIC.len()..header].try_into()?) as usize;
    if bytes.len() - header != declared {
        return Err(invalid(format!(
            "{} has a truncated/extended payload",
            path.display()
        ))
        .into());
    }
    Ok(serde_json::from_slice(&bytes[header..])?)
}

fn load_and_copy_reference(
    config: &TerminalMeasurementConfig,
    output_dir: &Path,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    hardware: &HardwareIdentity,
    inference_revision: &str,
    executable_sha256: &str,
) -> Result<ReferenceEvidence> {
    let reference_revision = config.reference_model_revision.as_deref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-model-revision for the bf16 snapshot")
    })?;
    let reference_snapshot = config.reference_snapshot.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-snapshot for the bf16 model bundle")
    })?;
    let reference_snapshot =
        canonical_snapshot(reference_snapshot, reference_revision, "reference")?;
    let source_output = config.reference_output.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-output from the matching sealed bf16 case")
    })?;
    let source_receipt = config.reference_receipt.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-receipt from the matching sealed bf16 case")
    })?;
    let source_output = fs::canonicalize(source_output)?;
    let source_receipt = fs::canonicalize(source_receipt)?;
    let evidence_dir = source_receipt
        .parent()
        .ok_or_else(|| invalid("bf16 reference receipt has no evidence directory"))?
        .to_path_buf();
    if source_output.parent() != Some(evidence_dir.as_path())
        || source_output.file_name() != Some(std::ffi::OsStr::new("generated-output.bin"))
        || source_receipt.file_name() != Some(std::ffi::OsStr::new("receipt.json"))
    {
        return Err(invalid(
            "bf16 reference output and receipt must be the canonical generated-output.bin/receipt.json pair from one evidence directory",
        )
        .into());
    }
    let receipt: Ltx25QuantMeasurementReceipt =
        serde_json::from_slice(&fs::read(&source_receipt)?)?;
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "bf16 reference receipt is invalid: {}",
            errors.join("; ")
        ))
        .into());
    }
    if !reference_receipt_matches_campaign(
        &receipt,
        case,
        hardware,
        inference_revision,
        executable_sha256,
        reference_revision,
    ) {
        return Err(invalid("bf16 reference receipt does not match this exact code/reference-model/GPU/driver/fixture identity").into());
    }
    let reference_inventory = inventory_for_snapshot(&reference_snapshot)?;
    let reference_inventory_sha256 = snapshot_inventory_sha256(&reference_inventory)?;
    let inventory_path = evidence_dir.join("model-inventory.json");
    if sha256_file(&inventory_path)? != receipt.model_inventory_sha256
        || receipt.model_inventory_sha256 != reference_inventory_sha256
    {
        return Err(invalid(
            "bf16 reference receipt/inventory artifact does not match the explicit reference snapshot",
        )
        .into());
    }
    let reference_spec = LoadSpec::new(WeightsSource::Dir(reference_snapshot.clone()));
    let reference_bundle = crate::bundle::resolve_split_bundle(&reference_spec)?;
    let reference_variant = TransformerVariant::from_bundle(&reference_bundle)?;
    if reference_variant != case.transformer_variant {
        return Err(invalid(
            "bf16 reference bundle transformer variant differs from candidate case",
        )
        .into());
    }
    let reference_transformer = reference_bundle
        .require(candle_gen::gen_core::LtxComponent::Transformer)?
        .path();
    crate::advanced_quant::inspect_transformer_source(reference_transformer, Ltx25QuantMode::Bf16)?;
    let reference_bundle_sha256 = bundle_identity_sha256(
        &reference_bundle,
        &reference_snapshot,
        &reference_inventory,
        &reference_inventory_sha256,
        reference_variant,
        Ltx25QuantMode::Bf16,
    )?;
    if !reference_receipt_matches_bundle(
        &receipt,
        reference_revision,
        &reference_inventory_sha256,
        &reference_bundle_sha256,
    ) {
        return Err(invalid(
            "bf16 reference receipt is not self-bound to the explicit bf16 bundle identity",
        )
        .into());
    }
    let source_hash = sha256_file(&source_output)?;
    if source_hash != receipt.output_sha256 {
        return Err(invalid("bf16 reference output hash does not match its sealed receipt").into());
    }
    let transcript_path = evidence_dir.join("transcript.jsonl");
    let manifest_path = evidence_dir.join("evidence-manifest.json");
    if sha256_file(&transcript_path)? != receipt.transcript_sha256
        || sha256_file(&manifest_path)? != receipt.evidence_manifest_sha256
    {
        return Err(invalid(
            "bf16 reference transcript or evidence manifest hash differs from its receipt",
        )
        .into());
    }
    let sources = [
        (source_output.as_path(), "reference-output.bin"),
        (source_receipt.as_path(), "reference-receipt.json"),
        (inventory_path.as_path(), "reference-model-inventory.json"),
        (transcript_path.as_path(), "reference-transcript.jsonl"),
        (manifest_path.as_path(), "reference-evidence-manifest.json"),
    ];
    let mut artifacts = Vec::with_capacity(sources.len());
    for (source, name) in sources {
        let destination = output_dir.join(name);
        fs::copy(source, &destination)?;
        artifacts.push(artifact(output_dir, &destination)?);
    }
    let copied_output = output_dir.join("reference-output.bin");
    let reference = read_captured_output(&copied_output)?;
    Ok(ReferenceEvidence {
        output: reference,
        output_sha256: source_hash,
        receipt_sha256: sha256_file(&source_receipt)?,
        model_revision: reference_revision.to_owned(),
        model_inventory_sha256: reference_inventory_sha256,
        runtime_bundle_sha256: reference_bundle_sha256,
        artifacts,
    })
}

fn reference_receipt_matches_campaign(
    receipt: &Ltx25QuantMeasurementReceipt,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    hardware: &HardwareIdentity,
    inference_revision: &str,
    executable_sha256: &str,
    reference_revision: &str,
) -> bool {
    receipt.mode == Ltx25QuantMode::Bf16
        && receipt.gpu_generation == case.gpu
        && receipt.gpu_name == hardware.gpu_name
        && receipt.compute_capability
            == format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1)
        && receipt.driver_version == hardware.driver_version
        && receipt.inference_revision == inference_revision
        && receipt.executable_contract_sha256 == env!("LTX25_EXECUTABLE_CONTRACT_SHA256")
        && receipt.executable_sha256 == executable_sha256
        && receipt.model_revision == reference_revision
        && receipt.transformer_variant == case.transformer_variant
        && receipt.fixture == case.fixture
        && receipt.observed_width == case.width
        && receipt.observed_height == case.height
        && receipt.observed_frames == case.frames
        && receipt.observed_fps == case.fps
        && receipt.seed == case.seed
}

fn reference_receipt_matches_bundle(
    receipt: &Ltx25QuantMeasurementReceipt,
    reference_revision: &str,
    reference_inventory_sha256: &str,
    reference_bundle_sha256: &str,
) -> bool {
    receipt.model_revision == reference_revision
        && receipt.model_inventory_sha256 == reference_inventory_sha256
        && receipt.runtime_bundle_sha256 == reference_bundle_sha256
        && receipt.reference_model_revision == receipt.model_revision
        && receipt.reference_model_inventory_sha256 == receipt.model_inventory_sha256
        && receipt.reference_runtime_bundle_sha256 == receipt.runtime_bundle_sha256
}

fn compare_outputs(
    candidate: &CapturedOutput,
    reference: &CapturedOutput,
) -> Result<Ltx25QuantQuality> {
    if candidate.fps != reference.fps
        || candidate.frames.len() != reference.frames.len()
        || candidate.frames.is_empty()
    {
        return Err(invalid("candidate/reference frame count or FPS differs").into());
    }
    let mut candidate_pixels = Vec::new();
    let mut reference_pixels = Vec::new();
    for (candidate, reference) in candidate.frames.iter().zip(&reference.frames) {
        if candidate.width != reference.width
            || candidate.height != reference.height
            || candidate.pixels.len() != reference.pixels.len()
            || candidate.pixels.len() != candidate.width as usize * candidate.height as usize * 3
        {
            return Err(
                invalid("candidate/reference frame geometry differs or is malformed").into(),
            );
        }
        candidate_pixels.extend_from_slice(&candidate.pixels);
        reference_pixels.extend_from_slice(&reference.pixels);
    }
    let mse = candidate_pixels
        .iter()
        .zip(&reference_pixels)
        .map(|(&a, &b)| {
            let delta = f64::from(a) - f64::from(b);
            delta * delta
        })
        .sum::<f64>()
        / candidate_pixels.len() as f64;
    let reference_psnr = if mse == 0.0 {
        120.0
    } else {
        10.0 * (255.0_f64.powi(2) / mse).log10()
    };
    let reference_ssim = global_ssim(&candidate_pixels, &reference_pixels);
    let temporal_boundary_drift = temporal_boundary_drift(&candidate.frames, &reference.frames)?;
    let silent_zero_video_passed = candidate_pixels.iter().any(|&value| value != 0)
        && candidate_pixels.iter().min() != candidate_pixels.iter().max();
    let silent_zero_audio_passed = candidate.audio.as_ref().is_some_and(|audio| {
        !audio.samples.is_empty()
            && audio.samples.iter().all(|sample| sample.is_finite())
            && audio.samples.iter().any(|sample| sample.abs() > 1.0e-8)
    });
    Ok(Ltx25QuantQuality {
        reference_psnr,
        reference_ssim,
        temporal_boundary_drift,
        silent_zero_video_passed,
        silent_zero_audio_passed,
    })
}

fn global_ssim(candidate: &[u8], reference: &[u8]) -> f64 {
    let n = candidate.len() as f64;
    let mean_a = candidate.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let mean_b = reference.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let (mut var_a, mut var_b, mut covariance) = (0.0, 0.0, 0.0);
    for (&a, &b) in candidate.iter().zip(reference) {
        let da = f64::from(a) - mean_a;
        let db = f64::from(b) - mean_b;
        var_a += da * da;
        var_b += db * db;
        covariance += da * db;
    }
    let denominator = (n - 1.0).max(1.0);
    var_a /= denominator;
    var_b /= denominator;
    covariance /= denominator;
    let c1 = (0.01_f64 * 255.0).powi(2);
    let c2 = (0.03_f64 * 255.0).powi(2);
    ((2.0 * mean_a * mean_b + c1) * (2.0 * covariance + c2)
        / ((mean_a * mean_a + mean_b * mean_b + c1) * (var_a + var_b + c2)))
        .clamp(0.0, 1.0)
}

fn temporal_boundary_drift(candidate: &[ImageRecord], reference: &[ImageRecord]) -> Result<f64> {
    if candidate.len() < 2 {
        return Ok(0.0);
    }
    let mut sum = 0.0;
    let mut count = 0usize;
    for index in 1..candidate.len() {
        for (((&candidate_now, &candidate_before), &reference_now), &reference_before) in candidate
            [index]
            .pixels
            .iter()
            .zip(&candidate[index - 1].pixels)
            .zip(&reference[index].pixels)
            .zip(&reference[index - 1].pixels)
        {
            let candidate_delta = i16::from(candidate_now) - i16::from(candidate_before);
            let reference_delta = i16::from(reference_now) - i16::from(reference_before);
            sum += f64::from((candidate_delta - reference_delta).unsigned_abs()) / 255.0;
            count += 1;
        }
    }
    if count == 0 {
        return Err(invalid("temporal drift had no samples").into());
    }
    Ok(sum / count as f64)
}

fn artifact(root: &Path, path: &Path) -> Result<EvidenceArtifact> {
    Ok(EvidenceArtifact {
        path: path
            .strip_prefix(root)?
            .to_string_lossy()
            .replace('\\', "/"),
        bytes: path.metadata()?.len(),
        sha256: sha256_file(path)?,
    })
}

fn write_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    let mut file = File::create(path)?;
    file.write_all(&bytes)?;
    file.sync_all()?;
    Ok(())
}

fn write_transcript(path: &Path, events: &[serde_json::Value]) -> Result<()> {
    let mut file = File::create(path)?;
    for event in events {
        serde_json::to_writer(&mut file, event)?;
        file.write_all(b"\n")?;
    }
    file.sync_all()?;
    Ok(())
}

fn sha256_file(path: &Path) -> Result<String> {
    let mut file = File::open(path)?;
    let mut hash = Sha256::new();
    let mut buffer = vec![0_u8; 1024 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hash.update(&buffer[..read]);
    }
    Ok(format!("{:x}", hash.finalize()))
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn require_lower_hex(label: &str, value: &str, length: usize) -> Result<()> {
    if value.len() != length
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(invalid(format!(
            "{label} must be {length} lowercase hexadecimal characters"
        ))
        .into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn bf16_receipt() -> Ltx25QuantMeasurementReceipt {
        let case = measurement_case("ltx25-bf16-ada-v1").unwrap();
        Ltx25QuantMeasurementReceipt::seal(Ltx25QuantMeasurementDraft {
            case_id: case.id.to_owned(),
            mode: case.mode,
            gpu_generation: case.gpu,
            transformer_variant: case.transformer_variant,
            fixture: case.fixture.to_owned(),
            observed_width: case.width,
            observed_height: case.height,
            observed_frames: case.frames,
            observed_fps: case.fps,
            seed: case.seed,
            inference_revision: "a".repeat(40),
            executable_contract_sha256: env!("LTX25_EXECUTABLE_CONTRACT_SHA256").to_owned(),
            executable_sha256: "b".repeat(64),
            model_revision: "c".repeat(40),
            model_inventory_sha256: "d".repeat(64),
            runtime_bundle_sha256: "e".repeat(64),
            reference_model_revision: "c".repeat(40),
            reference_model_inventory_sha256: "d".repeat(64),
            reference_runtime_bundle_sha256: "e".repeat(64),
            gpu_name: "NVIDIA GeForce RTX 4090".to_owned(),
            compute_capability: "sm_89".to_owned(),
            driver_version: "580.12".to_owned(),
            harness_version: HARNESS_VERSION.to_owned(),
            run_nonce_sha256: "f".repeat(64),
            transcript_sha256: "1".repeat(64),
            evidence_manifest_sha256: "2".repeat(64),
            output_sha256: "3".repeat(64),
            reference_output_sha256: "3".repeat(64),
            reference_receipt_sha256: "4".repeat(64),
            operator_kind: "dense-linear".to_owned(),
            operator_contract_sha256: "5".repeat(64),
            operator_weight_inventory_sha256: "6".repeat(64),
            executed_projection_count: 1,
            declared_projection_count: 0,
            baseline_vram_bytes: 1,
            peak_vram_bytes: 2,
            wall_clock_ms: 1,
            quality: Ltx25QuantQuality {
                reference_psnr: 120.0,
                reference_ssim: 1.0,
                temporal_boundary_drift: 0.0,
                silent_zero_video_passed: true,
                silent_zero_audio_passed: true,
            },
        })
    }

    fn image(values: &[u8]) -> ImageRecord {
        ImageRecord {
            width: 1,
            height: 1,
            pixels: values.to_vec(),
        }
    }

    #[test]
    fn output_comparator_covers_psnr_ssim_temporal_drift_and_both_silent_zero_gates() {
        let reference = CapturedOutput {
            frames: vec![image(&[10, 20, 30]), image(&[20, 30, 40])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.0, 0.25],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        let exact = compare_outputs(&reference, &reference).unwrap();
        assert_eq!(exact.reference_psnr, 120.0);
        assert!((exact.reference_ssim - 1.0).abs() < 1e-12);
        assert_eq!(exact.temporal_boundary_drift, 0.0);
        assert!(exact.silent_zero_video_passed && exact.silent_zero_audio_passed);
        let mut silent = reference.clone();
        silent.audio.as_mut().unwrap().samples.fill(0.0);
        assert!(
            !compare_outputs(&silent, &reference)
                .unwrap()
                .silent_zero_audio_passed
        );
    }

    #[test]
    fn output_artifact_round_trip_is_exact_and_truncation_is_refused() {
        let root = tempfile::tempdir().unwrap();
        let path = root.path().join("output.bin");
        let output = CapturedOutput {
            frames: vec![image(&[1, 2, 3])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.5],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        write_captured_output(&path, &output).unwrap();
        assert_eq!(
            read_captured_output(&path).unwrap().frames[0].pixels,
            vec![1, 2, 3]
        );
        let mut bytes = fs::read(&path).unwrap();
        bytes.pop();
        fs::write(&path, bytes).unwrap();
        assert!(read_captured_output(&path)
            .unwrap_err()
            .to_string()
            .contains("truncated"));
    }

    #[test]
    fn observed_geometry_comes_from_output_and_rejects_malformed_frames() {
        let output = CapturedOutput {
            frames: vec![
                ImageRecord {
                    width: 2,
                    height: 1,
                    pixels: vec![1; 6],
                },
                ImageRecord {
                    width: 2,
                    height: 1,
                    pixels: vec![2; 6],
                },
            ],
            fps: 24,
            audio: None,
        };
        assert_eq!(observed_geometry(&output).unwrap(), (2, 1, 2, 24));

        let mut changed = output.clone();
        changed.frames[1].width = 1;
        assert!(observed_geometry(&changed)
            .unwrap_err()
            .to_string()
            .contains("inconsistent or malformed"));

        let mut truncated = output;
        truncated.frames[0].pixels.pop();
        assert!(observed_geometry(&truncated)
            .unwrap_err()
            .to_string()
            .contains("inconsistent or malformed"));
    }

    #[test]
    fn quant_candidate_accepts_a_distinct_explicit_bf16_snapshot_identity_only() {
        let receipt = bf16_receipt();
        let candidate = measurement_case("ltx25-int8-convrot-ada-v1").unwrap();
        let hardware = HardwareIdentity {
            gpu_name: receipt.gpu_name.clone(),
            driver_version: receipt.driver_version.clone(),
            compute_cap: (8, 9),
            generation: Ltx25GpuGeneration::AdaSm89,
            physical_ordinal: 0,
        };
        assert!(reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &receipt.executable_sha256,
            &receipt.model_revision,
        ));
        assert!(reference_receipt_matches_bundle(
            &receipt,
            &receipt.model_revision,
            &receipt.model_inventory_sha256,
            &receipt.runtime_bundle_sha256,
        ));
        let candidate_inventory = "9".repeat(64);
        assert_ne!(candidate_inventory, receipt.model_inventory_sha256);

        assert!(!reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &"0".repeat(64),
            &receipt.model_revision,
        ));
        assert!(!reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &receipt.executable_sha256,
            &"0".repeat(40),
        ));
        let mut wrong_reference = receipt.clone();
        wrong_reference.reference_model_inventory_sha256 = "0".repeat(64);
        assert!(!reference_receipt_matches_bundle(
            &wrong_reference,
            &receipt.model_revision,
            &receipt.model_inventory_sha256,
            &receipt.runtime_bundle_sha256,
        ));
    }

    #[test]
    fn terminal_acknowledgement_is_explicit_and_stable() {
        assert_eq!(
            TERMINAL_ACKNOWLEDGEMENT,
            "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY"
        );
        let error = run(TerminalMeasurementConfig {
            acknowledgement: "ordinary-generation".to_owned(),
            case_id: "ltx25-bf16-ada-v1".to_owned(),
            snapshot: PathBuf::from("unused"),
            model_revision: "0".repeat(40),
            output_dir: PathBuf::from("/unused"),
            reference_snapshot: None,
            reference_model_revision: None,
            reference_output: None,
            reference_receipt: None,
        })
        .unwrap_err()
        .to_string();
        assert!(error.contains("terminal-only acknowledgement"), "{error}");
    }

    #[cfg(unix)]
    #[test]
    fn model_inventory_hashes_hf_blob_symlinks_by_logical_snapshot_path() {
        use std::os::unix::fs::symlink;

        let cache = tempfile::tempdir().unwrap();
        let repo = cache.path().join("models--scene--ltx");
        let blobs = repo.join("blobs");
        let revision = "1".repeat(40);
        let root = repo.join("snapshots").join(&revision);
        fs::create_dir_all(root.join("nested")).unwrap();
        fs::create_dir_all(&blobs).unwrap();
        fs::write(blobs.join("blob"), b"exact-model-bytes").unwrap();
        symlink(
            "../../../blobs/blob",
            root.join("nested/transformer.safetensors"),
        )
        .unwrap();
        let inventory = inventory_for_snapshot(&root).unwrap();
        assert_eq!(inventory.entries.len(), 1);
        assert_eq!(inventory.entries[0].path, "nested/transformer.safetensors");
        assert_eq!(
            inventory.entries[0].symlink_target.as_deref(),
            Some("blobs/blob")
        );
        assert_eq!(
            inventory.entries[0].sha256,
            sha256_hex(b"exact-model-bytes")
        );

        fs::write(blobs.join("second-blob"), b"exact-model-bytes").unwrap();
        fs::remove_file(root.join("nested/transformer.safetensors")).unwrap();
        symlink(
            "../../../blobs/second-blob",
            root.join("nested/transformer.safetensors"),
        )
        .unwrap();
        let retargeted = inventory_for_snapshot(&root).unwrap();
        assert_ne!(
            inventory, retargeted,
            "retargeting a model symlink must invalidate the pre-generation inventory even when the followed bytes match"
        );
    }

    #[cfg(unix)]
    #[test]
    fn model_inventory_rejects_a_symlink_escaping_the_hf_repository_blobs() {
        use std::os::unix::fs::symlink;

        let cache = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let repo = cache.path().join("models--scene--ltx");
        let revision = "2".repeat(40);
        let root = repo.join("snapshots").join(revision);
        fs::create_dir_all(repo.join("blobs")).unwrap();
        fs::create_dir_all(&root).unwrap();
        fs::write(outside.path().join("escaped"), b"same-looking-model").unwrap();
        symlink(
            outside.path().join("escaped"),
            root.join("transformer.safetensors"),
        )
        .unwrap();
        let error = inventory_for_snapshot(&root).unwrap_err().to_string();
        assert!(
            error.contains("outside the repository blob cache"),
            "{error}"
        );
    }

    #[test]
    fn materialized_snapshot_files_do_not_require_a_blobs_directory() {
        let cache = tempfile::tempdir().unwrap();
        let revision = "3".repeat(40);
        let root = cache.path().join("repo/snapshots").join(revision);
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join("transformer.safetensors"), b"materialized").unwrap();
        let inventory = inventory_for_snapshot(&root).unwrap();
        assert_eq!(inventory.entries.len(), 1);
        assert_eq!(inventory.entries[0].symlink_target, None);
    }
}
