//! Explicit, terminal-only LTX-2.5 quant measurement controller (sc-18777).
//!
//! This module is compiled only with `terminal-quant-measurement`; no runtime bundle enables that
//! feature. One invocation creates a new evidence directory, renders one immutable case through the
//! unadmitted measurement seam, writes the generated bytes, transcript and exact model inventory,
//! then seals a receipt over those files. Candidate modes require a sealed bf16 reference from the
//! same code/model/GPU/driver/fixture identity. Partial or failed directories never contain a receipt.

use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::Instant;

#[cfg(feature = "cuda")]
use candle_gen::candle_core::Device;
use candle_gen::gen_core::{
    AudioTrack, GenerationOutput, GenerationRequest, Image, LoadSpec, Progress, Quant,
    WeightsSource,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};

use crate::quant_eval::{
    measurement_case, Ltx25GpuGeneration, Ltx25QuantMeasurementDraft, Ltx25QuantMeasurementReceipt,
    Ltx25QuantMode, Ltx25QuantQuality,
};

pub const TERMINAL_ACKNOWLEDGEMENT: &str = "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY";
pub const HARNESS_VERSION: &str = "sc-18777-terminal-v2";
const PROMPT: &str =
    "a red fox walking through snowy pines, slow cinematic dolly, detailed natural motion";
const OUTPUT_MAGIC: &[u8] = b"LTX25-QUANT-OUTPUT-V1\0";

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

#[derive(Clone, Debug)]
pub struct TerminalMeasurementConfig {
    pub acknowledgement: String,
    pub case_id: String,
    pub snapshot: PathBuf,
    pub model_revision: String,
    pub output_dir: PathBuf,
    pub reference_output: Option<PathBuf>,
    pub reference_receipt: Option<PathBuf>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct InventoryEntry {
    path: String,
    bytes: u64,
    sha256: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct ModelInventory {
    schema_version: &'static str,
    entries: Vec<InventoryEntry>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceArtifact {
    path: String,
    bytes: u64,
    sha256: String,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceManifest {
    schema_version: &'static str,
    case_id: String,
    run_nonce_sha256: String,
    artifacts: Vec<EvidenceArtifact>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct CapturedOutput {
    frames: Vec<ImageRecord>,
    fps: u32,
    audio: Option<AudioRecord>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct ImageRecord {
    width: u32,
    height: u32,
    pixels: Vec<u8>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct AudioRecord {
    samples: Vec<f32>,
    sample_rate: u32,
    channels: u16,
}

#[derive(Clone, Debug)]
struct HardwareIdentity {
    gpu_name: String,
    driver_version: String,
    compute_cap: (i32, i32),
    generation: Ltx25GpuGeneration,
    physical_ordinal: usize,
}

/// Execute one case and return the same receipt written to `<output-dir>/receipt.json`.
pub fn run(config: TerminalMeasurementConfig) -> Result<Ltx25QuantMeasurementReceipt> {
    if config.acknowledgement != TERMINAL_ACKNOWLEDGEMENT {
        return Err(invalid(format!(
            "terminal-only acknowledgement must equal {TERMINAL_ACKNOWLEDGEMENT:?}"
        ))
        .into());
    }
    let case = measurement_case(&config.case_id)
        .ok_or_else(|| invalid(format!("unknown terminal case {:?}", config.case_id)))?;
    require_lower_hex("model revision", &config.model_revision, 40)?;
    if !config.output_dir.is_absolute() {
        return Err(invalid("output directory must be an absolute path").into());
    }
    if config.output_dir.exists() {
        return Err(invalid(format!(
            "output directory {} already exists; evidence runs never append or overwrite",
            config.output_dir.display()
        ))
        .into());
    }

    let repo_root = git_repo_root()?;
    let inference_revision = clean_git_revision(&repo_root)?;
    let snapshot = fs::canonicalize(&config.snapshot).map_err(|error| {
        invalid(format!(
            "cannot canonicalize snapshot {}: {error}",
            config.snapshot.display()
        ))
    })?;
    if !snapshot.is_dir() {
        return Err(invalid(format!(
            "snapshot {} is not a directory",
            snapshot.display()
        ))
        .into());
    }
    if !snapshot.ancestors().any(|ancestor| {
        ancestor
            .file_name()
            .is_some_and(|name| name == config.model_revision.as_str())
    }) {
        return Err(invalid(format!(
            "snapshot {} is not nested beneath declared immutable model revision {}",
            snapshot.display(),
            config.model_revision
        ))
        .into());
    }
    let output_parent = config
        .output_dir
        .parent()
        .ok_or_else(|| invalid("output directory has no parent"))?;
    fs::create_dir_all(output_parent)?;
    let output_parent = fs::canonicalize(output_parent)?;
    if output_parent.starts_with(&repo_root) || output_parent.starts_with(&snapshot) {
        return Err(invalid(
            "evidence output must be outside both the inference worktree and model snapshot",
        )
        .into());
    }

    let hardware = hardware_identity()?;
    if hardware.generation != case.gpu {
        return Err(invalid(format!(
            "case {} requires {}, detected {} (sm_{}{})",
            case.id,
            case.gpu.id(),
            hardware.generation.id(),
            hardware.compute_cap.0,
            hardware.compute_cap.1,
        ))
        .into());
    }
    if case.mode == Ltx25QuantMode::Nvfp4 && hardware.compute_cap != (12, 0) {
        return Err(invalid(
            "NVFP4 is restricted to exact consumer Blackwell sm_120; datacenter Blackwell is not accepted",
        )
        .into());
    }

    fs::create_dir(&config.output_dir)?;
    let nonce = rand::random::<[u8; 32]>();
    let run_nonce_sha256 = sha256_hex(&nonce);

    let inventory_path = config.output_dir.join("model-inventory.json");
    let inventory = inventory_for(&snapshot)?;
    write_json(&inventory_path, &inventory)?;
    let model_inventory_sha256 = sha256_file(&inventory_path)?;

    let mut transcript = vec![
        json!({
            "event": "start",
            "harnessVersion": HARNESS_VERSION,
            "caseId": case.id,
            "runNonceSha256": run_nonce_sha256,
            "inferenceRevision": inference_revision,
            "modelRevision": config.model_revision,
        }),
        json!({
            "event": "hardware",
            "gpuName": hardware.gpu_name,
            "driverVersion": hardware.driver_version,
            "physicalOrdinal": hardware.physical_ordinal,
            "computeCapability": format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
            "generation": hardware.generation.id(),
        }),
        json!({
            "event": "fixture",
            "fixture": case.fixture,
            "mode": case.mode.id(),
            "width": case.width,
            "height": case.height,
            "frames": case.frames,
            "fps": case.fps,
            "seed": case.seed,
            "promptSha256": sha256_hex(PROMPT.as_bytes()),
            "modelInventorySha256": model_inventory_sha256,
        }),
    ];

    let baseline_mib = candle_gen::testkit::used_mib(hardware.physical_ordinal)
        .ok_or_else(|| invalid("trusted nvidia-smi could not read the pre-run VRAM baseline"))?;
    let sampler = candle_gen::testkit::PeakSampler::start(hardware.physical_ordinal);
    let started = Instant::now();
    let mut spec = LoadSpec::new(WeightsSource::Dir(snapshot.clone()));
    spec.quantize = match case.mode {
        Ltx25QuantMode::Bf16 => None,
        Ltx25QuantMode::Q4 => Some(Quant::Q4),
        Ltx25QuantMode::PackedQ8 | Ltx25QuantMode::Int8ConvRot => Some(Quant::Q8),
        Ltx25QuantMode::Nvfp4 => Some(Quant::Nvfp4),
    };
    let generator = crate::load_25_for_terminal_measurement(&spec, case)?;
    let request = GenerationRequest {
        prompt: PROMPT.to_owned(),
        width: case.width,
        height: case.height,
        count: 1,
        seed: Some(case.seed),
        frames: Some(case.frames),
        fps: Some(case.fps),
        sampler: Some("rectified-flow".to_owned()),
        ..Default::default()
    };
    let mut progress = Vec::new();
    let output = generator.generate(&request, &mut |event: Progress| {
        progress.push(format!("{event:?}"));
    })?;
    let wall_clock_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);
    let peak_mib = sampler.stop();
    if peak_mib == 0 || peak_mib < baseline_mib {
        return Err(invalid(format!(
            "invalid VRAM samples: baseline={baseline_mib} MiB peak={peak_mib} MiB"
        ))
        .into());
    }
    let captured = capture_output(output)?;
    let output_path = config.output_dir.join("generated-output.bin");
    write_captured_output(&output_path, &captured)?;
    let output_sha256 = sha256_file(&output_path)?;

    let (reference, reference_output_sha256, mut reference_artifacts) =
        if case.mode == Ltx25QuantMode::Bf16 {
            (captured.clone(), output_sha256.clone(), Vec::new())
        } else {
            load_and_copy_reference(
                &config,
                &config.output_dir,
                case,
                &hardware,
                &inference_revision,
            )?
        };
    let quality = compare_outputs(&captured, &reference)?;
    if !quality.silent_zero_video_passed || !quality.silent_zero_audio_passed {
        return Err(invalid("generated output failed the video or audio silent-zero gate").into());
    }

    transcript.push(json!({
        "event": "result",
        "progress": progress,
        "baselineVramBytes": baseline_mib * 1024 * 1024,
        "peakVramBytes": peak_mib * 1024 * 1024,
        "wallClockMs": wall_clock_ms,
        "outputSha256": output_sha256,
        "referenceOutputSha256": reference_output_sha256,
        "quality": quality,
    }));
    let transcript_path = config.output_dir.join("transcript.jsonl");
    write_transcript(&transcript_path, &transcript)?;
    let transcript_sha256 = sha256_file(&transcript_path)?;

    let mut artifacts = vec![
        artifact(&config.output_dir, &inventory_path)?,
        artifact(&config.output_dir, &output_path)?,
        artifact(&config.output_dir, &transcript_path)?,
    ];
    artifacts.append(&mut reference_artifacts);
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    let evidence_manifest = EvidenceManifest {
        schema_version: "sceneworks-ltx25-quant-evidence-v2",
        case_id: case.id.to_owned(),
        run_nonce_sha256: run_nonce_sha256.clone(),
        artifacts,
    };
    let manifest_path = config.output_dir.join("evidence-manifest.json");
    write_json(&manifest_path, &evidence_manifest)?;
    let evidence_manifest_sha256 = sha256_file(&manifest_path)?;

    let receipt = Ltx25QuantMeasurementReceipt::seal(Ltx25QuantMeasurementDraft {
        case_id: case.id.to_owned(),
        mode: case.mode,
        gpu_generation: case.gpu,
        fixture: case.fixture.to_owned(),
        width: case.width,
        height: case.height,
        frames: case.frames,
        fps: case.fps,
        seed: case.seed,
        inference_revision,
        model_revision: config.model_revision,
        model_inventory_sha256,
        gpu_name: hardware.gpu_name,
        compute_capability: format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
        driver_version: hardware.driver_version,
        harness_version: HARNESS_VERSION.to_owned(),
        run_nonce_sha256,
        transcript_sha256,
        evidence_manifest_sha256,
        output_sha256,
        reference_output_sha256,
        baseline_vram_bytes: baseline_mib * 1024 * 1024,
        peak_vram_bytes: peak_mib * 1024 * 1024,
        wall_clock_ms,
        quality,
    });
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "refusing to write invalid receipt: {}",
            errors.join("; ")
        ))
        .into());
    }
    write_json(&config.output_dir.join("receipt.json"), &receipt)?;
    Ok(receipt)
}

#[cfg(feature = "cuda")]
fn hardware_identity() -> Result<HardwareIdentity> {
    use candle_gen::candle_core::cuda::cudarc::driver::sys::CUdevice_attribute as Attr;
    let device = candle_gen::default_device()?;
    let Device::Cuda(cuda) = &device else {
        return Err(invalid("terminal quant measurement requires a CUDA device").into());
    };
    let context = cuda.cuda_stream().context();
    let major = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR)?;
    let minor = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR)?;
    let generation = Ltx25GpuGeneration::from_compute_cap(Some((major, minor)));
    let physical_ordinal = candle_gen::testkit::probe_gpu();
    let nvidia_smi = candle_gen::gpu::resolve_nvidia_smi()
        .ok_or_else(|| invalid("trusted absolute nvidia-smi path is unavailable"))?;
    let output = Command::new(nvidia_smi)
        .args([
            "--query-gpu=name,driver_version",
            "--format=csv,noheader,nounits",
            "-i",
            &physical_ordinal.to_string(),
        ])
        .output()?;
    if !output.status.success() {
        return Err(invalid(format!(
            "nvidia-smi identity query failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
        .into());
    }
    let line = String::from_utf8(output.stdout)?;
    let (gpu_name, driver_version) = line
        .trim()
        .split_once(',')
        .ok_or_else(|| invalid(format!("malformed nvidia-smi identity row {line:?}")))?;
    if gpu_name.trim().is_empty() || driver_version.trim().is_empty() {
        return Err(invalid("nvidia-smi returned an empty GPU name or driver version").into());
    }
    Ok(HardwareIdentity {
        gpu_name: gpu_name.trim().to_owned(),
        driver_version: driver_version.trim().to_owned(),
        compute_cap: (major, minor),
        generation,
        physical_ordinal,
    })
}

#[cfg(not(feature = "cuda"))]
fn hardware_identity() -> Result<HardwareIdentity> {
    Err(invalid("terminal quant measurement requires the cuda feature").into())
}

fn git_repo_root() -> Result<PathBuf> {
    let output = Command::new("git")
        .args(["rev-parse", "--show-toplevel"])
        .output()?;
    if !output.status.success() {
        return Err(invalid("run the controller from an inference git worktree").into());
    }
    Ok(fs::canonicalize(String::from_utf8(output.stdout)?.trim())?)
}

fn clean_git_revision(root: &Path) -> Result<String> {
    let revision = git_output(root, &["rev-parse", "HEAD"])?;
    require_lower_hex("inference revision", &revision, 40)?;
    let status = git_output(root, &["status", "--porcelain", "--untracked-files=no"])?;
    if !status.is_empty() {
        return Err(invalid(format!(
            "inference worktree is dirty; commit the exact controller/runtime before measuring:\n{status}"
        ))
        .into());
    }
    Ok(revision)
}

fn git_output(root: &Path, args: &[&str]) -> Result<String> {
    let output = Command::new("git")
        .arg("-C")
        .arg(root)
        .args(args)
        .output()?;
    if !output.status.success() {
        return Err(invalid(format!(
            "git {} failed: {}",
            args.join(" "),
            String::from_utf8_lossy(&output.stderr)
        ))
        .into());
    }
    Ok(String::from_utf8(output.stdout)?.trim().to_owned())
}

fn inventory_for(root: &Path) -> Result<ModelInventory> {
    fn visit(root: &Path, dir: &Path, files: &mut Vec<PathBuf>) -> Result<()> {
        for entry in fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            let metadata = fs::symlink_metadata(&path)?;
            if metadata.file_type().is_symlink() {
                if fs::metadata(&path)?.is_file() {
                    // Hugging Face snapshots normally symlink into the content-addressed blob
                    // store. Hash the resolved bytes under the snapshot-relative logical path;
                    // never include the machine-specific blob-store path in the identity.
                    files.push(path);
                } else {
                    return Err(invalid(format!(
                        "model inventory refuses non-file symlink {}",
                        path.display()
                    ))
                    .into());
                }
            } else if metadata.is_dir() {
                visit(root, &path, files)?;
            } else if metadata.is_file() {
                let _ = path.strip_prefix(root)?;
                files.push(path);
            }
        }
        Ok(())
    }
    let mut files = Vec::new();
    visit(root, root, &mut files)?;
    files.sort();
    if files.is_empty() {
        return Err(invalid("model snapshot inventory is empty").into());
    }
    let mut entries = Vec::with_capacity(files.len());
    for path in files {
        let relative = path
            .strip_prefix(root)?
            .to_string_lossy()
            .replace('\\', "/");
        entries.push(InventoryEntry {
            path: relative,
            bytes: path.metadata()?.len(),
            sha256: sha256_file(&path)?,
        });
    }
    Ok(ModelInventory {
        schema_version: "sceneworks-model-inventory-v1",
        entries,
    })
}

fn capture_output(output: GenerationOutput) -> Result<CapturedOutput> {
    let GenerationOutput::Video { frames, fps, audio } = output else {
        return Err(invalid("LTX terminal measurement expected a video output").into());
    };
    let frames = frames
        .into_iter()
        .map(
            |Image {
                 width,
                 height,
                 pixels,
             }| ImageRecord {
                width,
                height,
                pixels,
            },
        )
        .collect();
    let audio = audio
        .map(
            |AudioTrack {
                 samples,
                 sample_rate,
                 channels,
                 stems,
             }| {
                if !stems.is_empty() {
                    return Err(invalid(
                        "LTX terminal output unexpectedly contained source-separated stems",
                    ));
                }
                if samples.iter().any(|sample| !sample.is_finite()) {
                    return Err(invalid(
                        "LTX terminal output audio contains NaN or infinity",
                    ));
                }
                Ok(AudioRecord {
                    samples,
                    sample_rate,
                    channels,
                })
            },
        )
        .transpose()?;
    Ok(CapturedOutput { frames, fps, audio })
}

fn write_captured_output(path: &Path, output: &CapturedOutput) -> Result<()> {
    let payload = serde_json::to_vec(output)?;
    let mut file = File::create(path)?;
    file.write_all(OUTPUT_MAGIC)?;
    file.write_all(&(payload.len() as u64).to_le_bytes())?;
    file.write_all(&payload)?;
    file.sync_all()?;
    Ok(())
}

fn read_captured_output(path: &Path) -> Result<CapturedOutput> {
    let bytes = fs::read(path)?;
    let header = OUTPUT_MAGIC.len() + 8;
    if bytes.len() < header || &bytes[..OUTPUT_MAGIC.len()] != OUTPUT_MAGIC {
        return Err(invalid(format!(
            "{} is not an LTX25 output artifact",
            path.display()
        ))
        .into());
    }
    let declared = u64::from_le_bytes(bytes[OUTPUT_MAGIC.len()..header].try_into()?) as usize;
    if bytes.len() - header != declared {
        return Err(invalid(format!(
            "{} has a truncated/extended payload",
            path.display()
        ))
        .into());
    }
    Ok(serde_json::from_slice(&bytes[header..])?)
}

fn load_and_copy_reference(
    config: &TerminalMeasurementConfig,
    output_dir: &Path,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    hardware: &HardwareIdentity,
    inference_revision: &str,
) -> Result<(CapturedOutput, String, Vec<EvidenceArtifact>)> {
    let source_output = config.reference_output.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-output from the matching sealed bf16 case")
    })?;
    let source_receipt = config.reference_receipt.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-receipt from the matching sealed bf16 case")
    })?;
    let receipt: Ltx25QuantMeasurementReceipt = serde_json::from_slice(&fs::read(source_receipt)?)?;
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "bf16 reference receipt is invalid: {}",
            errors.join("; ")
        ))
        .into());
    }
    if receipt.mode != Ltx25QuantMode::Bf16
        || receipt.gpu_generation != case.gpu
        || receipt.gpu_name != hardware.gpu_name
        || receipt.compute_capability
            != format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1)
        || receipt.driver_version != hardware.driver_version
        || receipt.inference_revision != inference_revision
        || receipt.model_revision != config.model_revision
        || receipt.fixture != case.fixture
        || receipt.width != case.width
        || receipt.height != case.height
        || receipt.frames != case.frames
        || receipt.fps != case.fps
        || receipt.seed != case.seed
    {
        return Err(invalid("bf16 reference receipt does not match this exact code/model/GPU/driver/fixture identity").into());
    }
    let source_hash = sha256_file(source_output)?;
    if source_hash != receipt.output_sha256 {
        return Err(invalid("bf16 reference output hash does not match its sealed receipt").into());
    }
    let copied_output = output_dir.join("reference-output.bin");
    let copied_receipt = output_dir.join("reference-receipt.json");
    fs::copy(source_output, &copied_output)?;
    fs::copy(source_receipt, &copied_receipt)?;
    let reference = read_captured_output(&copied_output)?;
    Ok((
        reference,
        source_hash,
        vec![
            artifact(output_dir, &copied_output)?,
            artifact(output_dir, &copied_receipt)?,
        ],
    ))
}

fn compare_outputs(
    candidate: &CapturedOutput,
    reference: &CapturedOutput,
) -> Result<Ltx25QuantQuality> {
    if candidate.fps != reference.fps
        || candidate.frames.len() != reference.frames.len()
        || candidate.frames.is_empty()
    {
        return Err(invalid("candidate/reference frame count or FPS differs").into());
    }
    let mut candidate_pixels = Vec::new();
    let mut reference_pixels = Vec::new();
    for (candidate, reference) in candidate.frames.iter().zip(&reference.frames) {
        if candidate.width != reference.width
            || candidate.height != reference.height
            || candidate.pixels.len() != reference.pixels.len()
            || candidate.pixels.len() != candidate.width as usize * candidate.height as usize * 3
        {
            return Err(
                invalid("candidate/reference frame geometry differs or is malformed").into(),
            );
        }
        candidate_pixels.extend_from_slice(&candidate.pixels);
        reference_pixels.extend_from_slice(&reference.pixels);
    }
    let mse = candidate_pixels
        .iter()
        .zip(&reference_pixels)
        .map(|(&a, &b)| {
            let delta = f64::from(a) - f64::from(b);
            delta * delta
        })
        .sum::<f64>()
        / candidate_pixels.len() as f64;
    let reference_psnr = if mse == 0.0 {
        120.0
    } else {
        10.0 * (255.0_f64.powi(2) / mse).log10()
    };
    let reference_ssim = global_ssim(&candidate_pixels, &reference_pixels);
    let temporal_boundary_drift = temporal_boundary_drift(&candidate.frames, &reference.frames)?;
    let silent_zero_video_passed = candidate_pixels.iter().any(|&value| value != 0)
        && candidate_pixels.iter().min() != candidate_pixels.iter().max();
    let silent_zero_audio_passed = candidate.audio.as_ref().is_some_and(|audio| {
        !audio.samples.is_empty()
            && audio.samples.iter().all(|sample| sample.is_finite())
            && audio.samples.iter().any(|sample| sample.abs() > 1.0e-8)
    });
    Ok(Ltx25QuantQuality {
        reference_psnr,
        reference_ssim,
        temporal_boundary_drift,
        silent_zero_video_passed,
        silent_zero_audio_passed,
    })
}

fn global_ssim(candidate: &[u8], reference: &[u8]) -> f64 {
    let n = candidate.len() as f64;
    let mean_a = candidate.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let mean_b = reference.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let (mut var_a, mut var_b, mut covariance) = (0.0, 0.0, 0.0);
    for (&a, &b) in candidate.iter().zip(reference) {
        let da = f64::from(a) - mean_a;
        let db = f64::from(b) - mean_b;
        var_a += da * da;
        var_b += db * db;
        covariance += da * db;
    }
    let denominator = (n - 1.0).max(1.0);
    var_a /= denominator;
    var_b /= denominator;
    covariance /= denominator;
    let c1 = (0.01_f64 * 255.0).powi(2);
    let c2 = (0.03_f64 * 255.0).powi(2);
    ((2.0 * mean_a * mean_b + c1) * (2.0 * covariance + c2)
        / ((mean_a * mean_a + mean_b * mean_b + c1) * (var_a + var_b + c2)))
        .clamp(0.0, 1.0)
}

fn temporal_boundary_drift(candidate: &[ImageRecord], reference: &[ImageRecord]) -> Result<f64> {
    if candidate.len() < 2 {
        return Ok(0.0);
    }
    let mut sum = 0.0;
    let mut count = 0usize;
    for index in 1..candidate.len() {
        for (((&candidate_now, &candidate_before), &reference_now), &reference_before) in candidate
            [index]
            .pixels
            .iter()
            .zip(&candidate[index - 1].pixels)
            .zip(&reference[index].pixels)
            .zip(&reference[index - 1].pixels)
        {
            let candidate_delta = i16::from(candidate_now) - i16::from(candidate_before);
            let reference_delta = i16::from(reference_now) - i16::from(reference_before);
            sum += f64::from((candidate_delta - reference_delta).unsigned_abs()) / 255.0;
            count += 1;
        }
    }
    if count == 0 {
        return Err(invalid("temporal drift had no samples").into());
    }
    Ok(sum / count as f64)
}

fn artifact(root: &Path, path: &Path) -> Result<EvidenceArtifact> {
    Ok(EvidenceArtifact {
        path: path
            .strip_prefix(root)?
            .to_string_lossy()
            .replace('\\', "/"),
        bytes: path.metadata()?.len(),
        sha256: sha256_file(path)?,
    })
}

fn write_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    let mut file = File::create(path)?;
    file.write_all(&bytes)?;
    file.sync_all()?;
    Ok(())
}

fn write_transcript(path: &Path, events: &[serde_json::Value]) -> Result<()> {
    let mut file = File::create(path)?;
    for event in events {
        serde_json::to_writer(&mut file, event)?;
        file.write_all(b"\n")?;
    }
    file.sync_all()?;
    Ok(())
}

fn sha256_file(path: &Path) -> Result<String> {
    let mut file = File::open(path)?;
    let mut hash = Sha256::new();
    let mut buffer = vec![0_u8; 1024 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hash.update(&buffer[..read]);
    }
    Ok(format!("{:x}", hash.finalize()))
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn require_lower_hex(label: &str, value: &str, length: usize) -> Result<()> {
    if value.len() != length
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(invalid(format!(
            "{label} must be {length} lowercase hexadecimal characters"
        ))
        .into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn image(values: &[u8]) -> ImageRecord {
        ImageRecord {
            width: 1,
            height: 1,
            pixels: values.to_vec(),
        }
    }

    #[test]
    fn output_comparator_covers_psnr_ssim_temporal_drift_and_both_silent_zero_gates() {
        let reference = CapturedOutput {
            frames: vec![image(&[10, 20, 30]), image(&[20, 30, 40])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.0, 0.25],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        let exact = compare_outputs(&reference, &reference).unwrap();
        assert_eq!(exact.reference_psnr, 120.0);
        assert!((exact.reference_ssim - 1.0).abs() < 1e-12);
        assert_eq!(exact.temporal_boundary_drift, 0.0);
        assert!(exact.silent_zero_video_passed && exact.silent_zero_audio_passed);
        let mut silent = reference.clone();
        silent.audio.as_mut().unwrap().samples.fill(0.0);
        assert!(
            !compare_outputs(&silent, &reference)
                .unwrap()
                .silent_zero_audio_passed
        );
    }

    #[test]
    fn output_artifact_round_trip_is_exact_and_truncation_is_refused() {
        let root = tempfile::tempdir().unwrap();
        let path = root.path().join("output.bin");
        let output = CapturedOutput {
            frames: vec![image(&[1, 2, 3])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.5],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        write_captured_output(&path, &output).unwrap();
        assert_eq!(
            read_captured_output(&path).unwrap().frames[0].pixels,
            vec![1, 2, 3]
        );
        let mut bytes = fs::read(&path).unwrap();
        bytes.pop();
        fs::write(&path, bytes).unwrap();
        assert!(read_captured_output(&path)
            .unwrap_err()
            .to_string()
            .contains("truncated"));
    }

    #[test]
    fn terminal_acknowledgement_is_explicit_and_stable() {
        assert_eq!(
            TERMINAL_ACKNOWLEDGEMENT,
            "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY"
        );
        let error = run(TerminalMeasurementConfig {
            acknowledgement: "ordinary-generation".to_owned(),
            case_id: "ltx25-bf16-ada-v1".to_owned(),
            snapshot: PathBuf::from("unused"),
            model_revision: "0".repeat(40),
            output_dir: PathBuf::from("/unused"),
            reference_output: None,
            reference_receipt: None,
        })
        .unwrap_err()
        .to_string();
        assert!(error.contains("terminal-only acknowledgement"), "{error}");
    }

    #[cfg(unix)]
    #[test]
    fn model_inventory_hashes_hf_style_file_symlinks_by_logical_snapshot_path() {
        use std::os::unix::fs::symlink;

        let root = tempfile::tempdir().unwrap();
        let blobs = tempfile::tempdir().unwrap();
        fs::write(blobs.path().join("blob"), b"exact-model-bytes").unwrap();
        fs::create_dir(root.path().join("nested")).unwrap();
        symlink(
            blobs.path().join("blob"),
            root.path().join("nested/transformer.safetensors"),
        )
        .unwrap();
        let inventory = inventory_for(root.path()).unwrap();
        assert_eq!(inventory.entries.len(), 1);
        assert_eq!(inventory.entries[0].path, "nested/transformer.safetensors");
        assert_eq!(
            inventory.entries[0].sha256,
            sha256_hex(b"exact-model-bytes")
        );
    }
}
