//! Explicit, terminal-only LTX-2.5 quant measurement controller (sc-18777).
//!
//! This module is compiled only with `terminal-quant-measurement`; no runtime bundle enables that
//! feature. One invocation creates a new evidence directory, renders one immutable case through the
//! unadmitted measurement seam, writes the generated bytes, transcript and exact model inventory,
//! then seals a receipt over those files. Candidate modes require a sealed bf16 reference from the
//! same code/model/GPU/driver/fixture identity. Partial or failed directories never contain a receipt.

use std::collections::{BTreeMap, BTreeSet};
use std::fs::{self, File};
use std::io::{self, Read, Write};
use std::path::{Path, PathBuf};
#[cfg(feature = "cuda")]
use std::process::Command;
use std::time::Instant;

#[cfg(feature = "cuda")]
use candle_gen::candle_core::Device;
use candle_gen::gen_core::{
    AudioTrack, GenerationOutput, GenerationRequest, Image, Progress, Quant,
};
use serde::{Deserialize, Serialize};
use serde_json::json;
use sha2::{Digest, Sha256};

use crate::dev_sampler::TransformerVariant;
use crate::quant_eval::{
    bundle_identity_sha256, inventory_for_snapshot, measurement_case, promotion_copy_sha256,
    selected_bundle_identity_sha256, snapshot_inventory_sha256, Ltx25GpuGeneration,
    Ltx25QuantMeasurementDraft, Ltx25QuantMeasurementReceipt, Ltx25QuantMode, Ltx25QuantQuality,
    Ltx25QuantRuntimeBindings, Ltx25QuantRuntimeIdentity, RUNTIME_BINDING_FILE,
    RUNTIME_BINDING_SCHEMA, TERMINAL_MEASUREMENT_CASES,
};

pub const TERMINAL_ACKNOWLEDGEMENT: &str = "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY";
pub const HARNESS_VERSION: &str = "sc-18777-terminal-v5";
pub const CAMPAIGN_SCHEMA: &str = "sceneworks-ltx25-quant-campaign-v1";
pub const PROMOTION_SCHEMA: &str = "sceneworks-ltx25-quant-promotion-v1";
const EVIDENCE_SCHEMA: &str = "sceneworks-ltx25-quant-evidence-v3";
const PROMPT: &str =
    "a red fox walking through snowy pines, slow cinematic dolly, detailed natural motion";
const OUTPUT_MAGIC: &[u8] = b"LTX25-QUANT-OUTPUT-V1\0";

type Result<T> = std::result::Result<T, Box<dyn std::error::Error + Send + Sync>>;

fn invalid(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidInput, message.into())
}

fn quant_for_mode(mode: Ltx25QuantMode) -> Option<Quant> {
    match mode {
        Ltx25QuantMode::Bf16 => None,
        Ltx25QuantMode::Q4 => Some(Quant::Q4),
        Ltx25QuantMode::PackedQ8 | Ltx25QuantMode::Int8ConvRot => Some(Quant::Q8),
        Ltx25QuantMode::Nvfp4 => Some(Quant::Nvfp4),
    }
}

#[derive(Clone, Debug)]
pub struct TerminalMeasurementConfig {
    pub acknowledgement: String,
    pub case_id: String,
    pub snapshot: PathBuf,
    pub bundle_subdir: PathBuf,
    pub model_revision: String,
    pub output_dir: PathBuf,
    pub reference_snapshot: Option<PathBuf>,
    pub reference_bundle_subdir: Option<PathBuf>,
    pub reference_model_revision: Option<String>,
    pub reference_output: Option<PathBuf>,
    pub reference_receipt: Option<PathBuf>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TerminalCampaignManifest {
    pub schema_version: String,
    pub cases: Vec<TerminalCampaignCase>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TerminalCampaignCase {
    pub case_id: String,
    pub snapshot_root: PathBuf,
    pub model_revision: String,
    pub bundle_subdir: PathBuf,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TerminalPromotionInput {
    pub schema_version: String,
    pub cases: Vec<TerminalPromotionCase>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TerminalPromotionCase {
    pub case_id: String,
    pub public_snapshot_root: PathBuf,
    pub public_model_revision: String,
    pub public_bundle_subdir: PathBuf,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PromotionManifest {
    schema_version: &'static str,
    accepted_allowlist: EvidenceArtifact,
    snapshots: Vec<PromotionSnapshot>,
}

#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
struct PromotionSnapshot {
    model_revision: String,
    model_inventory_sha256: String,
    public_snapshot_root: String,
    runtime_binding: EvidenceArtifact,
    case_ids: Vec<String>,
}

struct BundleObservation {
    snapshot_root: PathBuf,
    model_inventory_sha256: String,
    bundle_subdir: String,
    runtime_bundle_sha256: String,
    selected_bundle_sha256: String,
    operator_contract_sha256: String,
}

struct PromotionGroup {
    public_snapshot_root: PathBuf,
    model_revision: String,
    model_inventory_sha256: String,
    bindings: Vec<Ltx25QuantRuntimeIdentity>,
    case_ids: Vec<String>,
}

struct ReferenceEvidence {
    output: CapturedOutput,
    output_sha256: String,
    receipt_sha256: String,
    model_revision: String,
    model_inventory_sha256: String,
    bundle_subdir: String,
    runtime_bundle_sha256: String,
    selected_bundle_sha256: String,
    artifacts: Vec<EvidenceArtifact>,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceArtifact {
    path: String,
    bytes: u64,
    sha256: String,
}

#[derive(Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
struct EvidenceManifest {
    schema_version: String,
    case_id: String,
    run_nonce_sha256: String,
    artifacts: Vec<EvidenceArtifact>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct CapturedOutput {
    frames: Vec<ImageRecord>,
    fps: u32,
    audio: Option<AudioRecord>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct ImageRecord {
    width: u32,
    height: u32,
    pixels: Vec<u8>,
}

#[derive(Clone, Debug, Serialize, Deserialize)]
struct AudioRecord {
    samples: Vec<f32>,
    sample_rate: u32,
    channels: u16,
}

#[derive(Clone, Debug)]
struct HardwareIdentity {
    gpu_name: String,
    driver_version: String,
    compute_cap: (i32, i32),
    generation: Ltx25GpuGeneration,
    physical_ordinal: usize,
}

/// Execute one case and return the same receipt written to `<output-dir>/receipt.json`.
pub fn run(config: TerminalMeasurementConfig) -> Result<Ltx25QuantMeasurementReceipt> {
    if config.acknowledgement != TERMINAL_ACKNOWLEDGEMENT {
        return Err(invalid(format!(
            "terminal-only acknowledgement must equal {TERMINAL_ACKNOWLEDGEMENT:?}"
        ))
        .into());
    }
    let case = measurement_case(&config.case_id)
        .ok_or_else(|| invalid(format!("unknown terminal case {:?}", config.case_id)))?;
    require_lower_hex("model revision", &config.model_revision, 40)?;
    if !config.output_dir.is_absolute() {
        return Err(invalid("output directory must be an absolute path").into());
    }
    if config.output_dir.exists() {
        return Err(invalid(format!(
            "output directory {} already exists; evidence runs never append or overwrite",
            config.output_dir.display()
        ))
        .into());
    }

    if env!("LTX25_BUILD_SOURCE_DIRTY") != "0" {
        return Err(invalid(
            "terminal measurement executable was built from a dirty source tree; rebuild from the committed revision",
        )
        .into());
    }
    let inference_revision = env!("LTX25_BUILD_INFERENCE_REVISION").to_owned();
    require_lower_hex("build-time inference revision", &inference_revision, 40)?;
    let executable_contract_sha256 = env!("LTX25_EXECUTABLE_CONTRACT_SHA256").to_owned();
    require_lower_hex(
        "executable contract SHA-256",
        &executable_contract_sha256,
        64,
    )?;
    let executable = fs::canonicalize(std::env::current_exe()?)?;
    let executable_sha256 = sha256_file(&executable)?;
    let snapshot = canonical_snapshot(&config.snapshot, &config.model_revision, "candidate")?;
    let (mut inspection_spec, bundle_subdir) =
        crate::bundle::select_snapshot_bundle(&snapshot, &config.bundle_subdir)?;
    inspection_spec.quantize = quant_for_mode(case.mode);
    let output_parent = config
        .output_dir
        .parent()
        .ok_or_else(|| invalid("output directory has no parent"))?;
    fs::create_dir_all(output_parent)?;
    let output_parent = fs::canonicalize(output_parent)?;
    if output_parent.starts_with(&snapshot) {
        return Err(invalid("evidence output must be outside the model snapshot").into());
    }

    let hardware = hardware_identity()?;
    if hardware.generation != case.gpu {
        return Err(invalid(format!(
            "case {} requires {}, detected {} (sm_{}{})",
            case.id,
            case.gpu.id(),
            hardware.generation.id(),
            hardware.compute_cap.0,
            hardware.compute_cap.1,
        ))
        .into());
    }
    if case.mode == Ltx25QuantMode::Nvfp4 && hardware.compute_cap != (12, 0) {
        return Err(invalid(
            "NVFP4 is restricted to exact consumer Blackwell sm_120; datacenter Blackwell is not accepted",
        )
        .into());
    }

    fs::create_dir(&config.output_dir)?;
    let nonce = rand::random::<[u8; 32]>();
    let run_nonce_sha256 = sha256_hex(&nonce);

    let inventory_path = config.output_dir.join("model-inventory.json");
    let inventory = inventory_for_snapshot(&snapshot)?;
    write_json(&inventory_path, &inventory)?;
    let model_inventory_sha256 = sha256_file(&inventory_path)?;
    if model_inventory_sha256 != snapshot_inventory_sha256(&inventory)? {
        return Err(invalid(
            "serialized model inventory hash disagrees with runtime inventory hash",
        )
        .into());
    }

    let resolved = crate::bundle::resolve_split_bundle(&inspection_spec)?;
    let observed_variant = TransformerVariant::from_bundle(&resolved)?;
    if observed_variant != case.transformer_variant {
        return Err(invalid(format!(
            "case {} requires transformer variant {}, bundle declares {}",
            case.id,
            case.transformer_variant.id(),
            observed_variant.id()
        ))
        .into());
    }
    let transformer = resolved
        .require(candle_gen::gen_core::LtxComponent::Transformer)?
        .path();
    let source_inspection =
        crate::advanced_quant::inspect_transformer_source(transformer, case.mode)?;
    let runtime_bundle_sha256 = bundle_identity_sha256(
        &resolved,
        &snapshot,
        &inventory,
        &model_inventory_sha256,
        observed_variant,
        case.mode,
    )?;
    let selected_bundle_sha256 = selected_bundle_identity_sha256(
        &resolved,
        &snapshot,
        &bundle_subdir,
        &inventory,
        observed_variant,
        case.mode,
    )?;

    let mut transcript = vec![
        json!({
            "event": "start",
            "harnessVersion": HARNESS_VERSION,
            "caseId": case.id,
            "runNonceSha256": run_nonce_sha256,
            "inferenceRevision": inference_revision,
            "executableContractSha256": executable_contract_sha256,
            "executableSha256": executable_sha256,
            "modelRevision": config.model_revision,
            "bundleSubdir": bundle_subdir,
            "transformerVariant": observed_variant.id(),
            "runtimeBundleSha256": runtime_bundle_sha256,
            "selectedBundleSha256": selected_bundle_sha256,
        }),
        json!({
            "event": "hardware",
            "gpuName": hardware.gpu_name,
            "driverVersion": hardware.driver_version,
            "physicalOrdinal": hardware.physical_ordinal,
            "computeCapability": format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
            "generation": hardware.generation.id(),
        }),
        json!({
            "event": "fixture",
            "fixture": case.fixture,
            "mode": case.mode.id(),
            "width": case.width,
            "height": case.height,
            "frames": case.frames,
            "fps": case.fps,
            "seed": case.seed,
            "promptSha256": sha256_hex(PROMPT.as_bytes()),
            "modelInventorySha256": model_inventory_sha256,
        }),
    ];

    let baseline_mib = candle_gen::testkit::used_mib(hardware.physical_ordinal)
        .ok_or_else(|| invalid("trusted nvidia-smi could not read the pre-run VRAM baseline"))?;
    let sampler = candle_gen::testkit::PeakSampler::start(hardware.physical_ordinal);
    let started = Instant::now();
    crate::advanced_quant::begin_operator_attestation(case.mode);
    let spec = inspection_spec;
    let generator = crate::load_25_for_terminal_measurement(&spec, case)?;
    let request = GenerationRequest {
        prompt: PROMPT.to_owned(),
        width: case.width,
        height: case.height,
        count: 1,
        seed: Some(case.seed),
        frames: Some(case.frames),
        fps: Some(case.fps),
        sampler: Some("rectified-flow".to_owned()),
        ..Default::default()
    };
    let mut progress = Vec::new();
    let output = generator.generate(&request, &mut |event: Progress| {
        progress.push(format!("{event:?}"));
    })?;
    let operator = crate::advanced_quant::finish_operator_attestation()?;
    let wall_clock_ms = u64::try_from(started.elapsed().as_millis()).unwrap_or(u64::MAX);
    let peak_mib = sampler.stop();
    if peak_mib == 0 || peak_mib < baseline_mib {
        return Err(invalid(format!(
            "invalid VRAM samples: baseline={baseline_mib} MiB peak={peak_mib} MiB"
        ))
        .into());
    }
    let captured = capture_output(output)?;
    let observed = observed_geometry(&captured)?;
    if observed != (case.width, case.height, case.frames, case.fps) {
        return Err(invalid(format!(
            "observed output geometry {}x{}x{}@{} does not equal case {}x{}x{}@{}",
            observed.0,
            observed.1,
            observed.2,
            observed.3,
            case.width,
            case.height,
            case.frames,
            case.fps
        ))
        .into());
    }
    let post_inventory = inventory_for_snapshot(&snapshot)?;
    if post_inventory != inventory {
        return Err(invalid(
            "model inventory changed during generation, including a file or followed symlink target",
        )
        .into());
    }
    let output_path = config.output_dir.join("generated-output.bin");
    write_captured_output(&output_path, &captured)?;
    let output_sha256 = sha256_file(&output_path)?;

    let mut reference = if case.mode == Ltx25QuantMode::Bf16 {
        ReferenceEvidence {
            output: captured.clone(),
            output_sha256: output_sha256.clone(),
            receipt_sha256: sha256_hex(b"bf16-self-reference-no-prior-receipt"),
            model_revision: config.model_revision.clone(),
            model_inventory_sha256: model_inventory_sha256.clone(),
            bundle_subdir: bundle_subdir.clone(),
            runtime_bundle_sha256: runtime_bundle_sha256.clone(),
            selected_bundle_sha256: selected_bundle_sha256.clone(),
            artifacts: Vec::new(),
        }
    } else {
        load_and_copy_reference(
            &config,
            &config.output_dir,
            case,
            &hardware,
            &inference_revision,
            &executable_sha256,
        )?
    };
    let quality = compare_outputs(&captured, &reference.output)?;
    if !quality.silent_zero_video_passed || !quality.silent_zero_audio_passed {
        return Err(invalid("generated output failed the video or audio silent-zero gate").into());
    }

    transcript.push(json!({
        "event": "result",
        "progress": progress,
        "baselineVramBytes": baseline_mib * 1024 * 1024,
        "peakVramBytes": peak_mib * 1024 * 1024,
        "wallClockMs": wall_clock_ms,
        "outputSha256": output_sha256,
        "referenceOutputSha256": reference.output_sha256,
        "referenceReceiptSha256": reference.receipt_sha256,
        "referenceModelRevision": reference.model_revision,
        "referenceModelInventorySha256": reference.model_inventory_sha256,
        "referenceRuntimeBundleSha256": reference.runtime_bundle_sha256,
        "quality": quality,
        "observedWidth": observed.0,
        "observedHeight": observed.1,
        "observedFrames": observed.2,
        "observedFps": observed.3,
        "operatorKind": operator.operator_kind,
        "executedProjectionCount": operator.executed_projection_count,
        "declaredProjectionCount": operator.declared_projection_count,
        "operatorWeightInventorySha256": operator.weight_inventory_sha256,
    }));
    let transcript_path = config.output_dir.join("transcript.jsonl");
    write_transcript(&transcript_path, &transcript)?;
    let transcript_sha256 = sha256_file(&transcript_path)?;

    let mut artifacts = vec![
        artifact(&config.output_dir, &inventory_path)?,
        artifact(&config.output_dir, &output_path)?,
        artifact(&config.output_dir, &transcript_path)?,
    ];
    artifacts.append(&mut reference.artifacts);
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    let evidence_manifest = EvidenceManifest {
        schema_version: EVIDENCE_SCHEMA.to_owned(),
        case_id: case.id.to_owned(),
        run_nonce_sha256: run_nonce_sha256.clone(),
        artifacts,
    };
    let manifest_path = config.output_dir.join("evidence-manifest.json");
    write_json(&manifest_path, &evidence_manifest)?;
    let evidence_manifest_sha256 = sha256_file(&manifest_path)?;

    let receipt = Ltx25QuantMeasurementReceipt::seal(Ltx25QuantMeasurementDraft {
        case_id: case.id.to_owned(),
        mode: case.mode,
        gpu_generation: case.gpu,
        transformer_variant: observed_variant,
        fixture: case.fixture.to_owned(),
        observed_width: observed.0,
        observed_height: observed.1,
        observed_frames: observed.2,
        observed_fps: observed.3,
        seed: case.seed,
        inference_revision,
        executable_contract_sha256,
        executable_sha256,
        model_revision: config.model_revision,
        model_inventory_sha256,
        bundle_subdir,
        runtime_bundle_sha256,
        selected_bundle_sha256,
        reference_model_revision: reference.model_revision,
        reference_model_inventory_sha256: reference.model_inventory_sha256,
        reference_bundle_subdir: reference.bundle_subdir,
        reference_runtime_bundle_sha256: reference.runtime_bundle_sha256,
        reference_selected_bundle_sha256: reference.selected_bundle_sha256,
        gpu_name: hardware.gpu_name,
        compute_capability: format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1),
        driver_version: hardware.driver_version,
        harness_version: HARNESS_VERSION.to_owned(),
        run_nonce_sha256,
        transcript_sha256,
        evidence_manifest_sha256,
        output_sha256,
        reference_output_sha256: reference.output_sha256,
        reference_receipt_sha256: reference.receipt_sha256,
        operator_kind: operator.operator_kind,
        operator_contract_sha256: source_inspection.operator_contract_sha256,
        operator_weight_inventory_sha256: operator.weight_inventory_sha256,
        executed_projection_count: operator.executed_projection_count,
        declared_projection_count: operator.declared_projection_count,
        baseline_vram_bytes: baseline_mib * 1024 * 1024,
        peak_vram_bytes: peak_mib * 1024 * 1024,
        wall_clock_ms,
        quality,
    });
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "refusing to write invalid receipt: {}",
            errors.join("; ")
        ))
        .into());
    }
    write_json(&config.output_dir.join("receipt.json"), &receipt)?;
    let runtime_binding = runtime_identity_from_receipt(&receipt);
    write_json(
        &config.output_dir.join(RUNTIME_BINDING_FILE),
        &Ltx25QuantRuntimeBindings {
            schema_version: RUNTIME_BINDING_SCHEMA.to_owned(),
            bindings: vec![runtime_binding],
        },
    )?;
    Ok(receipt)
}

fn runtime_identity_from_receipt(
    receipt: &Ltx25QuantMeasurementReceipt,
) -> Ltx25QuantRuntimeIdentity {
    let mut runtime = Ltx25QuantRuntimeIdentity {
        mode: receipt.mode,
        transformer_variant: receipt.transformer_variant,
        inference_revision: receipt.inference_revision.clone(),
        executable_contract_sha256: receipt.executable_contract_sha256.clone(),
        executable_sha256: receipt.executable_sha256.clone(),
        source_model_revision: receipt.model_revision.clone(),
        source_model_inventory_sha256: receipt.model_inventory_sha256.clone(),
        source_bundle_subdir: receipt.bundle_subdir.clone(),
        source_runtime_bundle_sha256: receipt.runtime_bundle_sha256.clone(),
        source_selected_bundle_sha256: receipt.selected_bundle_sha256.clone(),
        model_revision: receipt.model_revision.clone(),
        model_inventory_sha256: receipt.model_inventory_sha256.clone(),
        bundle_subdir: receipt.bundle_subdir.clone(),
        runtime_bundle_sha256: receipt.runtime_bundle_sha256.clone(),
        selected_bundle_sha256: receipt.selected_bundle_sha256.clone(),
        promotion_copy_sha256: String::new(),
        reference_model_revision: receipt.reference_model_revision.clone(),
        reference_model_inventory_sha256: receipt.reference_model_inventory_sha256.clone(),
        reference_bundle_subdir: receipt.reference_bundle_subdir.clone(),
        reference_runtime_bundle_sha256: receipt.reference_runtime_bundle_sha256.clone(),
        receipt_sha256: receipt.receipt_sha256.clone(),
        transcript_sha256: receipt.transcript_sha256.clone(),
        evidence_manifest_sha256: receipt.evidence_manifest_sha256.clone(),
        output_sha256: receipt.output_sha256.clone(),
        reference_output_sha256: receipt.reference_output_sha256.clone(),
        reference_receipt_sha256: receipt.reference_receipt_sha256.clone(),
        operator_kind: receipt.operator_kind.clone(),
        operator_contract_sha256: receipt.operator_contract_sha256.clone(),
        operator_weight_inventory_sha256: receipt.operator_weight_inventory_sha256.clone(),
    };
    runtime.promotion_copy_sha256 = promotion_copy_sha256(receipt, &runtime);
    runtime
}

fn validated_campaign_cases(
    manifest: &TerminalCampaignManifest,
) -> Result<BTreeMap<&str, &TerminalCampaignCase>> {
    if manifest.schema_version != CAMPAIGN_SCHEMA {
        return Err(invalid(format!(
            "campaign manifest schema must equal {CAMPAIGN_SCHEMA:?}"
        ))
        .into());
    }
    let mut cases = BTreeMap::new();
    for entry in &manifest.cases {
        if measurement_case(&entry.case_id).is_none() {
            return Err(invalid(format!(
                "campaign manifest contains unknown case {:?}",
                entry.case_id
            ))
            .into());
        }
        if cases.insert(entry.case_id.as_str(), entry).is_some() {
            return Err(invalid(format!(
                "campaign manifest repeats case {:?}",
                entry.case_id
            ))
            .into());
        }
    }
    let expected = TERMINAL_MEASUREMENT_CASES
        .iter()
        .map(|case| case.id)
        .collect::<BTreeSet<_>>();
    let actual = cases.keys().copied().collect::<BTreeSet<_>>();
    if actual != expected {
        let missing = expected.difference(&actual).copied().collect::<Vec<_>>();
        let extra = actual.difference(&expected).copied().collect::<Vec<_>>();
        return Err(invalid(format!(
            "campaign manifest must contain the exact terminal case set; missing={missing:?} extra={extra:?}"
        ))
        .into());
    }
    Ok(cases)
}

fn campaign_order() -> impl Iterator<Item = &'static crate::quant_eval::Ltx25QuantMeasurementCase> {
    TERMINAL_MEASUREMENT_CASES
        .iter()
        .filter(|case| case.mode == Ltx25QuantMode::Bf16)
        .chain(
            TERMINAL_MEASUREMENT_CASES
                .iter()
                .filter(|case| case.mode != Ltx25QuantMode::Bf16),
        )
}

/// Run the complete physical campaign serially in one already-built executable.
///
/// Both bf16 variants run first. Every candidate then consumes the matching variant's sealed bf16
/// evidence. `CUDA_VISIBLE_DEVICES` is replaced with one numeric physical ordinal before the first
/// CUDA call; comma-separated or multi-device execution is not representable here.
pub fn run_campaign(
    acknowledgement: &str,
    manifest_path: &Path,
    output_root: &Path,
    physical_gpu_ordinal: usize,
) -> Result<Vec<Ltx25QuantMeasurementReceipt>> {
    if acknowledgement != TERMINAL_ACKNOWLEDGEMENT {
        return Err(invalid(format!(
            "terminal-only acknowledgement must equal {TERMINAL_ACKNOWLEDGEMENT:?}"
        ))
        .into());
    }
    if !output_root.is_absolute() || output_root.exists() {
        return Err(invalid(
            "campaign output root must be an absolute path that does not already exist",
        )
        .into());
    }
    let manifest: TerminalCampaignManifest = serde_json::from_slice(&fs::read(manifest_path)?)?;
    let cases = validated_campaign_cases(&manifest)?;
    std::env::set_var("CUDA_VISIBLE_DEVICES", physical_gpu_ordinal.to_string());

    let mut receipts = Vec::with_capacity(TERMINAL_MEASUREMENT_CASES.len());
    for case in campaign_order() {
        let entry = cases[case.id];
        let reference_case = TERMINAL_MEASUREMENT_CASES.iter().find(|candidate| {
            candidate.mode == Ltx25QuantMode::Bf16
                && candidate.transformer_variant == case.transformer_variant
        });
        let reference = if case.mode == Ltx25QuantMode::Bf16 {
            None
        } else {
            Some(reference_case.expect("validated matrix has one bf16 row per variant"))
        };
        let reference_entry = reference.map(|reference| cases[reference.id]);
        let reference_dir = reference.map(|reference| output_root.join(reference.id));
        receipts.push(run(TerminalMeasurementConfig {
            acknowledgement: acknowledgement.to_owned(),
            case_id: case.id.to_owned(),
            snapshot: entry.snapshot_root.clone(),
            bundle_subdir: entry.bundle_subdir.clone(),
            model_revision: entry.model_revision.clone(),
            output_dir: output_root.join(case.id),
            reference_snapshot: reference_entry.map(|entry| entry.snapshot_root.clone()),
            reference_bundle_subdir: reference_entry.map(|entry| entry.bundle_subdir.clone()),
            reference_model_revision: reference_entry.map(|entry| entry.model_revision.clone()),
            reference_output: reference_dir
                .as_ref()
                .map(|dir| dir.join("generated-output.bin")),
            reference_receipt: reference_dir.as_ref().map(|dir| dir.join("receipt.json")),
        })?);
    }
    Ok(receipts)
}

fn observe_bundle(
    snapshot: &Path,
    revision: &str,
    bundle_subdir: &Path,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    label: &str,
) -> Result<BundleObservation> {
    let snapshot_root = canonical_snapshot(snapshot, revision, label)?;
    let inventory = inventory_for_snapshot(&snapshot_root)?;
    let model_inventory_sha256 = snapshot_inventory_sha256(&inventory)?;
    let (mut spec, bundle_subdir) =
        crate::bundle::select_snapshot_bundle(&snapshot_root, bundle_subdir)?;
    spec.quantize = quant_for_mode(case.mode);
    let bundle = crate::bundle::resolve_split_bundle(&spec)?;
    let variant = TransformerVariant::from_bundle(&bundle)?;
    if variant != case.transformer_variant {
        return Err(invalid(format!(
            "{label} bundle declares transformer variant {}, expected {}",
            variant.id(),
            case.transformer_variant.id()
        ))
        .into());
    }
    let transformer = bundle
        .require(candle_gen::gen_core::LtxComponent::Transformer)?
        .path();
    let inspection = crate::advanced_quant::inspect_transformer_source(transformer, case.mode)?;
    let runtime_bundle_sha256 = bundle_identity_sha256(
        &bundle,
        &snapshot_root,
        &inventory,
        &model_inventory_sha256,
        variant,
        case.mode,
    )?;
    let selected_bundle_sha256 = selected_bundle_identity_sha256(
        &bundle,
        &snapshot_root,
        &bundle_subdir,
        &inventory,
        variant,
        case.mode,
    )?;
    Ok(BundleObservation {
        snapshot_root,
        model_inventory_sha256,
        bundle_subdir,
        runtime_bundle_sha256,
        selected_bundle_sha256,
        operator_contract_sha256: inspection.operator_contract_sha256,
    })
}

fn verify_evidence_manifest(
    evidence_dir: &Path,
    receipt: &Ltx25QuantMeasurementReceipt,
) -> Result<()> {
    let manifest: EvidenceManifest =
        serde_json::from_slice(&fs::read(evidence_dir.join("evidence-manifest.json"))?)?;
    if manifest.schema_version != EVIDENCE_SCHEMA
        || manifest.case_id != receipt.case_id
        || manifest.run_nonce_sha256 != receipt.run_nonce_sha256
    {
        return Err(invalid(format!(
            "{} evidence manifest identity differs from its sealed receipt",
            receipt.case_id
        ))
        .into());
    }

    let expected = [
        "generated-output.bin",
        "model-inventory.json",
        "reference-evidence-manifest.json",
        "reference-model-inventory.json",
        "reference-output.bin",
        "reference-receipt.json",
        "reference-transcript.jsonl",
        "transcript.jsonl",
    ]
    .into_iter()
    .collect::<BTreeSet<_>>();
    let actual = manifest
        .artifacts
        .iter()
        .map(|artifact| artifact.path.as_str())
        .collect::<BTreeSet<_>>();
    if actual != expected || actual.len() != manifest.artifacts.len() {
        return Err(invalid(format!(
            "{} evidence manifest must contain the exact unique advanced-campaign artifact set",
            receipt.case_id
        ))
        .into());
    }

    let canonical_evidence_dir = fs::canonicalize(evidence_dir)?;
    for artifact in manifest.artifacts {
        if artifact.path.is_empty()
            || artifact.path.contains('\\')
            || artifact
                .path
                .split('/')
                .any(|component| component.is_empty() || component == "." || component == "..")
        {
            return Err(invalid(format!(
                "{} evidence manifest contains an unsafe artifact path {:?}",
                receipt.case_id, artifact.path
            ))
            .into());
        }
        let path = fs::canonicalize(evidence_dir.join(&artifact.path))?;
        if !path.starts_with(&canonical_evidence_dir) || !path.is_file() {
            return Err(invalid(format!(
                "{} evidence artifact {:?} escapes its evidence directory or is not a file",
                receipt.case_id, artifact.path
            ))
            .into());
        }
        if path.metadata()?.len() != artifact.bytes || sha256_file(&path)? != artifact.sha256 {
            return Err(invalid(format!(
                "{} evidence artifact {:?} differs from its manifest length/hash",
                receipt.case_id, artifact.path
            ))
            .into());
        }
    }
    Ok(())
}

fn verified_evidence_receipt(
    evidence_root: &Path,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    source: &TerminalCampaignCase,
    observation: &BundleObservation,
) -> Result<Ltx25QuantMeasurementReceipt> {
    let evidence_dir = evidence_root.join(case.id);
    let receipt_path = evidence_dir.join("receipt.json");
    let receipt: Ltx25QuantMeasurementReceipt = serde_json::from_slice(&fs::read(&receipt_path)?)?;
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "{} evidence receipt is invalid: {}",
            case.id,
            errors.join("; ")
        ))
        .into());
    }
    if receipt.case_id != case.id
        || receipt.model_revision != source.model_revision
        || receipt.model_inventory_sha256 != observation.model_inventory_sha256
        || receipt.bundle_subdir != observation.bundle_subdir
        || receipt.runtime_bundle_sha256 != observation.runtime_bundle_sha256
        || receipt.selected_bundle_sha256 != observation.selected_bundle_sha256
        || receipt.operator_contract_sha256 != observation.operator_contract_sha256
    {
        return Err(invalid(format!(
            "{} receipt does not match its re-inventoried measured source bundle",
            case.id
        ))
        .into());
    }
    for (name, expected) in [
        ("model-inventory.json", &receipt.model_inventory_sha256),
        ("generated-output.bin", &receipt.output_sha256),
        ("transcript.jsonl", &receipt.transcript_sha256),
        ("evidence-manifest.json", &receipt.evidence_manifest_sha256),
    ] {
        if sha256_file(&evidence_dir.join(name))? != *expected {
            return Err(invalid(format!(
                "{} evidence artifact {name} differs from its sealed hash",
                case.id
            ))
            .into());
        }
    }
    verify_evidence_manifest(&evidence_dir, &receipt)?;
    let bindings: Ltx25QuantRuntimeBindings =
        serde_json::from_slice(&fs::read(evidence_dir.join(RUNTIME_BINDING_FILE))?)?;
    let expected = runtime_identity_from_receipt(&receipt);
    if bindings.schema_version != RUNTIME_BINDING_SCHEMA
        || bindings.bindings.as_slice() != std::slice::from_ref(&expected)
    {
        return Err(invalid(format!(
            "{} measurement runtime binding differs from its sealed receipt",
            case.id
        ))
        .into());
    }
    Ok(receipt)
}

fn validated_promotion_cases(
    input: &TerminalPromotionInput,
) -> Result<BTreeMap<&str, &TerminalPromotionCase>> {
    if input.schema_version != PROMOTION_SCHEMA {
        return Err(invalid(format!(
            "promotion input schema must equal {PROMOTION_SCHEMA:?}"
        ))
        .into());
    }
    let expected = TERMINAL_MEASUREMENT_CASES
        .iter()
        .filter(|case| {
            matches!(
                case.mode,
                Ltx25QuantMode::Int8ConvRot | Ltx25QuantMode::Nvfp4
            )
        })
        .map(|case| case.id)
        .collect::<BTreeSet<_>>();
    let mut cases = BTreeMap::new();
    for entry in &input.cases {
        if !expected.contains(entry.case_id.as_str()) {
            return Err(invalid(format!(
                "promotion input contains non-promotable case {:?}",
                entry.case_id
            ))
            .into());
        }
        if cases.insert(entry.case_id.as_str(), entry).is_some() {
            return Err(
                invalid(format!("promotion input repeats case {:?}", entry.case_id)).into(),
            );
        }
    }
    let actual = cases.keys().copied().collect::<BTreeSet<_>>();
    if actual != expected {
        return Err(invalid(format!(
            "promotion input must contain the exact production advanced case set; expected={expected:?} actual={actual:?}"
        ))
        .into());
    }
    Ok(cases)
}

fn require_identical_selected_copy(
    case_id: &str,
    source: &BundleObservation,
    public: &BundleObservation,
) -> Result<()> {
    if source.selected_bundle_sha256 != public.selected_bundle_sha256
        || source.operator_contract_sha256 != public.operator_contract_sha256
    {
        return Err(invalid(format!(
            "{case_id} public selected bundle is not a byte/path/component-identical copy of the measured source"
        ))
        .into());
    }
    Ok(())
}

/// Verify a completed campaign against separately published immutable public snapshots and
/// materialize the non-Rust accepted allowlist. Measured receipts are never restamped: each runtime
/// row carries the original source identity, the independently inventoried public identity, and a
/// SHA-256 copy proof. Selected component ids, bundle-relative paths, byte lengths, and hashes must
/// be identical across source and public roots.
pub fn materialize_campaign_promotion(
    acknowledgement: &str,
    campaign_manifest_path: &Path,
    promotion_input_path: &Path,
    evidence_root: &Path,
    output_dir: &Path,
) -> Result<()> {
    if acknowledgement != TERMINAL_ACKNOWLEDGEMENT {
        return Err(invalid(format!(
            "terminal-only acknowledgement must equal {TERMINAL_ACKNOWLEDGEMENT:?}"
        ))
        .into());
    }
    if !evidence_root.is_absolute()
        || !output_dir.is_absolute()
        || output_dir.exists()
        || output_dir.starts_with(evidence_root)
    {
        return Err(invalid(
            "promotion requires absolute evidence/output paths, a new output directory, and output outside evidence",
        )
        .into());
    }
    let campaign: TerminalCampaignManifest =
        serde_json::from_slice(&fs::read(campaign_manifest_path)?)?;
    let source_cases = validated_campaign_cases(&campaign)?;
    let promotion: TerminalPromotionInput =
        serde_json::from_slice(&fs::read(promotion_input_path)?)?;
    let public_cases = validated_promotion_cases(&promotion)?;

    let mut accepted = Vec::new();
    let mut groups = BTreeMap::<(String, String), PromotionGroup>::new();
    for case in TERMINAL_MEASUREMENT_CASES.iter().filter(|case| {
        matches!(
            case.mode,
            Ltx25QuantMode::Int8ConvRot | Ltx25QuantMode::Nvfp4
        )
    }) {
        let source = source_cases[case.id];
        let public = public_cases[case.id];
        let source_observation = observe_bundle(
            &source.snapshot_root,
            &source.model_revision,
            &source.bundle_subdir,
            case,
            "measured source",
        )?;
        let receipt = verified_evidence_receipt(evidence_root, case, source, &source_observation)?;
        let public_observation = observe_bundle(
            &public.public_snapshot_root,
            &public.public_model_revision,
            &public.public_bundle_subdir,
            case,
            "public destination",
        )?;
        require_identical_selected_copy(case.id, &source_observation, &public_observation)?;

        let mut runtime = runtime_identity_from_receipt(&receipt);
        runtime.model_revision = public.public_model_revision.clone();
        runtime.model_inventory_sha256 = public_observation.model_inventory_sha256.clone();
        runtime.bundle_subdir = public_observation.bundle_subdir.clone();
        runtime.runtime_bundle_sha256 = public_observation.runtime_bundle_sha256.clone();
        runtime.selected_bundle_sha256 = public_observation.selected_bundle_sha256.clone();
        runtime.promotion_copy_sha256 = promotion_copy_sha256(&receipt, &runtime);
        accepted.push(crate::quant_eval::Ltx25QuantAcceptedMeasurement {
            receipt,
            runtime: runtime.clone(),
        });

        let key = (
            public.public_model_revision.clone(),
            public_observation.model_inventory_sha256.clone(),
        );
        let group = groups.entry(key).or_insert_with(|| PromotionGroup {
            public_snapshot_root: public_observation.snapshot_root.clone(),
            model_revision: public.public_model_revision.clone(),
            model_inventory_sha256: public_observation.model_inventory_sha256.clone(),
            bindings: Vec::new(),
            case_ids: Vec::new(),
        });
        if group.public_snapshot_root != public_observation.snapshot_root {
            return Err(invalid(
                "one public revision/inventory pair resolved to multiple snapshot roots",
            )
            .into());
        }
        group.bindings.push(runtime);
        group.case_ids.push(case.id.to_owned());
    }

    fs::create_dir(output_dir)?;
    let allowlist_path = output_dir.join("accepted_quant_receipts.allowlist");
    write_json(&allowlist_path, &accepted)?;
    let allowlist_artifact = artifact(output_dir, &allowlist_path)?;
    let mut snapshots = Vec::new();
    for ((revision, inventory), mut group) in groups {
        group.case_ids.sort();
        let directory = output_dir.join(format!("{revision}-{}", &inventory[..12]));
        fs::create_dir(&directory)?;
        let binding_path = directory.join(RUNTIME_BINDING_FILE);
        write_json(
            &binding_path,
            &Ltx25QuantRuntimeBindings {
                schema_version: RUNTIME_BINDING_SCHEMA.to_owned(),
                bindings: group.bindings,
            },
        )?;
        snapshots.push(PromotionSnapshot {
            model_revision: group.model_revision,
            model_inventory_sha256: group.model_inventory_sha256,
            public_snapshot_root: group.public_snapshot_root.to_string_lossy().into_owned(),
            runtime_binding: artifact(output_dir, &binding_path)?,
            case_ids: group.case_ids,
        });
    }
    snapshots.sort_by(|left, right| left.model_revision.cmp(&right.model_revision));
    write_json(
        &output_dir.join("promotion-manifest.json"),
        &PromotionManifest {
            schema_version: PROMOTION_SCHEMA,
            accepted_allowlist: allowlist_artifact,
            snapshots,
        },
    )?;
    Ok(())
}

#[cfg(feature = "cuda")]
fn hardware_identity() -> Result<HardwareIdentity> {
    use candle_gen::candle_core::cuda::cudarc::driver::sys::CUdevice_attribute as Attr;
    let device = candle_gen::default_device()?;
    let Device::Cuda(cuda) = &device else {
        return Err(invalid("terminal quant measurement requires a CUDA device").into());
    };
    let stream = cuda.cuda_stream();
    let context = stream.context();
    let major = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR)?;
    let minor = context.attribute(Attr::CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR)?;
    let generation = Ltx25GpuGeneration::from_compute_cap(Some((major, minor)));
    let physical_ordinal = candle_gen::testkit::probe_gpu();
    let nvidia_smi = candle_gen::gpu::resolve_nvidia_smi()
        .ok_or_else(|| invalid("trusted absolute nvidia-smi path is unavailable"))?;
    let output = Command::new(nvidia_smi)
        .args([
            "--query-gpu=name,driver_version",
            "--format=csv,noheader,nounits",
            "-i",
            &physical_ordinal.to_string(),
        ])
        .output()?;
    if !output.status.success() {
        return Err(invalid(format!(
            "nvidia-smi identity query failed: {}",
            String::from_utf8_lossy(&output.stderr)
        ))
        .into());
    }
    let line = String::from_utf8(output.stdout)?;
    let (gpu_name, driver_version) = line
        .trim()
        .split_once(',')
        .ok_or_else(|| invalid(format!("malformed nvidia-smi identity row {line:?}")))?;
    if gpu_name.trim().is_empty() || driver_version.trim().is_empty() {
        return Err(invalid("nvidia-smi returned an empty GPU name or driver version").into());
    }
    Ok(HardwareIdentity {
        gpu_name: gpu_name.trim().to_owned(),
        driver_version: driver_version.trim().to_owned(),
        compute_cap: (major, minor),
        generation,
        physical_ordinal,
    })
}

#[cfg(not(feature = "cuda"))]
fn hardware_identity() -> Result<HardwareIdentity> {
    Err(invalid("terminal quant measurement requires the cuda feature").into())
}

fn canonical_snapshot(path: &Path, revision: &str, label: &str) -> Result<PathBuf> {
    require_lower_hex(&format!("{label} model revision"), revision, 40)?;
    let root = fs::canonicalize(path).map_err(|error| {
        invalid(format!(
            "cannot canonicalize {label} snapshot {}: {error}",
            path.display()
        ))
    })?;
    if !root.is_dir() {
        return Err(invalid(format!(
            "{label} snapshot {} is not a directory",
            root.display()
        ))
        .into());
    }
    if root.file_name().is_none_or(|name| name != revision)
        || root.parent().and_then(Path::file_name) != Some(std::ffi::OsStr::new("snapshots"))
    {
        return Err(invalid(format!(
            "{label} snapshot {} must be the exact Hugging Face <repo>/snapshots/{revision} directory",
            root.display()
        ))
        .into());
    }
    Ok(root)
}

fn observed_geometry(output: &CapturedOutput) -> Result<(u32, u32, u32, u32)> {
    let first = output
        .frames
        .first()
        .ok_or_else(|| invalid("LTX terminal output contained zero frames"))?;
    if first.width == 0 || first.height == 0 || output.fps == 0 {
        return Err(invalid("LTX terminal output reported zero width, height, or FPS").into());
    }
    for frame in &output.frames {
        if frame.width != first.width
            || frame.height != first.height
            || frame.pixels.len() != frame.width as usize * frame.height as usize * 3
        {
            return Err(invalid(
                "LTX terminal output frame dimensions are inconsistent or malformed",
            )
            .into());
        }
    }
    Ok((
        first.width,
        first.height,
        u32::try_from(output.frames.len())?,
        output.fps,
    ))
}

fn capture_output(output: GenerationOutput) -> Result<CapturedOutput> {
    let GenerationOutput::Video { frames, fps, audio } = output else {
        return Err(invalid("LTX terminal measurement expected a video output").into());
    };
    let frames = frames
        .into_iter()
        .map(
            |Image {
                 width,
                 height,
                 pixels,
             }| ImageRecord {
                width,
                height,
                pixels,
            },
        )
        .collect();
    let audio = audio
        .map(
            |AudioTrack {
                 samples,
                 sample_rate,
                 channels,
                 stems,
             }| {
                if !stems.is_empty() {
                    return Err(invalid(
                        "LTX terminal output unexpectedly contained source-separated stems",
                    ));
                }
                if samples.iter().any(|sample| !sample.is_finite()) {
                    return Err(invalid(
                        "LTX terminal output audio contains NaN or infinity",
                    ));
                }
                Ok(AudioRecord {
                    samples,
                    sample_rate,
                    channels,
                })
            },
        )
        .transpose()?;
    Ok(CapturedOutput { frames, fps, audio })
}

fn write_captured_output(path: &Path, output: &CapturedOutput) -> Result<()> {
    let payload = serde_json::to_vec(output)?;
    let mut file = File::create(path)?;
    file.write_all(OUTPUT_MAGIC)?;
    file.write_all(&(payload.len() as u64).to_le_bytes())?;
    file.write_all(&payload)?;
    file.sync_all()?;
    Ok(())
}

fn read_captured_output(path: &Path) -> Result<CapturedOutput> {
    let bytes = fs::read(path)?;
    let header = OUTPUT_MAGIC.len() + 8;
    if bytes.len() < header || &bytes[..OUTPUT_MAGIC.len()] != OUTPUT_MAGIC {
        return Err(invalid(format!(
            "{} is not an LTX25 output artifact",
            path.display()
        ))
        .into());
    }
    let declared = u64::from_le_bytes(bytes[OUTPUT_MAGIC.len()..header].try_into()?) as usize;
    if bytes.len() - header != declared {
        return Err(invalid(format!(
            "{} has a truncated/extended payload",
            path.display()
        ))
        .into());
    }
    Ok(serde_json::from_slice(&bytes[header..])?)
}

fn load_and_copy_reference(
    config: &TerminalMeasurementConfig,
    output_dir: &Path,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    hardware: &HardwareIdentity,
    inference_revision: &str,
    executable_sha256: &str,
) -> Result<ReferenceEvidence> {
    let reference_revision = config.reference_model_revision.as_deref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-model-revision for the bf16 snapshot")
    })?;
    let reference_snapshot = config.reference_snapshot.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-snapshot for the bf16 model bundle")
    })?;
    let reference_bundle_subdir = config.reference_bundle_subdir.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-bundle-subdir for the bf16 model bundle")
    })?;
    let reference_snapshot =
        canonical_snapshot(reference_snapshot, reference_revision, "reference")?;
    let (reference_spec, reference_bundle_subdir) =
        crate::bundle::select_snapshot_bundle(&reference_snapshot, reference_bundle_subdir)?;
    let source_output = config.reference_output.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-output from the matching sealed bf16 case")
    })?;
    let source_receipt = config.reference_receipt.as_ref().ok_or_else(|| {
        invalid("non-bf16 cases require --reference-receipt from the matching sealed bf16 case")
    })?;
    let source_output = fs::canonicalize(source_output)?;
    let source_receipt = fs::canonicalize(source_receipt)?;
    let evidence_dir = source_receipt
        .parent()
        .ok_or_else(|| invalid("bf16 reference receipt has no evidence directory"))?
        .to_path_buf();
    if source_output.parent() != Some(evidence_dir.as_path())
        || source_output.file_name() != Some(std::ffi::OsStr::new("generated-output.bin"))
        || source_receipt.file_name() != Some(std::ffi::OsStr::new("receipt.json"))
    {
        return Err(invalid(
            "bf16 reference output and receipt must be the canonical generated-output.bin/receipt.json pair from one evidence directory",
        )
        .into());
    }
    let receipt: Ltx25QuantMeasurementReceipt =
        serde_json::from_slice(&fs::read(&source_receipt)?)?;
    let errors = receipt.validation_errors();
    if !errors.is_empty() {
        return Err(invalid(format!(
            "bf16 reference receipt is invalid: {}",
            errors.join("; ")
        ))
        .into());
    }
    if !reference_receipt_matches_campaign(
        &receipt,
        case,
        hardware,
        inference_revision,
        executable_sha256,
        reference_revision,
        &reference_bundle_subdir,
    ) {
        return Err(invalid("bf16 reference receipt does not match this exact code/reference-model/GPU/driver/fixture identity").into());
    }
    let reference_inventory = inventory_for_snapshot(&reference_snapshot)?;
    let reference_inventory_sha256 = snapshot_inventory_sha256(&reference_inventory)?;
    let inventory_path = evidence_dir.join("model-inventory.json");
    if sha256_file(&inventory_path)? != receipt.model_inventory_sha256
        || receipt.model_inventory_sha256 != reference_inventory_sha256
    {
        return Err(invalid(
            "bf16 reference receipt/inventory artifact does not match the explicit reference snapshot",
        )
        .into());
    }
    let reference_bundle = crate::bundle::resolve_split_bundle(&reference_spec)?;
    let reference_variant = TransformerVariant::from_bundle(&reference_bundle)?;
    if reference_variant != case.transformer_variant {
        return Err(invalid(
            "bf16 reference bundle transformer variant differs from candidate case",
        )
        .into());
    }
    let reference_transformer = reference_bundle
        .require(candle_gen::gen_core::LtxComponent::Transformer)?
        .path();
    crate::advanced_quant::inspect_transformer_source(reference_transformer, Ltx25QuantMode::Bf16)?;
    let reference_bundle_sha256 = bundle_identity_sha256(
        &reference_bundle,
        &reference_snapshot,
        &reference_inventory,
        &reference_inventory_sha256,
        reference_variant,
        Ltx25QuantMode::Bf16,
    )?;
    let reference_selected_bundle_sha256 = selected_bundle_identity_sha256(
        &reference_bundle,
        &reference_snapshot,
        &reference_bundle_subdir,
        &reference_inventory,
        reference_variant,
        Ltx25QuantMode::Bf16,
    )?;
    if !reference_receipt_matches_bundle(
        &receipt,
        reference_revision,
        &reference_inventory_sha256,
        &reference_bundle_sha256,
        &reference_selected_bundle_sha256,
    ) {
        return Err(invalid(
            "bf16 reference receipt is not self-bound to the explicit bf16 bundle identity",
        )
        .into());
    }
    let source_hash = sha256_file(&source_output)?;
    if source_hash != receipt.output_sha256 {
        return Err(invalid("bf16 reference output hash does not match its sealed receipt").into());
    }
    let transcript_path = evidence_dir.join("transcript.jsonl");
    let manifest_path = evidence_dir.join("evidence-manifest.json");
    if sha256_file(&transcript_path)? != receipt.transcript_sha256
        || sha256_file(&manifest_path)? != receipt.evidence_manifest_sha256
    {
        return Err(invalid(
            "bf16 reference transcript or evidence manifest hash differs from its receipt",
        )
        .into());
    }
    let sources = [
        (source_output.as_path(), "reference-output.bin"),
        (source_receipt.as_path(), "reference-receipt.json"),
        (inventory_path.as_path(), "reference-model-inventory.json"),
        (transcript_path.as_path(), "reference-transcript.jsonl"),
        (manifest_path.as_path(), "reference-evidence-manifest.json"),
    ];
    let mut artifacts = Vec::with_capacity(sources.len());
    for (source, name) in sources {
        let destination = output_dir.join(name);
        fs::copy(source, &destination)?;
        artifacts.push(artifact(output_dir, &destination)?);
    }
    let copied_output = output_dir.join("reference-output.bin");
    let reference = read_captured_output(&copied_output)?;
    Ok(ReferenceEvidence {
        output: reference,
        output_sha256: source_hash,
        receipt_sha256: sha256_file(&source_receipt)?,
        model_revision: reference_revision.to_owned(),
        model_inventory_sha256: reference_inventory_sha256,
        bundle_subdir: reference_bundle_subdir,
        runtime_bundle_sha256: reference_bundle_sha256,
        selected_bundle_sha256: reference_selected_bundle_sha256,
        artifacts,
    })
}

fn reference_receipt_matches_campaign(
    receipt: &Ltx25QuantMeasurementReceipt,
    case: &crate::quant_eval::Ltx25QuantMeasurementCase,
    hardware: &HardwareIdentity,
    inference_revision: &str,
    executable_sha256: &str,
    reference_revision: &str,
    reference_bundle_subdir: &str,
) -> bool {
    receipt.mode == Ltx25QuantMode::Bf16
        && receipt.gpu_generation == case.gpu
        && receipt.gpu_name == hardware.gpu_name
        && receipt.compute_capability
            == format!("sm_{}{}", hardware.compute_cap.0, hardware.compute_cap.1)
        && receipt.driver_version == hardware.driver_version
        && receipt.inference_revision == inference_revision
        && receipt.executable_contract_sha256 == env!("LTX25_EXECUTABLE_CONTRACT_SHA256")
        && receipt.executable_sha256 == executable_sha256
        && receipt.model_revision == reference_revision
        && receipt.bundle_subdir == reference_bundle_subdir
        && receipt.transformer_variant == case.transformer_variant
        && receipt.fixture == case.fixture
        && receipt.observed_width == case.width
        && receipt.observed_height == case.height
        && receipt.observed_frames == case.frames
        && receipt.observed_fps == case.fps
        && receipt.seed == case.seed
}

fn reference_receipt_matches_bundle(
    receipt: &Ltx25QuantMeasurementReceipt,
    reference_revision: &str,
    reference_inventory_sha256: &str,
    reference_bundle_sha256: &str,
    reference_selected_bundle_sha256: &str,
) -> bool {
    receipt.model_revision == reference_revision
        && receipt.model_inventory_sha256 == reference_inventory_sha256
        && receipt.runtime_bundle_sha256 == reference_bundle_sha256
        && receipt.selected_bundle_sha256 == reference_selected_bundle_sha256
        && receipt.reference_model_revision == receipt.model_revision
        && receipt.reference_model_inventory_sha256 == receipt.model_inventory_sha256
        && receipt.reference_runtime_bundle_sha256 == receipt.runtime_bundle_sha256
        && receipt.reference_selected_bundle_sha256 == receipt.selected_bundle_sha256
}

fn compare_outputs(
    candidate: &CapturedOutput,
    reference: &CapturedOutput,
) -> Result<Ltx25QuantQuality> {
    if candidate.fps != reference.fps
        || candidate.frames.len() != reference.frames.len()
        || candidate.frames.is_empty()
    {
        return Err(invalid("candidate/reference frame count or FPS differs").into());
    }
    let mut candidate_pixels = Vec::new();
    let mut reference_pixels = Vec::new();
    for (candidate, reference) in candidate.frames.iter().zip(&reference.frames) {
        if candidate.width != reference.width
            || candidate.height != reference.height
            || candidate.pixels.len() != reference.pixels.len()
            || candidate.pixels.len() != candidate.width as usize * candidate.height as usize * 3
        {
            return Err(
                invalid("candidate/reference frame geometry differs or is malformed").into(),
            );
        }
        candidate_pixels.extend_from_slice(&candidate.pixels);
        reference_pixels.extend_from_slice(&reference.pixels);
    }
    let mse = candidate_pixels
        .iter()
        .zip(&reference_pixels)
        .map(|(&a, &b)| {
            let delta = f64::from(a) - f64::from(b);
            delta * delta
        })
        .sum::<f64>()
        / candidate_pixels.len() as f64;
    let reference_psnr = if mse == 0.0 {
        120.0
    } else {
        10.0 * (255.0_f64.powi(2) / mse).log10()
    };
    let reference_ssim = global_ssim(&candidate_pixels, &reference_pixels);
    let temporal_boundary_drift = temporal_boundary_drift(&candidate.frames, &reference.frames)?;
    let silent_zero_video_passed = candidate_pixels.iter().any(|&value| value != 0)
        && candidate_pixels.iter().min() != candidate_pixels.iter().max();
    let silent_zero_audio_passed = candidate.audio.as_ref().is_some_and(|audio| {
        !audio.samples.is_empty()
            && audio.samples.iter().all(|sample| sample.is_finite())
            && audio.samples.iter().any(|sample| sample.abs() > 1.0e-8)
    });
    Ok(Ltx25QuantQuality {
        reference_psnr,
        reference_ssim,
        temporal_boundary_drift,
        silent_zero_video_passed,
        silent_zero_audio_passed,
    })
}

fn global_ssim(candidate: &[u8], reference: &[u8]) -> f64 {
    let n = candidate.len() as f64;
    let mean_a = candidate.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let mean_b = reference.iter().map(|&v| f64::from(v)).sum::<f64>() / n;
    let (mut var_a, mut var_b, mut covariance) = (0.0, 0.0, 0.0);
    for (&a, &b) in candidate.iter().zip(reference) {
        let da = f64::from(a) - mean_a;
        let db = f64::from(b) - mean_b;
        var_a += da * da;
        var_b += db * db;
        covariance += da * db;
    }
    let denominator = (n - 1.0).max(1.0);
    var_a /= denominator;
    var_b /= denominator;
    covariance /= denominator;
    let c1 = (0.01_f64 * 255.0).powi(2);
    let c2 = (0.03_f64 * 255.0).powi(2);
    ((2.0 * mean_a * mean_b + c1) * (2.0 * covariance + c2)
        / ((mean_a * mean_a + mean_b * mean_b + c1) * (var_a + var_b + c2)))
        .clamp(0.0, 1.0)
}

fn temporal_boundary_drift(candidate: &[ImageRecord], reference: &[ImageRecord]) -> Result<f64> {
    if candidate.len() < 2 {
        return Ok(0.0);
    }
    let mut sum = 0.0;
    let mut count = 0usize;
    for index in 1..candidate.len() {
        for (((&candidate_now, &candidate_before), &reference_now), &reference_before) in candidate
            [index]
            .pixels
            .iter()
            .zip(&candidate[index - 1].pixels)
            .zip(&reference[index].pixels)
            .zip(&reference[index - 1].pixels)
        {
            let candidate_delta = i16::from(candidate_now) - i16::from(candidate_before);
            let reference_delta = i16::from(reference_now) - i16::from(reference_before);
            sum += f64::from((candidate_delta - reference_delta).unsigned_abs()) / 255.0;
            count += 1;
        }
    }
    if count == 0 {
        return Err(invalid("temporal drift had no samples").into());
    }
    Ok(sum / count as f64)
}

fn artifact(root: &Path, path: &Path) -> Result<EvidenceArtifact> {
    Ok(EvidenceArtifact {
        path: path
            .strip_prefix(root)?
            .to_string_lossy()
            .replace('\\', "/"),
        bytes: path.metadata()?.len(),
        sha256: sha256_file(path)?,
    })
}

fn write_json(path: &Path, value: &impl Serialize) -> Result<()> {
    let mut bytes = serde_json::to_vec_pretty(value)?;
    bytes.push(b'\n');
    let mut file = File::create(path)?;
    file.write_all(&bytes)?;
    file.sync_all()?;
    Ok(())
}

fn write_transcript(path: &Path, events: &[serde_json::Value]) -> Result<()> {
    let mut file = File::create(path)?;
    for event in events {
        serde_json::to_writer(&mut file, event)?;
        file.write_all(b"\n")?;
    }
    file.sync_all()?;
    Ok(())
}

fn sha256_file(path: &Path) -> Result<String> {
    let mut file = File::open(path)?;
    let mut hash = Sha256::new();
    let mut buffer = vec![0_u8; 1024 * 1024];
    loop {
        let read = file.read(&mut buffer)?;
        if read == 0 {
            break;
        }
        hash.update(&buffer[..read]);
    }
    Ok(format!("{:x}", hash.finalize()))
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn require_lower_hex(label: &str, value: &str, length: usize) -> Result<()> {
    if value.len() != length
        || !value
            .bytes()
            .all(|byte| byte.is_ascii_digit() || (b'a'..=b'f').contains(&byte))
    {
        return Err(invalid(format!(
            "{label} must be {length} lowercase hexadecimal characters"
        ))
        .into());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn campaign_manifest() -> TerminalCampaignManifest {
        TerminalCampaignManifest {
            schema_version: CAMPAIGN_SCHEMA.to_owned(),
            cases: TERMINAL_MEASUREMENT_CASES
                .iter()
                .map(|case| TerminalCampaignCase {
                    case_id: case.id.to_owned(),
                    snapshot_root: PathBuf::from(format!("/snapshots/{}", "a".repeat(40))),
                    model_revision: "a".repeat(40),
                    bundle_subdir: PathBuf::from(case.id),
                })
                .collect(),
        }
    }

    fn bf16_receipt() -> Ltx25QuantMeasurementReceipt {
        let case = measurement_case("ltx25-bf16-blackwell-v1").unwrap();
        Ltx25QuantMeasurementReceipt::seal(Ltx25QuantMeasurementDraft {
            case_id: case.id.to_owned(),
            mode: case.mode,
            gpu_generation: case.gpu,
            transformer_variant: case.transformer_variant,
            fixture: case.fixture.to_owned(),
            observed_width: case.width,
            observed_height: case.height,
            observed_frames: case.frames,
            observed_fps: case.fps,
            seed: case.seed,
            inference_revision: "a".repeat(40),
            executable_contract_sha256: env!("LTX25_EXECUTABLE_CONTRACT_SHA256").to_owned(),
            executable_sha256: "b".repeat(64),
            model_revision: "c".repeat(40),
            model_inventory_sha256: "d".repeat(64),
            bundle_subdir: "bundles/distilled/bf16".to_owned(),
            runtime_bundle_sha256: "e".repeat(64),
            selected_bundle_sha256: "7".repeat(64),
            reference_model_revision: "c".repeat(40),
            reference_model_inventory_sha256: "d".repeat(64),
            reference_bundle_subdir: "bundles/distilled/bf16".to_owned(),
            reference_runtime_bundle_sha256: "e".repeat(64),
            reference_selected_bundle_sha256: "7".repeat(64),
            gpu_name: "NVIDIA GeForce RTX 5090".to_owned(),
            compute_capability: "sm_120".to_owned(),
            driver_version: "580.12".to_owned(),
            harness_version: HARNESS_VERSION.to_owned(),
            run_nonce_sha256: "f".repeat(64),
            transcript_sha256: "1".repeat(64),
            evidence_manifest_sha256: "2".repeat(64),
            output_sha256: "3".repeat(64),
            reference_output_sha256: "3".repeat(64),
            reference_receipt_sha256: "4".repeat(64),
            operator_kind: "dense-linear".to_owned(),
            operator_contract_sha256: "5".repeat(64),
            operator_weight_inventory_sha256: "6".repeat(64),
            executed_projection_count: 1,
            declared_projection_count: 0,
            baseline_vram_bytes: 1,
            peak_vram_bytes: 2,
            wall_clock_ms: 1,
            quality: Ltx25QuantQuality {
                reference_psnr: 120.0,
                reference_ssim: 1.0,
                temporal_boundary_drift: 0.0,
                silent_zero_video_passed: true,
                silent_zero_audio_passed: true,
            },
        })
    }

    fn image(values: &[u8]) -> ImageRecord {
        ImageRecord {
            width: 1,
            height: 1,
            pixels: values.to_vec(),
        }
    }

    #[test]
    fn output_comparator_covers_psnr_ssim_temporal_drift_and_both_silent_zero_gates() {
        let reference = CapturedOutput {
            frames: vec![image(&[10, 20, 30]), image(&[20, 30, 40])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.0, 0.25],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        let exact = compare_outputs(&reference, &reference).unwrap();
        assert_eq!(exact.reference_psnr, 120.0);
        assert!((exact.reference_ssim - 1.0).abs() < 1e-12);
        assert_eq!(exact.temporal_boundary_drift, 0.0);
        assert!(exact.silent_zero_video_passed && exact.silent_zero_audio_passed);
        let mut silent = reference.clone();
        silent.audio.as_mut().unwrap().samples.fill(0.0);
        assert!(
            !compare_outputs(&silent, &reference)
                .unwrap()
                .silent_zero_audio_passed
        );
    }

    #[test]
    fn campaign_plan_is_exact_and_runs_both_bf16_references_before_candidates() {
        let manifest = campaign_manifest();
        assert_eq!(validated_campaign_cases(&manifest).unwrap().len(), 9);
        let order = campaign_order().collect::<Vec<_>>();
        assert_eq!(order.len(), 9);
        assert!(order[..2]
            .iter()
            .all(|case| case.mode == Ltx25QuantMode::Bf16));
        assert!(order[2..]
            .iter()
            .all(|case| case.mode != Ltx25QuantMode::Bf16));

        let mut missing = manifest;
        missing.cases.pop();
        assert!(validated_campaign_cases(&missing)
            .unwrap_err()
            .to_string()
            .contains("exact terminal case set"));
    }

    #[test]
    fn promotion_input_accepts_only_the_three_production_advanced_rows() {
        let advanced = TERMINAL_MEASUREMENT_CASES
            .iter()
            .filter(|case| {
                matches!(
                    case.mode,
                    Ltx25QuantMode::Int8ConvRot | Ltx25QuantMode::Nvfp4
                )
            })
            .map(|case| TerminalPromotionCase {
                case_id: case.id.to_owned(),
                public_snapshot_root: PathBuf::from("/public/snapshots/immutable"),
                public_model_revision: "b".repeat(40),
                public_bundle_subdir: PathBuf::from(case.id),
            })
            .collect::<Vec<_>>();
        assert_eq!(advanced.len(), 3);
        let input = TerminalPromotionInput {
            schema_version: PROMOTION_SCHEMA.to_owned(),
            cases: advanced,
        };
        assert_eq!(validated_promotion_cases(&input).unwrap().len(), 3);

        let mut packed = input;
        packed.cases[0].case_id = "ltx25-packed-q8-blackwell-v1".to_owned();
        assert!(validated_promotion_cases(&packed)
            .unwrap_err()
            .to_string()
            .contains("non-promotable"));
    }

    #[test]
    fn promotion_copy_gate_rejects_selected_bytes_or_operator_mutation() {
        let observation = || BundleObservation {
            snapshot_root: PathBuf::from("/snapshot"),
            model_inventory_sha256: "a".repeat(64),
            bundle_subdir: "bundles/distilled/int8".to_owned(),
            runtime_bundle_sha256: "b".repeat(64),
            selected_bundle_sha256: "c".repeat(64),
            operator_contract_sha256: "d".repeat(64),
        };
        let source = observation();
        let mut public = observation();
        public.model_inventory_sha256 = "e".repeat(64);
        assert!(require_identical_selected_copy("case", &source, &public).is_ok());

        public.selected_bundle_sha256 = "f".repeat(64);
        assert!(require_identical_selected_copy("case", &source, &public).is_err());
        public.selected_bundle_sha256 = source.selected_bundle_sha256.clone();
        public.operator_contract_sha256 = "f".repeat(64);
        assert!(require_identical_selected_copy("case", &source, &public).is_err());
    }

    #[test]
    fn promotion_rechecks_every_manifested_campaign_artifact() {
        let root = tempfile::tempdir().unwrap();
        let receipt = bf16_receipt();
        let names = [
            "generated-output.bin",
            "model-inventory.json",
            "reference-evidence-manifest.json",
            "reference-model-inventory.json",
            "reference-output.bin",
            "reference-receipt.json",
            "reference-transcript.jsonl",
            "transcript.jsonl",
        ];
        let mut artifacts = Vec::new();
        for (index, name) in names.into_iter().enumerate() {
            let path = root.path().join(name);
            fs::write(&path, [index as u8]).unwrap();
            artifacts.push(artifact(root.path(), &path).unwrap());
        }
        artifacts.sort_by(|left, right| left.path.cmp(&right.path));
        write_json(
            &root.path().join("evidence-manifest.json"),
            &EvidenceManifest {
                schema_version: EVIDENCE_SCHEMA.to_owned(),
                case_id: receipt.case_id.clone(),
                run_nonce_sha256: receipt.run_nonce_sha256.clone(),
                artifacts,
            },
        )
        .unwrap();
        verify_evidence_manifest(root.path(), &receipt).unwrap();

        fs::write(root.path().join("reference-output.bin"), b"mutated").unwrap();
        assert!(verify_evidence_manifest(root.path(), &receipt)
            .unwrap_err()
            .to_string()
            .contains("manifest length/hash"));
    }

    #[test]
    fn windows_workflow_builds_once_and_dispatches_one_serial_sm120_campaign() {
        let workflow = fs::read_to_string(
            Path::new(env!("CARGO_MANIFEST_DIR"))
                .join("../../../../.github/workflows/ltx25-quant-campaign.yml"),
        )
        .unwrap();
        assert_eq!(workflow.matches("cargo build ").count(), 1);
        assert!(!workflow.contains("cargo run"));
        for required in [
            "CUDA_COMPUTE_CAP: \"120\"",
            "capability -ne '12.0'",
            "--campaign-manifest",
            "--physical-gpu",
            "cancel-in-progress: false",
        ] {
            assert!(workflow.contains(required), "missing {required:?}");
        }
    }

    #[test]
    fn output_artifact_round_trip_is_exact_and_truncation_is_refused() {
        let root = tempfile::tempdir().unwrap();
        let path = root.path().join("output.bin");
        let output = CapturedOutput {
            frames: vec![image(&[1, 2, 3])],
            fps: 24,
            audio: Some(AudioRecord {
                samples: vec![0.5],
                sample_rate: 48_000,
                channels: 1,
            }),
        };
        write_captured_output(&path, &output).unwrap();
        assert_eq!(
            read_captured_output(&path).unwrap().frames[0].pixels,
            vec![1, 2, 3]
        );
        let mut bytes = fs::read(&path).unwrap();
        bytes.pop();
        fs::write(&path, bytes).unwrap();
        assert!(read_captured_output(&path)
            .unwrap_err()
            .to_string()
            .contains("truncated"));
    }

    #[test]
    fn observed_geometry_comes_from_output_and_rejects_malformed_frames() {
        let output = CapturedOutput {
            frames: vec![
                ImageRecord {
                    width: 2,
                    height: 1,
                    pixels: vec![1; 6],
                },
                ImageRecord {
                    width: 2,
                    height: 1,
                    pixels: vec![2; 6],
                },
            ],
            fps: 24,
            audio: None,
        };
        assert_eq!(observed_geometry(&output).unwrap(), (2, 1, 2, 24));

        let mut changed = output.clone();
        changed.frames[1].width = 1;
        assert!(observed_geometry(&changed)
            .unwrap_err()
            .to_string()
            .contains("inconsistent or malformed"));

        let mut truncated = output;
        truncated.frames[0].pixels.pop();
        assert!(observed_geometry(&truncated)
            .unwrap_err()
            .to_string()
            .contains("inconsistent or malformed"));
    }

    #[test]
    fn quant_candidate_accepts_a_distinct_explicit_bf16_snapshot_identity_only() {
        let receipt = bf16_receipt();
        let candidate = measurement_case("ltx25-int8-convrot-blackwell-v1").unwrap();
        let hardware = HardwareIdentity {
            gpu_name: receipt.gpu_name.clone(),
            driver_version: receipt.driver_version.clone(),
            compute_cap: (12, 0),
            generation: Ltx25GpuGeneration::ConsumerBlackwellSm120,
            physical_ordinal: 0,
        };
        assert!(reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &receipt.executable_sha256,
            &receipt.model_revision,
            &receipt.bundle_subdir,
        ));
        assert!(reference_receipt_matches_bundle(
            &receipt,
            &receipt.model_revision,
            &receipt.model_inventory_sha256,
            &receipt.runtime_bundle_sha256,
            &receipt.selected_bundle_sha256,
        ));
        let candidate_inventory = "9".repeat(64);
        assert_ne!(candidate_inventory, receipt.model_inventory_sha256);

        assert!(!reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &"0".repeat(64),
            &receipt.model_revision,
            &receipt.bundle_subdir,
        ));
        assert!(!reference_receipt_matches_campaign(
            &receipt,
            candidate,
            &hardware,
            &receipt.inference_revision,
            &receipt.executable_sha256,
            &"0".repeat(40),
            &receipt.bundle_subdir,
        ));
        let mut wrong_reference = receipt.clone();
        wrong_reference.reference_model_inventory_sha256 = "0".repeat(64);
        assert!(!reference_receipt_matches_bundle(
            &wrong_reference,
            &receipt.model_revision,
            &receipt.model_inventory_sha256,
            &receipt.runtime_bundle_sha256,
            &receipt.selected_bundle_sha256,
        ));
    }

    #[test]
    fn terminal_acknowledgement_is_explicit_and_stable() {
        assert_eq!(
            TERMINAL_ACKNOWLEDGEMENT,
            "I_ACKNOWLEDGE_SC18777_TERMINAL_MEASUREMENT_ONLY"
        );
        let error = run(TerminalMeasurementConfig {
            acknowledgement: "ordinary-generation".to_owned(),
            case_id: "ltx25-bf16-blackwell-v1".to_owned(),
            snapshot: PathBuf::from("unused"),
            bundle_subdir: PathBuf::from("."),
            model_revision: "0".repeat(40),
            output_dir: PathBuf::from("/unused"),
            reference_snapshot: None,
            reference_bundle_subdir: None,
            reference_model_revision: None,
            reference_output: None,
            reference_receipt: None,
        })
        .unwrap_err()
        .to_string();
        assert!(error.contains("terminal-only acknowledgement"), "{error}");
    }

    #[cfg(unix)]
    #[test]
    fn model_inventory_hashes_hf_blob_symlinks_by_logical_snapshot_path() {
        use std::os::unix::fs::symlink;

        let cache = tempfile::tempdir().unwrap();
        let repo = cache.path().join("models--scene--ltx");
        let blobs = repo.join("blobs");
        let revision = "1".repeat(40);
        let root = repo.join("snapshots").join(&revision);
        fs::create_dir_all(root.join("nested")).unwrap();
        fs::create_dir_all(&blobs).unwrap();
        fs::write(blobs.join("blob"), b"exact-model-bytes").unwrap();
        symlink(
            "../../../blobs/blob",
            root.join("nested/transformer.safetensors"),
        )
        .unwrap();
        let inventory = inventory_for_snapshot(&root).unwrap();
        assert_eq!(inventory.entries.len(), 1);
        assert_eq!(inventory.entries[0].path, "nested/transformer.safetensors");
        assert_eq!(
            inventory.entries[0].symlink_target.as_deref(),
            Some("blobs/blob")
        );
        assert_eq!(
            inventory.entries[0].sha256,
            sha256_hex(b"exact-model-bytes")
        );

        fs::write(blobs.join("second-blob"), b"exact-model-bytes").unwrap();
        fs::remove_file(root.join("nested/transformer.safetensors")).unwrap();
        symlink(
            "../../../blobs/second-blob",
            root.join("nested/transformer.safetensors"),
        )
        .unwrap();
        let retargeted = inventory_for_snapshot(&root).unwrap();
        assert_ne!(
            inventory, retargeted,
            "retargeting a model symlink must invalidate the pre-generation inventory even when the followed bytes match"
        );
    }

    #[cfg(unix)]
    #[test]
    fn model_inventory_rejects_a_symlink_escaping_the_hf_repository_blobs() {
        use std::os::unix::fs::symlink;

        let cache = tempfile::tempdir().unwrap();
        let outside = tempfile::tempdir().unwrap();
        let repo = cache.path().join("models--scene--ltx");
        let revision = "2".repeat(40);
        let root = repo.join("snapshots").join(revision);
        fs::create_dir_all(repo.join("blobs")).unwrap();
        fs::create_dir_all(&root).unwrap();
        fs::write(outside.path().join("escaped"), b"same-looking-model").unwrap();
        symlink(
            outside.path().join("escaped"),
            root.join("transformer.safetensors"),
        )
        .unwrap();
        let error = inventory_for_snapshot(&root).unwrap_err().to_string();
        assert!(
            error.contains("outside the repository blob cache"),
            "{error}"
        );
    }

    #[test]
    fn materialized_snapshot_files_do_not_require_a_blobs_directory() {
        let cache = tempfile::tempdir().unwrap();
        let revision = "3".repeat(40);
        let root = cache.path().join("repo/snapshots").join(revision);
        fs::create_dir_all(&root).unwrap();
        fs::write(root.join("transformer.safetensors"), b"materialized").unwrap();
        let inventory = inventory_for_snapshot(&root).unwrap();
        assert_eq!(inventory.entries.len(), 1);
        assert_eq!(inventory.entries[0].symlink_target, None);
    }
}
