//! Gemma 4 unified **decoder** goldens (sc-18761).
//!
//! `tests/gemma4_primitives.rs` pins each primitive Gemma 4 adds. This pins the *assembled block*:
//! a whole tiny `Gemma4Unified` model — four layers alternating `sliding_attention` and
//! `full_attention`, two head dims (4 / 8), two GQA group counts (2 / 4), `attention_k_eq_v` on the
//! full layers, and a sliding window (2) shorter than the prompt (5) — built from
//! `crates/llm/testdata/gemma4/gemma4_decoder_goldens.json` and run end to end.
//!
//! That fixture is **shared with `mlx-llm`** (sc-18760), which asserts the identical numbers. It is
//! generated by a committed, numpy-only, deterministic script transcribed from the public reference
//! (`huggingface/transformers` `gemma4_unified`), so neither backend is the other's oracle and
//! cross-backend drift is caught by construction rather than by comparing two ports to each other.
//!
//! Both entry points are covered: the causal-LM forward (`decode_logits_all` / `decode_logits`) and
//! the all-hidden-states forward (`hidden_states`), plus a cached decode step whose sliding window
//! now spans the cache rather than the prompt.
//!
//! Assertions are on **absolute** error, not cosine similarity — a RoPE schedule with the right
//! shape and the wrong base is cosine-close and numerically wrong. Every golden is paired with a
//! *mutation*: the plausible wrong decoder (no window; one RoPE for the whole stack; a separate
//! value projection) is shown to produce different numbers, so a golden a near-miss also passes is
//! not left standing.

use std::collections::HashMap;

use candle_core::{DType, Device, Tensor};
use serde_json::Value;

use candle_llm::config::ModelConfig;
use candle_llm::models::CausalLm;
use candle_llm::primitives::{input_ids, KvCache, Weights};

const DECODER_GOLDENS: &str = include_str!("../../testdata/gemma4/gemma4_decoder_goldens.json");

fn goldens() -> Value {
    serde_json::from_str(DECODER_GOLDENS).expect("parse gemma4 decoder goldens")
}

fn floats(v: &Value) -> Vec<f32> {
    v.as_array()
        .expect("float array")
        .iter()
        .map(|x| x.as_f64().unwrap() as f32)
        .collect()
}

fn usizes(v: &Value) -> Vec<usize> {
    v.as_array()
        .expect("shape array")
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect()
}

fn ids_of(v: &Value) -> Vec<i32> {
    v.as_array()
        .expect("id array")
        .iter()
        .map(|x| x.as_i64().unwrap() as i32)
        .collect()
}

fn max_abs_err(got: &[f32], want: &[f32]) -> f32 {
    assert_eq!(got.len(), want.len(), "length mismatch");
    got.iter()
        .zip(want)
        .map(|(a, b)| (a - b).abs())
        .fold(0.0f32, f32::max)
}

/// Assert on **absolute** error, with the budget scaled by the golden's own magnitude (the fixture
/// is computed in f64 and the decoder runs in f32 on CPU).
fn assert_abs_close(got: &[f32], want: &[f32], rel: f32, what: &str) {
    let scale = want.iter().map(|x| x.abs()).fold(0.0f32, f32::max).max(1.0);
    let err = max_abs_err(got, want);
    assert!(
        err <= rel * scale,
        "{what}: max|delta| = {err} exceeds {} (rel {rel} of magnitude {scale})",
        rel * scale
    );
}

fn host(t: &Tensor) -> Vec<f32> {
    t.to_dtype(DType::F32)
        .unwrap()
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .unwrap()
}

/// The golden's committed weight map, lifted onto the CPU.
fn weight_map(g: &Value) -> HashMap<String, Tensor> {
    let mut m = HashMap::new();
    for (key, spec) in g["weights"].as_object().expect("weights object") {
        let shape = usizes(&spec["shape"]);
        let data = floats(&spec["data"]);
        assert_eq!(
            data.len(),
            shape.iter().product::<usize>(),
            "{key}: data does not fill {shape:?}"
        );
        m.insert(
            key.clone(),
            Tensor::from_vec(data, shape, &Device::Cpu).unwrap(),
        );
    }
    m
}

/// Build the golden model, optionally with `patch` applied to its `text_config` first.
fn build_model(g: &Value, patch: &[(&str, Value)]) -> Result<CausalLm, candle_llm::Error> {
    let mut cfg_json = g["config"].clone();
    for (key, value) in patch {
        cfg_json["text_config"][*key] = value.clone();
    }
    let cfg = ModelConfig::from_json(&cfg_json).expect("gemma4 decoder fixture config parses");
    CausalLm::from_weights(&Weights::from_map(weight_map(g), Device::Cpu), "", cfg)
}

fn model(g: &Value) -> CausalLm {
    match build_model(g, &[]) {
        Ok(m) => m,
        Err(e) => panic!("the decoder must build a Gemma 4 model: {e}"),
    }
}

/// The message of a build that must fail (`CausalLm` is not `Debug`, so `expect_err` is out).
fn build_error(g: &Value, patch: &[(&str, Value)], why: &str) -> String {
    match build_model(g, patch) {
        Err(e) => e.to_string(),
        Ok(_) => panic!("{why}"),
    }
}

// ---------------------------------------------------------------------------------------------
// the two entry points
// ---------------------------------------------------------------------------------------------

/// The **all-hidden-states** forward — the entry point a text encoder consumes (LTX-2.5 stacks
/// every layer's output into its feature extractor).
///
/// `num_layers + 1` entries in Hugging Face's `output_hidden_states` layout: the scaled input
/// embeddings, each layer's output, and a **final-normed** last entry. The fixture computes the same
/// stack from the reference, so a wrong sandwich order, a wrong norm fold, or a missing final norm
/// all fail here — none of which a logits-only assertion can see.
#[test]
fn gemma4_hidden_state_stack_matches_the_shared_goldens() {
    let g = goldens();
    let m = model(&g);
    let prompt = ids_of(&g["prefill"]["input_ids"]);
    let want_shape = usizes(&g["prefill"]["hidden_states_shape"]);

    let ids = input_ids(&prompt, &Device::Cpu).unwrap();
    let mut cache = m.new_cache();
    let stack = m.hidden_states(&ids, &mut cache, 0).unwrap();

    let want = g["prefill"]["hidden_states"].as_array().unwrap();
    assert_eq!(
        stack.len(),
        want.len(),
        "num_layers + 1 hidden-state entries"
    );
    for (i, (got, expect)) in stack.iter().zip(want).enumerate() {
        assert_eq!(got.dims(), want_shape.as_slice(), "entry {i} shape");
        assert_abs_close(&host(got), &floats(expect), 1e-4, &format!("hidden[{i}]"));
    }
    // A real forward, not a probe: the cache advanced one position per prompt token.
    assert_eq!(cache.offset(), prompt.len() as i32);

    // Every entry must differ from its predecessor — otherwise a stack that pushed one handle
    // `L + 1` times would satisfy every shape check above.
    for i in 1..stack.len() {
        assert!(
            max_abs_err(&host(&stack[i]), &host(&stack[i - 1])) > 1e-4,
            "entry {i} must differ from entry {}",
            i - 1
        );
    }
}

/// The **causal-LM** forward: every position's logits, soft-capped at 30.0 through the tied head.
#[test]
fn gemma4_all_position_logits_match_the_shared_goldens() {
    let g = goldens();
    let m = model(&g);
    let prompt = ids_of(&g["prefill"]["input_ids"]);
    let ids = input_ids(&prompt, &Device::Cpu).unwrap();

    let mut cache = m.new_cache();
    let logits = m.decode_logits_all(&ids, &mut cache, 0).unwrap();
    assert_eq!(
        logits.dims(),
        usizes(&g["prefill"]["logits_shape"]).as_slice()
    );
    assert_abs_close(
        &host(&logits),
        &floats(&g["prefill"]["logits"]),
        1e-4,
        "prefill logits",
    );

    // The last-position forward must agree with the all-position one's last row.
    let mut cache2 = m.new_cache();
    let last = m.decode_logits(&ids, &mut cache2, 0).unwrap();
    assert_abs_close(
        &host(&last),
        &floats(&g["prefill"]["last_logits"]),
        1e-4,
        "prefill last logits",
    );
}

/// A **cached decode step**: one token at `offset = len(prompt)`, whose sliding window now spans the
/// cache rather than the prompt. This is the case a prefill-only golden cannot see — the
/// bottom-right alignment of the window over cached keys.
#[test]
fn gemma4_cached_decode_step_matches_the_shared_goldens() {
    let g = goldens();
    let m = model(&g);
    let prompt = ids_of(&g["prefill"]["input_ids"]);
    let step = ids_of(&g["decode"]["input_ids"]);
    let offset = g["decode"]["offset"].as_i64().unwrap() as i32;
    assert_eq!(offset, prompt.len() as i32);

    let mut cache = m.new_cache();
    m.decode_logits(&input_ids(&prompt, &Device::Cpu).unwrap(), &mut cache, 0)
        .unwrap();
    let logits = m
        .decode_logits(&input_ids(&step, &Device::Cpu).unwrap(), &mut cache, offset)
        .unwrap();
    assert_abs_close(
        &host(&logits),
        &floats(&g["decode"]["last_logits"]),
        1e-4,
        "decode-step logits",
    );
    assert_eq!(cache.offset(), offset + 1);
}

// ---------------------------------------------------------------------------------------------
// mutations: the plausible wrong decoders
// ---------------------------------------------------------------------------------------------

/// **The window must bite.** Widening `sliding_window` past the prompt turns every layer causal;
/// the logits must move. A decoder that built the mask but never applied it passes the goldens on a
/// short prompt and silently degrades on a long one — this is the assertion that catches it.
#[test]
fn gemma4_widening_the_sliding_window_changes_the_output() {
    let g = goldens();
    let prompt = ids_of(&g["prefill"]["input_ids"]);
    let ids = input_ids(&prompt, &Device::Cpu).unwrap();

    let golden = floats(&g["prefill"]["logits"]);
    let wide = build_model(&g, &[("sliding_window", Value::from(4096))]).unwrap();
    let mut cache = wide.new_cache();
    let got = host(&wide.decode_logits_all(&ids, &mut cache, 0).unwrap());

    assert!(
        max_abs_err(&got, &golden) > 1e-3,
        "a window wider than the prompt must not reproduce the windowed goldens"
    );
}

/// **`attention_k_eq_v` must drive the weight requirement, not just the arithmetic.** The fixture's
/// checkpoint has no `v_proj` on its `full_attention` layers at all; turning the flag off must make
/// the load *fail* for want of one. A decoder that "supported" sharing by running the key weight
/// through two projections would load either way, at twice the matmul and twice the quantized
/// footprint — which is the whole point of the flag.
#[test]
fn gemma4_k_eq_v_layers_have_no_value_projection_in_the_checkpoint() {
    let g = goldens();
    let m = build_error(
        &g,
        &[("attention_k_eq_v", Value::from(false))],
        "without k_eq_v the full layers need a v_proj the checkpoint does not have",
    );
    assert!(m.contains("v_proj"), "{m}");
}

/// **The two layer types must use two RoPE schedules.** Forcing the `full_attention` entry onto the
/// sliding layers' `default` schedule (same theta, no partial factor) must move the logits — a
/// decoder that built one RoPE for the whole stack would be unmoved.
#[test]
fn gemma4_full_layers_use_the_proportional_rope_not_the_sliding_one() {
    let g = goldens();
    let prompt = ids_of(&g["prefill"]["input_ids"]);
    let ids = input_ids(&prompt, &Device::Cpu).unwrap();
    let golden = floats(&g["prefill"]["logits"]);

    let one_schedule = build_model(
        &g,
        &[(
            "rope_parameters",
            serde_json::json!({
                "sliding_attention": { "rope_type": "default", "rope_theta": 10000.0 },
                "full_attention": { "rope_type": "default", "rope_theta": 10000.0 },
            }),
        )],
    )
    .unwrap();
    let mut cache = one_schedule.new_cache();
    let got = host(&one_schedule.decode_logits_all(&ids, &mut cache, 0).unwrap());

    assert!(
        max_abs_err(&got, &golden) > 1e-3,
        "running the sliding schedule on the full layers must not reproduce the goldens"
    );
}

// ---------------------------------------------------------------------------------------------
// refusals: configs this decoder does not implement, and paths it cannot serve
// ---------------------------------------------------------------------------------------------

/// `num_kv_shared_layers` / `use_double_wide_mlp` describe a *different* stack (a KV-sharing tail).
/// Both are `0` / `false` in every shipped Gemma 4 config, so refusing them turns nothing real away
/// — but silently ignoring either would produce plausible, wrong numbers instead of an error.
#[test]
fn gemma4_kv_sharing_config_knobs_are_refused_rather_than_ignored() {
    let g = goldens();
    let shared = build_error(
        &g,
        &[("num_kv_shared_layers", Value::from(2))],
        "a KV-sharing tail is a different stack",
    );
    assert!(shared.contains("num_kv_shared_layers"), "{shared}");

    let wide = build_error(
        &g,
        &[("use_double_wide_mlp", Value::from(true))],
        "a double-wide tail MLP is a different stack",
    );
    assert!(wide.contains("use_double_wide_mlp"), "{wide}");
}

// ---------------------------------------------------------------------------------------------
// real weights
// ---------------------------------------------------------------------------------------------

/// The **real-weight** encoder forward, on the CUDA lane (`#[ignore]`; point
/// `CANDLE_LLM_GEMMA4_MODEL` at a Gemma 4 unified snapshot and run with `--features cuda`).
///
/// The deterministic CPU goldens above carry the numeric pinning — this asserts the thing only real
/// weights can: that a 48-layer stack whose per-layer table resolves to 40 sliding + 8 full actually
/// *builds* from a shipped checkpoint (the full layers' missing `v_proj`, the two `o_proj` widths,
/// the 256/512 q/k norms) and produces a finite, soft-capped, correctly-shaped hidden-state stack
/// and logit row. A per-layer table wired wrong fails on a weight lookup here rather than anywhere a
/// synthetic fixture can reach.
#[test]
#[ignore = "needs a Gemma 4 unified snapshot via CANDLE_LLM_GEMMA4_MODEL"]
fn gemma4_real_weight_forward_produces_a_finite_hidden_state_stack() {
    let Some(dir) = std::env::var("CANDLE_LLM_GEMMA4_MODEL")
        .ok()
        .filter(|v| !v.is_empty())
    else {
        eprintln!("skip: set CANDLE_LLM_GEMMA4_MODEL");
        return;
    };
    let device = candle_llm::device::select_device().expect("select the compile-time device");
    let cfg = ModelConfig::from_dir(&dir).expect("parse the snapshot's config.json");
    assert!(cfg.is_gemma4(), "not a Gemma 4 snapshot");
    let table = cfg.gemma4.as_ref().expect("gemma 4 layer table");
    let sliding = table
        .layer_types
        .iter()
        .filter(|t| **t == candle_llm::config::LayerAttentionType::Sliding)
        .count();
    assert_eq!(
        (sliding, table.layer_types.len() - sliding),
        (40, 8),
        "the shipped 48-layer schedule is 40 sliding / 8 full"
    );

    let w = Weights::from_dir(&dir, &device).expect("load weights");
    let m = CausalLm::from_weights(&w, "", cfg.clone()).expect("build the Gemma 4 decoder");

    let prompt: Vec<i32> = vec![2, 1596, 3384, 611, 1002, 3055];
    let ids = input_ids(&prompt, m.device()).unwrap();
    let mut cache = m.new_cache();
    let stack = m.hidden_states(&ids, &mut cache, 0).expect("hidden states");
    assert_eq!(stack.len(), cfg.num_layers + 1);
    for (i, h) in stack.iter().enumerate() {
        assert_eq!(
            h.dims(),
            &[1, prompt.len(), cfg.hidden_size as usize],
            "entry {i} shape"
        );
        assert!(host(h).iter().all(|x| x.is_finite()), "entry {i} finite");
    }

    let mut cache2 = m.new_cache();
    let logits = m.decode_logits(&ids, &mut cache2, 0).expect("logits");
    assert_eq!(logits.dims(), &[1, cfg.vocab_size as usize]);
    let row = host(&logits);
    assert!(row.iter().all(|x| x.is_finite()), "logits must be finite");
    // `final_logit_softcapping: 30.0` bounds every logit; an uncapped head blows past it.
    let cap = cfg
        .final_logit_softcap
        .expect("gemma 4 caps its final logits");
    assert!(
        row.iter().all(|x| x.abs() <= cap * 1.001),
        "soft-capped logits must stay within +/-{cap}"
    );
}

/// A **paged** cache is sized once from layer 0's head shape, so an ordinary
/// `decode_logits`-on-a-paged-cache is equally unserviceable for Gemma 4 — and it is reachable
/// through `new_paged_cache` + `generate_with_cache`, not just the Throughput path. It must say what
/// is wrong at the first disagreeing layer rather than surfacing a raw tensor-shape mismatch.
#[test]
fn gemma4_paged_cache_names_the_per_layer_head_shape_it_cannot_hold() {
    let g = goldens();
    let m = model(&g);
    let ids = input_ids(&ids_of(&g["prefill"]["input_ids"]), &Device::Cpu).unwrap();
    let mut cache = m.new_paged_cache(8);
    let err = match m.decode_logits(&ids, &mut cache, 0) {
        Err(e) => e.to_string(),
        Ok(_) => panic!("one pooled head shape cannot serve two layer types"),
    };
    assert!(err.contains("head shape"), "{err}");
    assert!(err.contains("Gemma 4"), "{err}");
    // The contiguous cache, which holds each layer's own shape, does serve it.
    let mut contiguous = m.new_cache();
    m.decode_logits(&ids, &mut contiguous, 0)
        .expect("the contiguous cache holds per-layer shapes");
}

/// The continuous-batching `Throughput` path sizes one shared block pool from a single
/// `(n_kv_heads, head_dim)`; Gemma 4's layer types disagree on both, so it is refused by name (as
/// MLA is) rather than quietly attending the wrong shape. The bit-exact `Exact` mode serves it.
#[test]
fn gemma4_refuses_the_paged_throughput_path_by_name() {
    let g = goldens();
    let m = model(&g);
    let ids = input_ids(&[3], &Device::Cpu).unwrap();
    let mut cache = m.new_paged_cache(8);
    let mut caches = vec![&mut cache];
    let err = m
        .decode_logits_per_seq(&ids, &mut caches, &[0])
        .expect_err("the single-shape paged pool cannot hold a Gemma 4 stack");
    let text = err.to_string();
    assert!(text.contains("Gemma 4"), "{text}");
    assert!(text.contains("Exact"), "{text}");
}
