//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "a14b_vace_te_quant_measurement.rs"]
mod a14b_vace_te_quant_measurement;

#[path = "approximation_reachability.rs"]
mod approximation_reachability;

#[path = "batched_forward.rs"]
mod batched_forward;

#[path = "bernini_forward_packed.rs"]
mod bernini_forward_packed;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "compile_parity.rs"]
mod compile_parity;

#[path = "convert_5b_parity.rs"]
mod convert_5b_parity;

#[path = "convert_bernini_renderer.rs"]
mod convert_bernini_renderer;

#[path = "convert_i2v_14b_parity.rs"]
mod convert_i2v_14b_parity;

#[path = "convert_vae_parity.rs"]
mod convert_vae_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "expert_swap_footprint.rs"]
mod expert_swap_footprint;

#[path = "i2v_parity.rs"]
mod i2v_parity;

#[path = "i2v_real_parity.rs"]
mod i2v_real_parity;

#[path = "lora_real_parity.rs"]
mod lora_real_parity;

#[path = "perf.rs"]
mod perf;

#[path = "quant_e2e_parity.rs"]
mod quant_e2e_parity;

#[path = "quant_parity.rs"]
mod quant_parity;

#[path = "registration.rs"]
mod registration;

#[path = "s0_parity.rs"]
mod s0_parity;

#[path = "s1_parity.rs"]
mod s1_parity;

#[path = "s2_parity.rs"]
mod s2_parity;

#[path = "s3_parity.rs"]
mod s3_parity;

#[path = "s4_parity.rs"]
mod s4_parity;

#[path = "s5_parity.rs"]
mod s5_parity;

#[path = "s6_generate_smoke.rs"]
mod s6_generate_smoke;

#[path = "s6_real_parity.rs"]
mod s6_real_parity;

#[path = "te_quant_parity.rs"]
mod te_quant_parity;

#[path = "ti2v_5b_offload_footprint.rs"]
mod ti2v_5b_offload_footprint;

#[path = "ti2v_parity.rs"]
mod ti2v_parity;

#[path = "ti2v_real_parity.rs"]
mod ti2v_real_parity;

#[path = "tiling_parity.rs"]
mod tiling_parity;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "trim.rs"]
mod trim;

#[path = "vae16_decode_sweep.rs"]
mod vae16_decode_sweep;

#[path = "vae16_write_bound_real.rs"]
mod vae16_write_bound_real;

#[path = "vae22_parity.rs"]
mod vae22_parity;

#[path = "wan_overlap_ab.rs"]
mod wan_overlap_ab;

#[path = "wanvace_cond_parity.rs"]
mod wanvace_cond_parity;

#[path = "wanvace_e2e.rs"]
mod wanvace_e2e;

#[path = "wanvace_fun_e2e.rs"]
mod wanvace_fun_e2e;

#[path = "wanvace_fun_expert_swap_footprint.rs"]
mod wanvace_fun_expert_swap_footprint;

#[path = "wanvace_lora_real_parity.rs"]
mod wanvace_lora_real_parity;

#[path = "wanvace_real_parity.rs"]
mod wanvace_real_parity;

#[path = "wanvace_transformer_parity.rs"]
mod wanvace_transformer_parity;

#[path = "wedge_sweep.rs"]
mod wedge_sweep;
