//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "adapter_real_weights.rs"]
mod adapter_real_weights;

#[path = "adapter_routing.rs"]
mod adapter_routing;

#[path = "bf16_matmul_sweep.rs"]
mod bf16_matmul_sweep;

#[path = "block_residency_real_weights.rs"]
mod block_residency_real_weights;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "control_prequantize_real_weights.rs"]
mod control_prequantize_real_weights;

#[path = "control_real_weights.rs"]
mod control_real_weights;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dump_runb_latents.rs"]
mod dump_runb_latents;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "edit_real_weights.rs"]
mod edit_real_weights;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "fun_control_parity.rs"]
mod fun_control_parity;

#[path = "img2img_real_weights.rs"]
mod img2img_real_weights;

#[path = "lightning_parity.rs"]
mod lightning_parity;

#[path = "lightning_render_real_weights.rs"]
mod lightning_render_real_weights;

#[path = "perf.rs"]
mod perf;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "production_capability_reach.rs"]
mod production_capability_reach;

#[path = "q8_smoke.rs"]
mod q8_smoke;

#[path = "qwen_image_processor.rs"]
mod qwen_image_processor;

#[path = "registration.rs"]
mod registration;

#[path = "sdpa_nax_repro.rs"]
mod sdpa_nax_repro;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "text_encoder_real_weights.rs"]
mod text_encoder_real_weights;

#[path = "transformer_real_weights.rs"]
mod transformer_real_weights;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;

#[path = "vae_real_weights.rs"]
mod vae_real_weights;

#[path = "vae_tiling_normalization_proof.rs"]
mod vae_tiling_normalization_proof;

#[path = "vae_tiling_real_weights.rs"]
mod vae_tiling_real_weights;

#[path = "vision_real_weights.rs"]
mod vision_real_weights;
