//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "adaln_evict_memory.rs"]
mod adaln_evict_memory;

#[path = "audio_vae_encode_parity.rs"]
mod audio_vae_encode_parity;

#[path = "audio_vae_parity.rs"]
mod audio_vae_parity;

#[path = "cross_backend.rs"]
mod cross_backend;

#[path = "dit_io.rs"]
mod dit_io;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "joint_denoise.rs"]
mod joint_denoise;

#[path = "quant_policy.rs"]
mod quant_policy;

#[path = "real_weights.rs"]
mod real_weights;

#[path = "ref2va_checkpoint.rs"]
mod ref2va_checkpoint;

#[path = "ref2va_conditioning.rs"]
mod ref2va_conditioning;

#[path = "ref2va_cross_backend.rs"]
mod ref2va_cross_backend;

#[path = "turbo_lora.rs"]
mod turbo_lora;

#[path = "video_vae_encode_parity.rs"]
mod video_vae_encode_parity;

#[path = "video_vae_parity.rs"]
mod video_vae_parity;

#[path = "vram_probe.rs"]
mod vram_probe;
