//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "adapter_surface.rs"]
mod adapter_surface;

#[path = "apply_real_weights.rs"]
mod apply_real_weights;

#[path = "block_residency_real_weights.rs"]
mod block_residency_real_weights;

#[path = "conformance.rs"]
mod conformance;

#[path = "control_branch_tier_real_weights.rs"]
mod control_branch_tier_real_weights;

#[path = "control_decode_tiling_real_weights.rs"]
mod control_decode_tiling_real_weights;

#[path = "control_full_ladder_real_weights.rs"]
mod control_full_ladder_real_weights;

#[path = "control_memory_calibration_real_weights.rs"]
mod control_memory_calibration_real_weights;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "dit_real_weights.rs"]
mod dit_real_weights;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "img2img_spike_real_weights.rs"]
mod img2img_spike_real_weights;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "pid_img2img_early_stop_real_weights.rs"]
mod pid_img2img_early_stop_real_weights;

#[path = "pid_peraxis_verify.rs"]
mod pid_peraxis_verify;

#[path = "pid_tall_green_cast.rs"]
mod pid_tall_green_cast;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "projector_bypass_real_weights.rs"]
mod projector_bypass_real_weights;

#[path = "raw_img2img_real_weights.rs"]
mod raw_img2img_real_weights;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "tap_reweight_control_real_weights.rs"]
mod tap_reweight_control_real_weights;

#[path = "tap_reweight_edit_real_weights.rs"]
mod tap_reweight_edit_real_weights;

#[path = "tap_reweight_real_weights.rs"]
mod tap_reweight_real_weights;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "te_real_weights.rs"]
mod te_real_weights;

#[path = "trainer_real_weights.rs"]
mod trainer_real_weights;

#[path = "turnkey.rs"]
mod turnkey;

#[path = "vae_real_weights.rs"]
mod vae_real_weights;

#[path = "weights_free_validate_request.rs"]
mod weights_free_validate_request;
