//! Anima candle-port parity goldens (sc-10525, epic 10512) — the **CPU / CI-runnable** stages. They
//! read the committed golden JSON (regenerated by the MLX lane's `gen_anima_parity_goldens.py`,
//! diffusers 0.39.0) — **no Python at test time** — and need **no** licensed weights, so they run in
//! the plain `cargo test` (CPU) lane and prove framework-independent correctness against the SAME
//! goldens the MLX port asserts.
//!
//! Covered here:
//!   * **Stage 1** — Qwen2 + T5 tokenizers → exact token ids (integer-exact; must MATCH the MLX lane).
//!   * **Stage 5** — `linspace(1, 1/N, N)` sigma schedule + static `shift=3.0` → sigmas (exact CPU math).
//!   * **Synthetic DiT forward** — a small Cosmos DiT (non-square 4×6 latent) with fixed-seed random
//!     weights on CPU, pinned to the committed cross-framework golden — the weights-free CI numeric
//!     protection for the transformer forward (the real-weights DiT stages are `#[ignore]`d).
//!
//! The real-weights stages (2 Qwen3, 3 conditioner, 4 DiT) live in `parity_real_weights.rs`,
//! `#[ignore]`d + weights-gated. RoPE traps + the 17-channel patch input are unit tests in the crate.

use std::collections::HashMap;

use serde_json::Value;

use candle_gen::candle_core::{DType, Device, Tensor};
use candle_gen::candle_nn::VarBuilder;
use candle_gen_anima::config::DitConfig;
use candle_gen_anima::pipeline::anima_sigmas;
use candle_gen_anima::tokenizer::AnimaTokenizers;
use candle_gen_anima::transformer::CosmosDiT;

fn load_golden(name: &str) -> Value {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn as_i32_vec(v: &Value) -> Vec<i32> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_i64().expect("int") as i32)
        .collect()
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_f64().expect("float"))
        .collect()
}

// -------------------------------------------------------------------------------------------------
// Stage 1 — tokenizers → exact token ids (integer-exact; CPU/scalar; identical to the MLX lane).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage1_tokenizers_match_golden_ids() {
    let g = load_golden("tokenizer_golden.json");
    let cases = g["cases"].as_array().expect("cases array");
    assert_eq!(cases.len(), 6, "expected 6 fixture-prompt cases");

    let tk = AnimaTokenizers::load().expect("load vendored tokenizers");
    for case in cases {
        let prompt = case["prompt"].as_str().expect("prompt");
        let want_qwen = as_i32_vec(&case["qwen_ids"]);
        let want_qwen_mask = as_i32_vec(&case["qwen_mask"]);
        let want_t5 = as_i32_vec(&case["t5_ids"]);

        let (got_qwen, got_qmask) = tk.encode_qwen(prompt).expect("encode_qwen");
        let got_t5 = tk.encode_t5(prompt).expect("encode_t5");

        assert_eq!(
            got_qwen, want_qwen,
            "Qwen ids mismatch for prompt {prompt:?}"
        );
        assert_eq!(
            got_qmask, want_qwen_mask,
            "Qwen mask mismatch for prompt {prompt:?}"
        );
        assert_eq!(got_t5, want_t5, "T5 ids mismatch for prompt {prompt:?}");
    }

    // The empty prompt is the load-bearing edge (reference: Qwen [[0]]/mask[[0]], T5 [[1]] EOS).
    let empty = cases
        .iter()
        .find(|c| c["prompt"].as_str() == Some(""))
        .expect("empty-prompt case present");
    assert_eq!(as_i32_vec(&empty["qwen_ids"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["qwen_mask"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["t5_ids"]), vec![1]);
}

// -------------------------------------------------------------------------------------------------
// Stage 5 — the sigma schedule (exact CPU arithmetic; must match the diffusers reference exactly).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage5_sigma_schedule_matches_golden() {
    let g = load_golden("sigma_schedule_golden.json");
    let schedules = g["schedules"].as_object().expect("schedules object");
    assert!(!schedules.is_empty(), "no schedules in golden");

    for (steps_str, sched) in schedules {
        let steps: usize = steps_str.parse().expect("steps key is an int");
        let want = as_f64_vec(&sched["sigmas"]);
        let got = anima_sigmas(steps);
        assert_eq!(
            got.len(),
            want.len(),
            "sigma length mismatch for N={steps} (got {}, want {})",
            got.len(),
            want.len()
        );
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert!(
                (*g as f64 - *w).abs() < 1e-5,
                "sigma[{i}] mismatch for N={steps}: got {g}, want {w}"
            );
        }
    }
}

// =================================================================================================
// CI DiT-forward golden — SYNTHETIC deterministic-random weights (sc-10524 review parity, candle lane).
//
// The real-weights DiT stages (2/3/4) are `#[ignore]`d + snapshot-gated, so a numeric regression in the
// candle transformer forward would ship GREEN — CI had ZERO weights-free numeric protection for it. This
// runs a SMALL Cosmos DiT (2 layers, hidden 12, NON-SQUARE 4×6 latent → post-patch 2×3) with fixed-seed
// deterministic-LCG weights — NO licensed weights, NO snapshot — on candle's CPU backend, and pins the
// committed `dit_synthetic_golden.json`. It catches structural regressions with no weights: the 17-vs-16
// padding-mask concat, adaLN modulation wiring, the h/w RoPE axis (grid is non-square, so a transposition
// changes the output), and any shape drift.
//
// The synthetic WEIGHTS are bit-identical to the MLX lane's generator (same LCG, same FNV-1a-of-key seed
// over the `net.`-prefixed key names, same `norm.weight → 1+0.1·v / else 0.3·v` init), so the golden is a
// genuine CROSS-FRAMEWORK reference (MLX Metal fp32 blessed it; candle CPU fp32 reproduces it). We assert
// only the FINAL velocity: candle's `CosmosDiT` exposes `forward` (not the MLX lane's `forward_hidden`),
// so the raw block-0 hidden is not accessible without widening the port surface — and the final velocity
// is the structurally-decisive gate anyway (the MLX note measured drop-concat 258×, adaLN-swap 63×,
// RoPE-h/w-swap 13× over this same bound; block0 was only a corroborating backstop).
//
// The gate is DISTRIBUTION / relative-L2 (NOT per-element): cross-device/-framework fp32 matmul reorders
// its reductions, so a single small-magnitude element can differ a few e-3 *relative* — a per-element
// atol/rtol would be red on that noise. rel-L2 `‖got−want‖₂/‖want‖₂` is norm-weighted (not dominated by
// one small element) yet a structural regression still moves it by orders of magnitude.
// =================================================================================================

// --- Cross-backend fixture geometry (sc-19496) ---------------------------------------------------
//
// Every golden JSON under `tests/fixtures/` here is byte-identical to the one ``mlx-gen-anima`` commits
// under the same name. For the synthetic DiT golden that identity is load-bearing in a way the
// real-weights goldens' are not: the golden carries no geometry of its own beyond `shape`/`count`,
// so BOTH lanes must construct the same tiny `DitConfig`, the same deterministic-LCG weights, and
// the same inputs, or they are comparing two different models against one summary. Nothing could
// see that: the two crates cannot import each other, because `mlx-gen-*` builds on macOS only.
//
// The numbers the two lanes must agree on are declared here as `SHARED_FIXTURE_*` constants and the
// generator below builds from them. `check_cross_backend_geometry` in `scripts/check-workspace.py`
// compares every `SHARED_FIXTURE_*` declaration under this crate's `tests/` against the MLX crate's,
// by name set and by value — so the comment claiming the synthetic weights are "bit-identical to
// the MLX lane's generator" now describes something enforced.

/// Synthetic-DiT latent channels — 17 after the padding-mask concat (the 17-vs-16 regression surface).
pub const SHARED_FIXTURE_SYNTH_IN_CHANNELS: usize = 16;
/// Synthetic-DiT output channels.
pub const SHARED_FIXTURE_SYNTH_OUT_CHANNELS: usize = 16;
/// Synthetic-DiT attention heads.
pub const SHARED_FIXTURE_SYNTH_NUM_ATTENTION_HEADS: usize = 2;
/// Synthetic-DiT per-head width — hidden = 12; head_dim 6 splits cleanly for RoPE (dim_t/h/w = 2/2/2).
pub const SHARED_FIXTURE_SYNTH_ATTENTION_HEAD_DIM: usize = 6;
/// Synthetic-DiT depth.
pub const SHARED_FIXTURE_SYNTH_NUM_LAYERS: usize = 2;
/// Synthetic-DiT feed-forward expansion.
pub const SHARED_FIXTURE_SYNTH_MLP_RATIO: f32 = 4.0;
/// Synthetic-DiT cross-attention context (encoder) width.
pub const SHARED_FIXTURE_SYNTH_TEXT_EMBED_DIM: usize = 8;
/// Synthetic-DiT adaLN-LoRA rank.
pub const SHARED_FIXTURE_SYNTH_ADALN_LORA_DIM: usize = 8;
/// Synthetic-DiT post-patch max size — the production `(128, 120, 120)`, so the RoPE tables are real.
pub const SHARED_FIXTURE_SYNTH_MAX_SIZE: (usize, usize, usize) = (128, 120, 120);
/// Synthetic-DiT patch — the production `(1, 2, 2)`.
pub const SHARED_FIXTURE_SYNTH_PATCH_SIZE: (usize, usize, usize) = (1, 2, 2);
/// Synthetic-DiT NTK RoPE scale — the production `(1.0, 4.0, 4.0)`.
pub const SHARED_FIXTURE_SYNTH_ROPE_SCALE: (f32, f32, f32) = (1.0, 4.0, 4.0);
/// Synthetic-DiT padding-mask concat — the 17-channel patch input the trap test pins.
pub const SHARED_FIXTURE_SYNTH_CONCAT_PADDING_MASK: bool = true;

/// The NON-SQUARE synthetic latent `[1, 16, 1, 4, 6]` (post-patch grid 2x3, so an h/w RoPE swap moves
/// the output).
pub const SHARED_FIXTURE_SYNTH_LATENT_SHAPE: [usize; 5] = [1, 16, 1, 4, 6];
/// The LCG seed the synthetic latent is filled from.
pub const SHARED_FIXTURE_SYNTH_LATENT_SEED: u64 = 1;
/// The synthetic encoder context `[1, 5, 8]`.
pub const SHARED_FIXTURE_SYNTH_ENCODER_SHAPE: [usize; 3] = [1, 5, 8];
/// The LCG seed the synthetic encoder context is filled from.
pub const SHARED_FIXTURE_SYNTH_ENCODER_SEED: u64 = 2;
/// The noise level the synthetic forward is evaluated at.
pub const SHARED_FIXTURE_SYNTH_SIGMA: f32 = 0.7;

/// FNV-1a offset basis — the per-tensor seed is FNV-1a of the FULL `net.`-prefixed key, so the two
/// lanes' weight bytes only agree if this, the prime, and the key names all agree.
pub const SHARED_FIXTURE_SYNTH_FNV_OFFSET_BASIS: u64 = 0xcbf2_9ce4_8422_2325;
/// FNV-1a 64-bit prime.
pub const SHARED_FIXTURE_SYNTH_FNV_PRIME: u64 = 0x0000_0100_0000_01b3;
/// LCG multiplier (the `lcg_fill` recurrence the real-weights tests also use).
pub const SHARED_FIXTURE_SYNTH_LCG_MULTIPLIER: u64 = 1103515245;
/// LCG increment.
pub const SHARED_FIXTURE_SYNTH_LCG_INCREMENT: u64 = 12345;
/// LCG state mask — 31 bits.
pub const SHARED_FIXTURE_SYNTH_LCG_MASK: u64 = 0x7fff_ffff;
/// LCG divisor mapping the 31-bit state onto `[-1, 1)`.
pub const SHARED_FIXTURE_SYNTH_LCG_DIVISOR: f64 = 2147483647.0;
/// Norm-weight init: `1 + NORM_INIT_SCALE * lcg`, so scales sit near 1.0.
pub const SHARED_FIXTURE_SYNTH_NORM_INIT_SCALE: f32 = 0.1;
/// Linear-weight init: `LINEAR_INIT_SCALE * lcg` — large enough that adaLN scale/shift/gate are O(1),
/// small enough that the LayerNorm-gated two-layer forward stays finite.
pub const SHARED_FIXTURE_SYNTH_LINEAR_INIT_SCALE: f32 = 0.3;

/// A tiny Cosmos DiT config — SAME structure as [`DitConfig::anima`] (17-ch concat, 3-axis NTK RoPE,
/// adaLN-LoRA, patch `(1,2,2)`) but small dims. Field-for-field identical to the MLX generator's config.
fn synth_cfg() -> DitConfig {
    DitConfig {
        in_channels: SHARED_FIXTURE_SYNTH_IN_CHANNELS,
        out_channels: SHARED_FIXTURE_SYNTH_OUT_CHANNELS,
        num_attention_heads: SHARED_FIXTURE_SYNTH_NUM_ATTENTION_HEADS,
        attention_head_dim: SHARED_FIXTURE_SYNTH_ATTENTION_HEAD_DIM,
        num_layers: SHARED_FIXTURE_SYNTH_NUM_LAYERS,
        mlp_ratio: SHARED_FIXTURE_SYNTH_MLP_RATIO,
        text_embed_dim: SHARED_FIXTURE_SYNTH_TEXT_EMBED_DIM,
        adaln_lora_dim: SHARED_FIXTURE_SYNTH_ADALN_LORA_DIM,
        max_size: SHARED_FIXTURE_SYNTH_MAX_SIZE,
        patch_size: SHARED_FIXTURE_SYNTH_PATCH_SIZE,
        rope_scale: SHARED_FIXTURE_SYNTH_ROPE_SCALE,
        concat_padding_mask: SHARED_FIXTURE_SYNTH_CONCAT_PADDING_MASK,
    }
}

/// FNV-1a of the key → a stable, order-independent, portable per-tensor seed (matches the MLX generator).
fn key_seed(key: &str) -> u64 {
    let mut h = SHARED_FIXTURE_SYNTH_FNV_OFFSET_BASIS;
    for b in key.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(SHARED_FIXTURE_SYNTH_FNV_PRIME);
    }
    h
}

/// Deterministic LCG in `[-1, 1)` — bit-identical to the real-weights tests' `lcg_fill` and the MLX
/// generator, so weights reproduce bit-for-bit across machines and frameworks.
fn synth_lcg(n: usize, seed: u64) -> Vec<f32> {
    let mut s = seed & SHARED_FIXTURE_SYNTH_LCG_MASK;
    (0..n)
        .map(|_| {
            s = (s
                .wrapping_mul(SHARED_FIXTURE_SYNTH_LCG_MULTIPLIER)
                .wrapping_add(SHARED_FIXTURE_SYNTH_LCG_INCREMENT))
                & SHARED_FIXTURE_SYNTH_LCG_MASK;
            (s as f64 / SHARED_FIXTURE_SYNTH_LCG_DIVISOR * 2.0 - 1.0) as f32
        })
        .collect()
}

/// Insert a synthetic tensor for `key` (the FULL `net.`-prefixed name, so the seed matches MLX). Norm
/// weights init near 1.0; linear weights at `0.3·lcg` (adaLN scale/shift/gate stay O(1) so a modulation
/// regression moves the output, yet the two-layer LayerNorm-gated forward stays finite).
fn synth_tensor(map: &mut HashMap<String, Tensor>, key: &str, shape: &[usize]) {
    let n: usize = shape.iter().product();
    let raw = synth_lcg(n, key_seed(key));
    let data: Vec<f32> = if key.ends_with("norm.weight") {
        raw.iter()
            .map(|&v| 1.0 + SHARED_FIXTURE_SYNTH_NORM_INIT_SCALE * v)
            .collect()
    } else {
        raw.iter()
            .map(|&v| SHARED_FIXTURE_SYNTH_LINEAR_INIT_SCALE * v)
            .collect()
    };
    map.insert(
        key.to_string(),
        Tensor::from_vec(data, shape.to_vec(), &Device::Cpu).unwrap(),
    );
}

/// Build the full dense-f32 weight map the [`CosmosDiT`] loader requires, under the `net` root (Cosmos
/// original key names). Every shape is derived from `cfg`, so this stays in lockstep with the loader.
fn synth_weight_map(cfg: &DitConfig) -> HashMap<String, Tensor> {
    let h = cfg.hidden_size(); // 12
    let hd = cfg.attention_head_dim; // 6
    let lora = cfg.adaln_lora_dim; // 8
    let ctx = cfg.text_embed_dim; // 8 (cross-attn kv input)
    let ff = (cfg.mlp_ratio * cfg.hidden_size() as f32) as usize; // 48
    let (pt, ph, pw) = cfg.patch_size;
    let patch_in = cfg.patch_in_channels() * pt * ph * pw; // 17·1·2·2 = 68
    let proj_out = ph * pw * pt * cfg.out_channels; // 2·2·1·16 = 64
    let mut w = HashMap::new();
    synth_tensor(&mut w, "net.x_embedder.proj.1.weight", &[h, patch_in]);
    synth_tensor(&mut w, "net.t_embedder.1.linear_1.weight", &[3 * h, h]);
    synth_tensor(&mut w, "net.t_embedder.1.linear_2.weight", &[3 * h, 3 * h]);
    synth_tensor(&mut w, "net.t_embedding_norm.weight", &[h]);
    for i in 0..cfg.num_layers {
        let b = format!("net.blocks.{i}");
        for m in [
            "adaln_modulation_self_attn",
            "adaln_modulation_cross_attn",
            "adaln_modulation_mlp",
        ] {
            synth_tensor(&mut w, &format!("{b}.{m}.1.weight"), &[lora, h]);
            synth_tensor(&mut w, &format!("{b}.{m}.2.weight"), &[3 * h, lora]);
        }
        for (attn, kv_in) in [("self_attn", h), ("cross_attn", ctx)] {
            synth_tensor(&mut w, &format!("{b}.{attn}.q_proj.weight"), &[h, h]);
            synth_tensor(&mut w, &format!("{b}.{attn}.k_proj.weight"), &[h, kv_in]);
            synth_tensor(&mut w, &format!("{b}.{attn}.v_proj.weight"), &[h, kv_in]);
            synth_tensor(&mut w, &format!("{b}.{attn}.output_proj.weight"), &[h, h]);
            synth_tensor(&mut w, &format!("{b}.{attn}.q_norm.weight"), &[hd]);
            synth_tensor(&mut w, &format!("{b}.{attn}.k_norm.weight"), &[hd]);
        }
        synth_tensor(&mut w, &format!("{b}.mlp.layer1.weight"), &[ff, h]);
        synth_tensor(&mut w, &format!("{b}.mlp.layer2.weight"), &[h, ff]);
    }
    synth_tensor(
        &mut w,
        "net.final_layer.adaln_modulation.1.weight",
        &[lora, h],
    );
    synth_tensor(
        &mut w,
        "net.final_layer.adaln_modulation.2.weight",
        &[2 * h, lora],
    );
    synth_tensor(&mut w, "net.final_layer.linear.weight", &[proj_out, h]);
    w
}

/// Run the full forward with the synthetic weights on candle CPU (fp32). NON-SQUARE latent `[1,16,1,4,6]`
/// (post-patch 2×3 — an h/w RoPE swap is detectable) + encoder `[1,5,8]` + `sigma=0.7`.
fn synth_full_velocity() -> Tensor {
    let cfg = synth_cfg();
    let map = synth_weight_map(&cfg);
    let vb = VarBuilder::from_tensors(map, DType::F32, &Device::Cpu);
    let dit = CosmosDiT::new(&vb.pp("net"), cfg).expect("synthetic DiT loads");
    let lat = SHARED_FIXTURE_SYNTH_LATENT_SHAPE;
    let enc = SHARED_FIXTURE_SYNTH_ENCODER_SHAPE;
    let latent = Tensor::from_vec(
        synth_lcg(lat.iter().product(), SHARED_FIXTURE_SYNTH_LATENT_SEED),
        (lat[0], lat[1], lat[2], lat[3], lat[4]),
        &Device::Cpu,
    )
    .unwrap();
    let encoder = Tensor::from_vec(
        synth_lcg(enc.iter().product(), SHARED_FIXTURE_SYNTH_ENCODER_SEED),
        (enc[0], enc[1], enc[2]),
        &Device::Cpu,
    )
    .unwrap();
    let sigma = Tensor::from_vec(vec![SHARED_FIXTURE_SYNTH_SIGMA], (1,), &Device::Cpu).unwrap();
    dit.forward(&latent, &sigma, &encoder, DType::F32)
        .expect("forward")
}

/// Assert a synthetic output against its committed summary with a distribution + sampled-relative-L2 gate
/// (the SAME gate shape the real-weights stages use). `stat_rtol` bounds mean/std/l2; `max_rel_l2` bounds
/// `‖got−want‖₂/‖want‖₂` over the fixed index set. Both absorb cross-device/-framework fp32 variance —
/// not a per-element bound.
fn assert_synth(got: &Tensor, g: &Value, label: &str, stat_rtol: f64, max_rel_l2: f64) {
    let want_shape: Vec<usize> = g["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect();
    assert_eq!(got.dims(), &want_shape[..], "{label}: shape");
    let flat: Vec<f64> = got
        .to_dtype(DType::F32)
        .unwrap()
        .flatten_all()
        .unwrap()
        .to_vec1::<f32>()
        .unwrap()
        .into_iter()
        .map(|x| x as f64)
        .collect();
    let count = g["count"].as_u64().unwrap() as usize;
    assert_eq!(flat.len(), count, "{label}: count");
    // (1) Aggregate distribution gate — cross-device fp32 reordering barely moves these; a structural bug
    //     shifts them by orders of magnitude.
    let mean = flat.iter().sum::<f64>() / count as f64;
    let std = (flat.iter().map(|&x| (x - mean).powi(2)).sum::<f64>() / count as f64).sqrt();
    let l2 = flat.iter().map(|&x| x * x).sum::<f64>().sqrt();
    let (gm, gs, gl) = (
        g["mean"].as_f64().unwrap(),
        g["std"].as_f64().unwrap(),
        g["l2"].as_f64().unwrap(),
    );
    let rel = |a: f64, b: f64| (a - b).abs() / b.abs().max(1e-6);
    assert!(
        (mean - gm).abs() < stat_rtol * gs.abs().max(1e-3),
        "{label}: mean drift {mean} vs {gm}"
    );
    assert!(rel(std, gs) < stat_rtol, "{label}: std drift {std} vs {gs}");
    assert!(rel(l2, gl) < stat_rtol, "{label}: l2 drift {l2} vs {gl}");
    // (2) Sampled relative-L2 gate — the primary structural check.
    let idx: Vec<usize> = g["sample_indices"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect();
    let vals: Vec<f64> = g["sample_values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect();
    assert!(idx.len() >= 16, "{label}: too few samples ({})", idx.len());
    let mut num = 0f64;
    let mut den = 0f64;
    for (&i, &want) in idx.iter().zip(&vals) {
        let d = flat[i] - want;
        num += d * d;
        den += want * want;
    }
    let rel_l2 = (num / den.max(1e-12)).sqrt();
    println!(
        "[{label}] rel-L2 = {rel_l2:.4e} (bound {max_rel_l2:.1e}); stats mean {mean:.5}/{gm:.5} \
         std {std:.5}/{gs:.5} l2 {l2:.4}/{gl:.4}"
    );
    assert!(
        rel_l2 < max_rel_l2,
        "{label}: sampled rel-L2 {rel_l2:.4e} exceeds {max_rel_l2:.1e} — a structural regression, \
         not cross-device fp32 noise"
    );
}

/// **CI numeric protection for the candle DiT forward** — runs the synthetic-weight Cosmos DiT on CPU (no
/// licensed weights, no snapshot) and asserts the final velocity against the committed cross-framework
/// golden. The final velocity is norm_out + proj_out (LayerNorm-conditioned), so it is the TIGHT gate:
/// `max_rel_l2 = 5e-3` clears the accumulated cross-device/-framework fp32 spread yet trips on every
/// structural mutation with >10× margin (drop-concat/adaLN-swap/RoPE-h/w-swap, per the MLX measurements).
#[test]
fn synthetic_dit_forward_golden() {
    let g = load_golden("dit_synthetic_golden.json");
    let full = synth_full_velocity();
    assert_synth(&full, &g["full"], "synth_full", 3e-3, 5e-3);
}
