//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "ar_generate.rs"]
mod ar_generate;

#[path = "causal_ar_torch_golden.rs"]
mod causal_ar_torch_golden;

#[path = "causal_forward.rs"]
mod causal_forward;

#[path = "generate_smoke.rs"]
mod generate_smoke;

#[path = "quant_tiers.rs"]
mod quant_tiers;

#[path = "rehost_real_weights.rs"]
mod rehost_real_weights;

#[path = "style_lora.rs"]
mod style_lora;

#[path = "style_lora_real_weights.rs"]
mod style_lora_real_weights;

#[path = "t2v_pipeline.rs"]
mod t2v_pipeline;

#[path = "transformer_load.rs"]
mod transformer_load;
