//! Recording → cover: a reviewed transcription ([`ReviewArtifact`]) becomes a YuE2 cover request
//! ([`candle_audio_yue2::cover::prepare_cover`]), and the cover is generated by the YuE2 engine only
//! after the transcription model is gone.
//!
//! * [`plan_cover`] — takes the transcribed score of the requested mode (`score_melody.abc` for
//!   `cot=melody`, `score.abc` with its chord symbols for `cot=full`) or the reviewer's edited copy,
//!   refuses a transcription the review marked unusable for that mode (e.g. no melody), builds and
//!   validates the request, and records the provenance: which recording (source identity), which
//!   transcription (manifest SHA-256, closure identity, the review's warnings), which score (and
//!   whether and how the reviewer changed its melody), the request, the lyric checks and the licence
//!   attributions.
//! * [`run_cover`] — the sequencing: unload the [`Transcriber`] (its receipt must show the model
//!   released), require that no SheetSage2 model is alive in the process ([`live_models`]), then —
//!   and only then — load the generator, generate into `dir/run`, and write `dir/cover.json`.
//!   Loading the generator is a closure, so the transcription and generation models are never
//!   resident together.

use std::path::{Path, PathBuf};

use candle_audio_yue2::cover::abc::KeepVoice;
use candle_audio_yue2::cover::abc::{compare, parse, VOICES};
use candle_audio_yue2::cover::{prepare_cover, CoverLyrics, CoverMode, CoverSpec, PreparedCover};
use candle_audio_yue2::license::{authorize_closure, IntendedUse};
use candle_audio_yue2::run::{verify_run, RunOutput, SongInput};
use candle_audio_yue2::{Closure, EngineHooks, SongRequest, SongSettings, Yue2Engine};
use serde_json::{json, Value};
use sha2::{Digest, Sha256};

use crate::provider::{live_models, Transcriber, UnloadReceipt};
use crate::review::{Readiness, ReviewArtifact, MELODY_SCORE};
use crate::Error;

/// `cover.json`'s schema.
pub const COVER_SCHEMA: &str = "sceneworks-yue2-cover-v1";
/// The provenance file of a cover directory.
pub const COVER_JSON: &str = "cover.json";
/// The engine run directory inside a cover directory.
pub const RUN_DIR: &str = "run";

/// What the cover is built from, besides the transcription.
#[derive(Clone, Debug, PartialEq)]
pub struct CoverOptions {
    /// Melody-only (`cot=melody`) or full score (`cot=full`).
    pub mode: CoverMode,
    /// The reviewer's edited score; `None` uses the transcribed score of `mode`.
    pub reviewed_score: Option<String>,
    /// Melodies a melody-only cover keeps.
    pub keep: KeepVoice,
    /// Target style.
    pub style: String,
    /// Source or translated lyrics.
    pub lyrics: CoverLyrics,
    /// Seed.
    pub seed: u64,
    /// CFG scale (`None` = mode default).
    pub cfg_scale: Option<f64>,
    /// Filename-safe id.
    pub id: String,
}

impl CoverOptions {
    /// Options with upstream's default seed and id and both melodies kept.
    pub fn new(mode: CoverMode, style: impl Into<String>, lyrics: CoverLyrics) -> Self {
        let spec = CoverSpec::new(mode, "", "", CoverLyrics::source(""));
        Self {
            mode,
            reviewed_score: None,
            keep: KeepVoice::Both,
            style: style.into(),
            lyrics,
            seed: spec.seed,
            cfg_scale: None,
            id: spec.id,
        }
    }
}

/// A validated cover request with its provenance.
#[derive(Clone, Debug)]
pub struct CoverPlan {
    /// The request and its checks.
    pub prepared: PreparedCover,
    /// The provenance record written to `cover.json`.
    pub provenance: Value,
}

fn sha256_hex(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// Build the cover request from a reviewed transcription (see the module docs).
pub fn plan_cover(artifact: &ReviewArtifact, options: &CoverOptions) -> Result<CoverPlan, Error> {
    let authorization =
        authorize_closure(Closure::Cover, IntendedUse::NoncommercialExperimentation)
            .map_err(|e| Error::Closure(e.to_string()))?;
    let melody_only = options.mode == CoverMode::Melody;
    let transcribed_file = if melody_only {
        MELODY_SCORE
    } else {
        "score.abc"
    };
    let transcribed = match artifact.readiness(melody_only) {
        Readiness::Ready => Some(
            String::from_utf8(artifact.read(transcribed_file)?)
                .map_err(|_| Error::Replay(format!("{transcribed_file} is not UTF-8")))?,
        ),
        Readiness::Refused(reason) => {
            if options.reviewed_score.is_none() {
                return Err(Error::Refused(format!(
                    "the transcription cannot serve a {} cover: {reason}",
                    if melody_only {
                        "melody-only"
                    } else {
                        "full-score"
                    }
                )));
            }
            None
        }
    };
    let (score, score_record) = match &options.reviewed_score {
        None => {
            let text = transcribed.expect("ready transcriptions have a score");
            let record = json!({"source": "transcribed", "file": transcribed_file});
            (text, record)
        }
        Some(edited) => {
            let differences = match &transcribed {
                Some(original) => {
                    let (a, b) = (
                        parse(original).map_err(|e| Error::Symbolic(e.to_string()))?,
                        parse(edited)
                            .map_err(|e| Error::Symbolic(format!("reviewed score: {e}")))?,
                    );
                    json!(compare(&a, &b, &VOICES, false))
                }
                None => {
                    json!(["the transcribed score was not usable; the reviewed score replaces it"])
                }
            };
            let record = json!({
                "source": "reviewed",
                "transcribed_file": transcribed_file,
                "melody_differences_from_transcription": differences,
            });
            (edited.clone(), record)
        }
    };
    let prepared = prepare_cover(&CoverSpec {
        mode: options.mode,
        score: score.clone(),
        keep: options.keep,
        style: options.style.clone(),
        lyrics: options.lyrics.clone(),
        seed: options.seed,
        cfg_scale: options.cfg_scale,
        id: options.id.clone(),
    })
    .map_err(|e| Error::Refused(e.to_string()))?;
    let plan_abc = prepared.request.abc().unwrap_or_default();
    let manifest = artifact.manifest();
    let provenance = json!({
        "schema": COVER_SCHEMA,
        "mode": {"cot": prepared.request.cot().as_str(), "keep_voices": options.keep.names()},
        "conditioning": "symbolic only: the plan score and the text request; no audio, reference \
                         audio or in-context-learning prompt reaches the generator",
        "transcription": {
            "manifest_sha256": artifact.manifest_sha256(),
            "source": manifest["source"],
            "settings": manifest["settings"],
            "closure": manifest["closure"],
            "warnings": manifest["review"]["warnings"],
        },
        "score": {
            "input_sha256": sha256_hex(score.as_bytes()),
            "plan_sha256": sha256_hex(plan_abc.as_bytes()),
            "record": score_record,
        },
        "lyrics": {
            "translated": options.lyrics.translated_from.is_some(),
            "source_lyrics": options.lyrics.translated_from,
        },
        "checks": prepared.report.to_json(),
        "request": prepared.request.to_json(),
        "licence": {
            "use": "noncommercial experimentation",
            "attributions": authorization.attributions(),
        },
    });
    Ok(CoverPlan {
        prepared,
        provenance,
    })
}

/// Generates the cover audio from a request (the YuE2 engine in production, a stand-in in tests).
pub trait CoverGenerator {
    /// Generate `request` into the fresh run directory `run_dir`; return the verified run record.
    fn generate(
        &self,
        request: &SongRequest,
        run_dir: &Path,
        cancelled: &dyn Fn() -> bool,
    ) -> Result<Value, Error>;
}

/// The YuE2 engine as a cover generator.
pub struct EngineCover {
    /// The loaded engine.
    pub engine: Yue2Engine,
    /// Sampling, ODE steps and decoder.
    pub settings: SongSettings,
}

impl CoverGenerator for EngineCover {
    fn generate(
        &self,
        request: &SongRequest,
        run_dir: &Path,
        cancelled: &dyn Fn() -> bool,
    ) -> Result<Value, Error> {
        let mut observer = ();
        let mut hooks = EngineHooks {
            cancelled,
            observer: &mut observer,
        };
        let outcome = self
            .engine
            .generate_to(
                &SongInput::Request(request.clone()),
                &self.settings,
                &RunOutput::fresh(run_dir),
                &mut hooks,
            )
            .map_err(|e| Error::Generation(e.to_string()))?;
        let identity = outcome.result["identity"].as_str().map(str::to_string);
        verify_run(run_dir, identity.as_deref()).map_err(|e| Error::Generation(e.to_string()))
    }
}

/// A finished cover.
#[derive(Clone, Debug)]
pub struct CoverOutcome {
    /// The engine run directory (`dir/run`).
    pub run_dir: PathBuf,
    /// Its verified `result.json`.
    pub result: Value,
    /// The transcriber's unload receipt, when one was handed in.
    pub unload: Option<UnloadReceipt>,
    /// `dir/cover.json`.
    pub provenance_path: PathBuf,
}

/// Unload the transcriber, prove no SheetSage2 model is alive, then load the generator and
/// generate the cover into `dir` (see the module docs).
pub fn run_cover<G: CoverGenerator>(
    transcriber: Option<Transcriber>,
    plan: &CoverPlan,
    load_generator: impl FnOnce() -> Result<G, Error>,
    dir: &Path,
    cancelled: &dyn Fn() -> bool,
) -> Result<CoverOutcome, Error> {
    if dir.exists()
        && std::fs::read_dir(dir)
            .map_err(|e| Error::io(dir, e))?
            .next()
            .is_some()
    {
        return Err(Error::Request(format!(
            "{} is not empty; a cover is written to a fresh directory",
            dir.display()
        )));
    }
    let unload = transcriber.map(Transcriber::unload);
    if let Some(receipt) = &unload {
        if !receipt.released {
            return Err(Error::Refused(
                "the transcription model was not released; refusing to load the generator".into(),
            ));
        }
    }
    let alive = live_models();
    if alive != 0 {
        return Err(Error::Refused(format!(
            "{alive} SheetSage2 model(s) still loaded; unload before generation"
        )));
    }
    let generator = load_generator()?;
    std::fs::create_dir_all(dir).map_err(|e| Error::io(dir, e))?;
    let run_dir = dir.join(RUN_DIR);
    let result = generator.generate(&plan.prepared.request, &run_dir, cancelled)?;
    let mut provenance = plan.provenance.clone();
    provenance["transcription_unloaded_before_generation"] = json!({
        "live_sheetsage2_models_at_generator_load": alive,
        "unload_receipt": unload.map(|r| json!({
            "released": r.released,
            "parameter_bytes": r.parameter_bytes,
            "live_models_after": r.live_models_after,
        })),
    });
    provenance["run"] = json!({
        "dir": RUN_DIR,
        "identity": result["identity"],
        "status": result["status"],
    });
    let path = dir.join(COVER_JSON);
    std::fs::write(
        &path,
        serde_json::to_vec_pretty(&provenance).expect("serializable"),
    )
    .map_err(|e| Error::io(&path, e))?;
    Ok(CoverOutcome {
        run_dir,
        result,
        unload,
        provenance_path: path,
    })
}

#[cfg(test)]
mod tests;
