//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "depth_parity.rs"]
mod depth_parity;

#[path = "depth_real_weights.rs"]
mod depth_real_weights;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "generator_contract.rs"]
mod generator_contract;

#[path = "real_weights.rs"]
mod real_weights;

#[path = "solver_parity.rs"]
mod solver_parity;

#[path = "text_parity.rs"]
mod text_parity;
