//! Forward-pass regression goldens: every `ModelConfig`-consuming architecture still **runs**
//! bit-identically after sc-18769 extended the shared config struct (sc-18769 review follow-up).
//!
//! `tests/architecture_regression.rs` pins what the config layer *parses and derives*. That is only
//! half the story's "every existing `Architecture` parses and runs bit-identically" clause: it
//! cannot see a change to the decoder loop itself. This suite closes that half — it builds a tiny
//! deterministic model per architecture, drives a real prefill plus two cached decode steps, and
//! compares **every logit** against a golden captured on the base branch.
//!
//! The goldens in `crates/llm/testdata/architectures/forward_mlx.json` were generated by running
//! this exact file on `origin/feature/sc-18755-ltx-2-5` (the branch point), so a match proves this
//! branch did not move a single output value. They keep guarding after this story lands: sc-18760
//! edits this same decoder loop to add Gemma 4's per-layer attention, and any drift it introduces
//! into the uniform architectures fails here.
//!
//! **Precision contract — and why this backend's differs from candle's.** MLX's Metal kernels are
//! not bit-reproducible across machine conditions, and three successive CI runs narrowed down
//! exactly which ones. Every drift observed landed on Gemma-2 or DeepSeek-V2, never on the other
//! six:
//!
//! * f32 bit-equality — gemma2 index 0, `1.0900694` vs `1.0915667` (Δ 1.5e-3);
//! * bf16 bit-equality — gemma2 index 1, `-0.17145248` vs `-0.17308894` (Δ 1.6e-3, ~2 bf16 ULPs);
//! * 4e-3 absolute — deepseek_v2 index 4, `0.83984375` vs `0.83203125` (Δ 7.8e-3, ~2 bf16 ULPs).
//!
//! All three passed 25/25 locally on an idle machine, so the variable is runner load. And those two
//! architectures are not an arbitrary pair: they are precisely the ones `sdpa_capped` routes to
//! `sdpa_eager` — Gemma-2 because its attention soft-cap forces it, DeepSeek-V2 because MLA's
//! query and value head dims differ. The eager path multiplies through `bmm` (a raw `matmul`), the
//! kernel this repo already documents as reproducible only to ~1e-3
//! (`mlx_metal_matmul_reduced_precision`, and the tile-shape dependence behind `sdpa`'s own 2e-3
//! tolerances). The other six run the fused SDPA kernel and have not moved.
//!
//! So the numeric comparison is **pinned for the six fused-path architectures** (at
//! [`FORWARD_ABS_TOL`], tight enough that a 1% attention-scale change — 7.8e-3 on llama — fails it)
//! and **not pinned for the two eager-`bmm` ones**, which are still built and run here for shape,
//! finiteness, and cache growth. Raising the tolerance until they fit would have taken it past the
//! point where it catches anything worth catching, so it is stated as a limit instead of hidden in
//! a bigger number.
//!
//! **The excluded two are not left uncovered.** `candle-llm`'s mirror of this file runs on a
//! deterministic CPU kernel and asserts raw f32 bit-equality on all eight architectures, built from
//! the same weights and driven through the same steps — so Gemma-2's and DeepSeek-V2's exact
//! numerics stay pinned bit-for-bit there. This suite's job is the Metal path.
//!
//! Regenerate (only ever against a known-good tree, and say so in the commit):
//!
//! ```text
//! SC18769_WRITE_FORWARD_GOLDEN=1 cargo test -p mlx-llm --test architecture_forward
//! ```

use std::collections::HashMap;

use mlx_rs::{Array, Dtype};
use serde_json::{json, Map, Value};

use mlx_llm::config::ModelConfig;
use mlx_llm::models::CausalLm;
use mlx_llm::primitives::sampler::{SplitMix64, TokenRng};
use mlx_llm::primitives::{input_ids, Weights};

const HIDDEN: i32 = 32;
const VOCAB: i32 = 48;
const HEAD_DIM: i32 = 8;
const LAYERS: usize = 2;
const HEADS: i32 = 4;
const KV: i32 = 2;
const INTER: i32 = 64;

/// The prompt every case prefills, then two cached decode steps at fixed token ids. Fixed rather
/// than sampled so the golden depends only on the decoder, never on a sampler.
const PROMPT: [i32; 5] = [1, 2, 3, 4, 5];
const DECODE_STEPS: [i32; 2] = [6, 7];

fn golden_path() -> std::path::PathBuf {
    std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../testdata/architectures/forward_mlx.json")
}

/// Small deterministic `[out, in]` weight. Identical draw sequence on both branches, so the built
/// model is the same model.
fn randn(shape: &[i32], rng: &mut SplitMix64) -> Array {
    let n: i32 = shape.iter().product();
    let data: Vec<f32> = (0..n).map(|_| (rng.next_f32() - 0.5) * 0.4).collect();
    Array::from_slice(&data, shape)
}

fn ones(d: i32) -> Array {
    Array::ones::<f32>(&[d]).unwrap()
}

fn dense_mlp(m: &mut HashMap<String, Array>, p: &dyn Fn(&str) -> String, rng: &mut SplitMix64) {
    m.insert(p("mlp.gate_proj.weight"), randn(&[INTER, HIDDEN], rng));
    m.insert(p("mlp.up_proj.weight"), randn(&[INTER, HIDDEN], rng));
    m.insert(p("mlp.down_proj.weight"), randn(&[HIDDEN, INTER], rng));
}

fn gqa_proj(
    m: &mut HashMap<String, Array>,
    p: &dyn Fn(&str) -> String,
    rng: &mut SplitMix64,
    bias: bool,
) {
    let (qd, kvd) = (HEADS * HEAD_DIM, KV * HEAD_DIM);
    m.insert(p("self_attn.q_proj.weight"), randn(&[qd, HIDDEN], rng));
    m.insert(p("self_attn.k_proj.weight"), randn(&[kvd, HIDDEN], rng));
    m.insert(p("self_attn.v_proj.weight"), randn(&[kvd, HIDDEN], rng));
    m.insert(p("self_attn.o_proj.weight"), randn(&[HIDDEN, qd], rng));
    if bias {
        m.insert(p("self_attn.q_proj.bias"), randn(&[qd], rng));
        m.insert(p("self_attn.k_proj.bias"), randn(&[kvd], rng));
        m.insert(p("self_attn.v_proj.bias"), randn(&[kvd], rng));
    }
}

/// One architecture's config plus the weight map that fits it.
struct Case {
    name: &'static str,
    family: &'static str,
    config: Value,
    weights: HashMap<String, Array>,
    /// Whether this architecture's logits are compared against the golden.
    ///
    /// `false` for the two architectures `sdpa_capped` routes to `sdpa_eager` (Gemma-2's attention
    /// soft-cap, DeepSeek-V2's mismatched MLA q/v head dims). Their forward still runs and is
    /// checked for shape and finiteness; their numerics are pinned bit-for-bit by the candle mirror
    /// instead. See the precision contract at the top of this file.
    numerics_pinned: bool,
}

fn llama() -> Case {
    let mut rng = SplitMix64::new(0x1876_9001);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        gqa_proj(&mut m, &p, &mut rng, false);
        dense_mlp(&mut m, &p, &mut rng);
    }
    Case {
        name: "llama",
        family: "llama",
        numerics_pinned: true,
        config: json!({
            "architectures": ["LlamaForCausalLM"], "model_type": "llama",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "head_dim": HEAD_DIM,
            "vocab_size": VOCAB, "rms_norm_eps": 1e-5, "rope_theta": 500000.0,
            "tie_word_embeddings": false,
            "rope_scaling": { "rope_type": "llama3", "factor": 8.0, "low_freq_factor": 1.0,
                "high_freq_factor": 4.0, "original_max_position_embeddings": 64 }
        }),
        weights: m,
    }
}

fn qwen3() -> Case {
    let mut rng = SplitMix64::new(0x1876_9002);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        gqa_proj(&mut m, &p, &mut rng, false);
        m.insert(p("self_attn.q_norm.weight"), randn(&[HEAD_DIM], &mut rng));
        m.insert(p("self_attn.k_norm.weight"), randn(&[HEAD_DIM], &mut rng));
        dense_mlp(&mut m, &p, &mut rng);
    }
    Case {
        name: "qwen3",
        family: "qwen3",
        numerics_pinned: true,
        config: json!({
            "architectures": ["Qwen3ForCausalLM"], "model_type": "qwen3",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "head_dim": HEAD_DIM,
            "vocab_size": VOCAB, "rms_norm_eps": 1e-6, "rope_theta": 1000000.0,
            "tie_word_embeddings": false
        }),
        weights: m,
    }
}

fn phi3() -> Case {
    let (qd, kvd) = (HEADS * HEAD_DIM, KV * HEAD_DIM);
    let mut rng = SplitMix64::new(0x1876_9003);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        m.insert(
            p("self_attn.qkv_proj.weight"),
            randn(&[qd + 2 * kvd, HIDDEN], &mut rng),
        );
        m.insert(p("self_attn.o_proj.weight"), randn(&[HIDDEN, qd], &mut rng));
        m.insert(
            p("mlp.gate_up_proj.weight"),
            randn(&[2 * INTER, HIDDEN], &mut rng),
        );
        m.insert(p("mlp.down_proj.weight"), randn(&[HIDDEN, INTER], &mut rng));
    }
    Case {
        name: "phi3",
        family: "phi3",
        numerics_pinned: true,
        config: json!({
            "architectures": ["Phi3ForCausalLM"], "model_type": "phi3",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "vocab_size": VOCAB,
            "rms_norm_eps": 1e-5, "rope_theta": 10000.0, "tie_word_embeddings": false
        }),
        weights: m,
    }
}

fn qwen2_moe() -> Case {
    let (n_exp, moe_inter, shared_inter) = (4usize, 16i32, 32i32);
    let mut rng = SplitMix64::new(0x1876_9004);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        gqa_proj(&mut m, &p, &mut rng, true);
        m.insert(
            p("mlp.gate.weight"),
            randn(&[n_exp as i32, HIDDEN], &mut rng),
        );
        for e in 0..n_exp {
            let ep = |s: &str| format!("model.layers.{i}.mlp.experts.{e}.{s}");
            m.insert(
                ep("gate_proj.weight"),
                randn(&[moe_inter, HIDDEN], &mut rng),
            );
            m.insert(ep("up_proj.weight"), randn(&[moe_inter, HIDDEN], &mut rng));
            m.insert(
                ep("down_proj.weight"),
                randn(&[HIDDEN, moe_inter], &mut rng),
            );
        }
        m.insert(
            p("mlp.shared_expert.gate_proj.weight"),
            randn(&[shared_inter, HIDDEN], &mut rng),
        );
        m.insert(
            p("mlp.shared_expert.up_proj.weight"),
            randn(&[shared_inter, HIDDEN], &mut rng),
        );
        m.insert(
            p("mlp.shared_expert.down_proj.weight"),
            randn(&[HIDDEN, shared_inter], &mut rng),
        );
        m.insert(
            p("mlp.shared_expert_gate.weight"),
            randn(&[1, HIDDEN], &mut rng),
        );
    }
    Case {
        name: "qwen2_moe",
        family: "qwen2_moe",
        numerics_pinned: true,
        config: json!({
            "architectures": ["Qwen2MoeForCausalLM"], "model_type": "qwen2_moe",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "vocab_size": VOCAB,
            "rms_norm_eps": 1e-6, "rope_theta": 1000000.0, "tie_word_embeddings": false,
            "num_experts": n_exp, "num_experts_per_tok": 2, "norm_topk_prob": false,
            "moe_intermediate_size": moe_inter, "shared_expert_intermediate_size": shared_inter
        }),
        weights: m,
    }
}

fn gemma2() -> Case {
    let mut rng = SplitMix64::new(0x1876_9005);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    // Gemma-2 norms are `(1 + weight)`; draw them rather than pinning ones, so the fold is live.
    m.insert("model.norm.weight".into(), randn(&[HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), randn(&[HIDDEN], &mut rng));
        m.insert(
            p("post_attention_layernorm.weight"),
            randn(&[HIDDEN], &mut rng),
        );
        m.insert(
            p("pre_feedforward_layernorm.weight"),
            randn(&[HIDDEN], &mut rng),
        );
        m.insert(
            p("post_feedforward_layernorm.weight"),
            randn(&[HIDDEN], &mut rng),
        );
        gqa_proj(&mut m, &p, &mut rng, false);
        dense_mlp(&mut m, &p, &mut rng);
    }
    Case {
        name: "gemma2",
        family: "gemma2",
        // `attn_logit_softcapping` forces `sdpa_eager`; see the precision contract.
        numerics_pinned: false,
        config: json!({
            "architectures": ["Gemma2ForCausalLM"], "model_type": "gemma2",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "head_dim": HEAD_DIM,
            "vocab_size": VOCAB, "rms_norm_eps": 1e-6, "rope_theta": 10000.0,
            "query_pre_attn_scalar": HEAD_DIM, "attn_logit_softcapping": 50.0,
            "final_logit_softcapping": 30.0
        }),
        weights: m,
    }
}

fn glm4() -> Case {
    let mut rng = SplitMix64::new(0x1876_9006);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_self_attn_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_mlp_layernorm.weight"), ones(HIDDEN));
        gqa_proj(&mut m, &p, &mut rng, true);
        m.insert(
            p("mlp.gate_up_proj.weight"),
            randn(&[2 * INTER, HIDDEN], &mut rng),
        );
        m.insert(p("mlp.down_proj.weight"), randn(&[HIDDEN, INTER], &mut rng));
    }
    Case {
        name: "glm4",
        family: "glm4",
        numerics_pinned: true,
        config: json!({
            "architectures": ["Glm4ForCausalLM"], "model_type": "glm4",
            "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
            "num_attention_heads": HEADS, "num_key_value_heads": KV, "head_dim": HEAD_DIM,
            "vocab_size": VOCAB, "rms_norm_eps": 1e-5, "rope_theta": 10000.0,
            "partial_rotary_factor": 0.5, "tie_word_embeddings": false
        }),
        weights: m,
    }
}

fn deepseek_v2() -> Case {
    let (heads, qk_nope, qk_rope, v_head, kv_lora) = (2i32, 16i32, 8i32, 16i32, 24i32);
    let q_head = qk_nope + qk_rope;
    let (n_routed, moe_inter, n_shared, dense_inter) = (4usize, 16i32, 1i32, 32i32);
    let mut rng = SplitMix64::new(0x1876_9007);
    let mut m = HashMap::new();
    m.insert(
        "model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        m.insert(
            p("self_attn.q_proj.weight"),
            randn(&[heads * q_head, HIDDEN], &mut rng),
        );
        m.insert(
            p("self_attn.kv_a_proj_with_mqa.weight"),
            randn(&[kv_lora + qk_rope, HIDDEN], &mut rng),
        );
        m.insert(p("self_attn.kv_a_layernorm.weight"), ones(kv_lora));
        m.insert(
            p("self_attn.kv_b_proj.weight"),
            randn(&[heads * (qk_nope + v_head), kv_lora], &mut rng),
        );
        m.insert(
            p("self_attn.o_proj.weight"),
            randn(&[HIDDEN, heads * v_head], &mut rng),
        );
        if i == 0 {
            // `first_k_dense_replace: 1` keeps layer 0 a dense MLP.
            m.insert(
                p("mlp.gate_proj.weight"),
                randn(&[dense_inter, HIDDEN], &mut rng),
            );
            m.insert(
                p("mlp.up_proj.weight"),
                randn(&[dense_inter, HIDDEN], &mut rng),
            );
            m.insert(
                p("mlp.down_proj.weight"),
                randn(&[HIDDEN, dense_inter], &mut rng),
            );
        } else {
            m.insert(
                p("mlp.gate.weight"),
                randn(&[n_routed as i32, HIDDEN], &mut rng),
            );
            for e in 0..n_routed {
                let ep = |s: &str| format!("model.layers.{i}.mlp.experts.{e}.{s}");
                m.insert(
                    ep("gate_proj.weight"),
                    randn(&[moe_inter, HIDDEN], &mut rng),
                );
                m.insert(ep("up_proj.weight"), randn(&[moe_inter, HIDDEN], &mut rng));
                m.insert(
                    ep("down_proj.weight"),
                    randn(&[HIDDEN, moe_inter], &mut rng),
                );
            }
            let shared_inter = n_shared * moe_inter;
            m.insert(
                p("mlp.shared_experts.gate_proj.weight"),
                randn(&[shared_inter, HIDDEN], &mut rng),
            );
            m.insert(
                p("mlp.shared_experts.up_proj.weight"),
                randn(&[shared_inter, HIDDEN], &mut rng),
            );
            m.insert(
                p("mlp.shared_experts.down_proj.weight"),
                randn(&[HIDDEN, shared_inter], &mut rng),
            );
        }
    }
    Case {
        name: "deepseek_v2",
        family: "deepseek_v2",
        // MLA's q head dim (24) != v head dim (16) forces `sdpa_eager`; see the precision contract.
        numerics_pinned: false,
        config: json!({
            "architectures": ["DeepseekV2ForCausalLM"], "model_type": "deepseek_v2",
            "hidden_size": HIDDEN, "intermediate_size": dense_inter, "num_hidden_layers": LAYERS,
            "num_attention_heads": heads, "num_key_value_heads": heads, "vocab_size": VOCAB,
            "rms_norm_eps": 1e-6, "rope_theta": 10000.0, "tie_word_embeddings": false,
            "q_lora_rank": null, "kv_lora_rank": kv_lora,
            "qk_nope_head_dim": qk_nope, "qk_rope_head_dim": qk_rope, "v_head_dim": v_head,
            "n_routed_experts": n_routed, "num_experts_per_tok": 2, "n_shared_experts": n_shared,
            "moe_intermediate_size": moe_inter, "first_k_dense_replace": 1,
            "norm_topk_prob": false, "routed_scaling_factor": 1.0,
            "rope_scaling": { "type": "yarn", "factor": 40, "beta_fast": 32, "beta_slow": 1,
                "mscale": 0.707, "mscale_all_dim": 0.707, "original_max_position_embeddings": 64 }
        }),
        weights: m,
    }
}

fn qwen3_vl() -> Case {
    let mut rng = SplitMix64::new(0x1876_9008);
    let mut m = HashMap::new();
    // VLM-nested layout: decoder under `model.language_model.*`, `lm_head.weight` at the root.
    m.insert(
        "model.language_model.embed_tokens.weight".into(),
        randn(&[VOCAB, HIDDEN], &mut rng),
    );
    m.insert("model.language_model.norm.weight".into(), ones(HIDDEN));
    m.insert("lm_head.weight".into(), randn(&[VOCAB, HIDDEN], &mut rng));
    for i in 0..LAYERS {
        let p = |s: &str| format!("model.language_model.layers.{i}.{s}");
        m.insert(p("input_layernorm.weight"), ones(HIDDEN));
        m.insert(p("post_attention_layernorm.weight"), ones(HIDDEN));
        gqa_proj(&mut m, &p, &mut rng, false);
        m.insert(p("self_attn.q_norm.weight"), randn(&[HEAD_DIM], &mut rng));
        m.insert(p("self_attn.k_norm.weight"), randn(&[HEAD_DIM], &mut rng));
        dense_mlp(&mut m, &p, &mut rng);
    }
    Case {
        name: "qwen3_vl",
        family: "qwen3_vl",
        numerics_pinned: true,
        config: json!({
            "architectures": ["Qwen3VLForConditionalGeneration"], "model_type": "qwen3_vl",
            "tie_word_embeddings": false, "image_token_id": 40,
            "text_config": {
                "model_type": "qwen3_vl_text",
                "hidden_size": HIDDEN, "intermediate_size": INTER, "num_hidden_layers": LAYERS,
                "num_attention_heads": HEADS, "num_key_value_heads": KV, "head_dim": HEAD_DIM,
                "vocab_size": VOCAB, "rms_norm_eps": 1e-6, "rope_theta": 5000000.0,
                "max_position_embeddings": 262144,
                "rope_scaling": { "mrope_interleaved": true, "mrope_section": [2, 1, 1],
                                  "rope_type": "default" }
            },
            "vision_config": { "model_type": "qwen3_vl", "depth": 2 }
        }),
        weights: m,
    }
}

/// Every architecture the shared [`ModelConfig`] serves through the generic decoder.
///
/// Qwen3.6 (`qwen3_5`) is absent on purpose: `ModelConfig::from_json` declines it, and it is served
/// by its own `Qwen35Config`/`Qwen35Model`. Gemma 4 is absent because its decoder does not exist yet
/// (sc-18760); when it does, it belongs here.
fn cases() -> Vec<Case> {
    vec![
        llama(),
        qwen3(),
        phi3(),
        qwen2_moe(),
        gemma2(),
        glm4(),
        deepseek_v2(),
        qwen3_vl(),
    ]
}

/// Prefill `PROMPT`, then run `DECODE_STEPS` cached decode steps, concatenating every logit vector
/// the model produced. Exercises the whole decoder loop — projections, RoPE, attention, KV cache
/// growth, norms, FFN (dense / MoE / MLA), and the LM head — not just a shape.
fn run_forward(case: &Case) -> Vec<f32> {
    let cfg = ModelConfig::from_json(&case.config)
        .unwrap_or_else(|e| panic!("{}: config must parse: {e}", case.name));
    assert_eq!(
        cfg.architecture.family(),
        case.family,
        "{}: family dispatch",
        case.name
    );
    let weights = Weights::from_map(case.weights.clone());
    let model = CausalLm::from_weights(&weights, "", cfg)
        .unwrap_or_else(|e| panic!("{}: model must build: {e}", case.name));

    let mut cache = model.new_cache();
    let mut out = Vec::new();
    let logits = model
        .decode_logits(&input_ids(&PROMPT), &mut cache, 0)
        .unwrap_or_else(|e| panic!("{}: prefill: {e}", case.name));
    out.extend(host(&logits));
    for (step, tok) in DECODE_STEPS.iter().enumerate() {
        let offset = PROMPT.len() as i32 + step as i32;
        let logits = model
            .decode_logits(&input_ids(&[*tok]), &mut cache, offset)
            .unwrap_or_else(|e| panic!("{}: decode {step}: {e}", case.name));
        out.extend(host(&logits));
    }
    assert_eq!(
        out.len(),
        VOCAB as usize * (1 + DECODE_STEPS.len()),
        "{}: one [1, vocab] row per step",
        case.name
    );
    assert!(
        out.iter().all(|x| x.is_finite()),
        "{}: non-finite logits",
        case.name
    );
    out
}

/// How far a logit may move between two runs of the same MLX graph before it counts as a change.
///
/// Applies to the six fused-SDPA architectures only (see the precision contract). Absolute rather
/// than relative because the drift tracks the largest intermediates, not each value's own
/// magnitude. A 1% attention-scale change moves llama's logits by 7.8e-3, so real changes stay
/// outside it; the eager-`bmm` architectures drift by about that much on their own, which is why
/// they are excluded rather than accommodated.
const FORWARD_ABS_TOL: f32 = 4e-3;

fn host(a: &Array) -> Vec<f32> {
    a.as_dtype(Dtype::Float32)
        .unwrap()
        .as_slice::<f32>()
        .to_vec()
}

/// **The regression gate.** Every architecture's full forward output, as the base branch produced
/// it — matched within the Metal band (see the precision contract above) — plus the coverage check
/// that the case list is exactly the generic-decoder architecture set.
///
/// Deliberately a **single** test: a second `#[test]` in this binary runs on a second thread, and
/// building its cases would touch MLX concurrently with this one's forward passes. That is exactly
/// the kind of contention the precision contract above is about, and there is no reason to invite
/// it inside our own test binary.
#[test]
fn every_architecture_forward_matches_the_base_branch() {
    let cases = cases();
    assert_case_coverage(&cases);

    if std::env::var("SC18769_WRITE_FORWARD_GOLDEN").is_ok() {
        let mut doc = Map::new();
        doc.insert(
            "_note".into(),
            Value::String(
                "Generated by `SC18769_WRITE_FORWARD_GOLDEN=1 cargo test -p mlx-llm --test \
                 architecture_forward`. Captured on origin/feature/sc-18755-ltx-2-5 so the values \
                 predate sc-18769's changes to the shared ModelConfig and decoder."
                    .into(),
            ),
        );
        for case in &cases {
            let values: Vec<Value> = run_forward(case)
                .into_iter()
                .map(|x| json!(x as f64))
                .collect();
            doc.insert(case.name.into(), Value::Array(values));
        }
        let path = golden_path();
        std::fs::create_dir_all(path.parent().unwrap()).unwrap();
        std::fs::write(&path, serde_json::to_string_pretty(&doc).unwrap() + "\n").unwrap();
        eprintln!("wrote {}", path.display());
        return;
    }

    let text = std::fs::read_to_string(golden_path()).expect("forward goldens must be committed");
    let golden: Value = serde_json::from_str(&text).expect("parse forward goldens");
    let mut pinned = 0;
    for case in &cases {
        let want: Vec<f32> = golden[case.name]
            .as_array()
            .unwrap_or_else(|| panic!("{}: missing from the forward goldens", case.name))
            .iter()
            .map(|x| x.as_f64().unwrap() as f32)
            .collect();
        // Always run it: shape, finiteness and cache growth are asserted inside `run_forward`, and
        // they are worth checking on every architecture regardless of kernel reproducibility.
        let got = run_forward(case);
        assert_eq!(got.len(), want.len(), "{}: logit count", case.name);
        if !case.numerics_pinned {
            continue;
        }
        pinned += 1;
        if let Some((i, (g, w))) = got
            .iter()
            .zip(&want)
            .enumerate()
            .find(|(_, (g, w))| (*g - *w).abs() > FORWARD_ABS_TOL)
        {
            panic!(
                "{name}: forward output moved at index {i} by {delta} (got {g}, the base branch \
                 produced {w}) — beyond the {tol} Metal reproducibility band. The shared decoder \
                 or config changed this architecture's numerics.",
                name = case.name,
                delta = (g - w).abs(),
                tol = FORWARD_ABS_TOL,
            );
        }
    }
    assert_eq!(
        pinned, 6,
        "six fused-SDPA architectures must have their numerics pinned here; the other two are \
         pinned by the candle mirror"
    );
}

/// The case list must cover **every** architecture the generic decoder serves, so a newly-added one
/// cannot land without a forward golden.
fn assert_case_coverage(cases: &[Case]) {
    let covered: std::collections::BTreeSet<&str> = cases.iter().map(|c| c.family).collect();
    let expected: std::collections::BTreeSet<&str> = [
        "llama",
        "qwen3",
        "phi3",
        "qwen2_moe",
        "gemma2",
        "glm4",
        "deepseek_v2",
        "qwen3_vl",
    ]
    .into_iter()
    .collect();
    assert_eq!(
        covered, expected,
        "the forward suite must cover exactly the generic-decoder architectures"
    );
}
