//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[allow(dead_code)]
mod common;

#[path = "architecture_forward.rs"]
mod architecture_forward;

#[path = "architecture_regression.rs"]
mod architecture_regression;

#[path = "batch.rs"]
mod batch;

#[path = "breadth.rs"]
mod breadth;

#[path = "byo.rs"]
mod byo;

#[path = "conformance.rs"]
mod conformance;

#[path = "continuous.rs"]
mod continuous;

#[path = "contract_roundtrip.rs"]
mod contract_roundtrip;

#[path = "gemma4_decoder.rs"]
mod gemma4_decoder;

#[path = "gemma4_primitives.rs"]
mod gemma4_primitives;

#[path = "gemma4_real_weights.rs"]
mod gemma4_real_weights;

#[path = "gemma4_sequential_residency.rs"]
mod gemma4_sequential_residency;

#[path = "gguf.rs"]
mod gguf;

#[path = "gguf_tokenizer.rs"]
mod gguf_tokenizer;

#[path = "joycaption.rs"]
mod joycaption;

#[path = "ltx_2_5_te_tier_quality.rs"]
mod ltx_2_5_te_tier_quality;

#[path = "paged.rs"]
mod paged;

#[path = "prefix.rs"]
mod prefix;

#[path = "prepare_snapshot.rs"]
mod prepare_snapshot;

#[path = "qwen35.rs"]
mod qwen35;

#[path = "qwen35_tools.rs"]
mod qwen35_tools;

#[path = "qwen35_vision.rs"]
mod qwen35_vision;

#[path = "qwen3vl.rs"]
mod qwen3vl;

#[path = "real_breadth.rs"]
mod real_breadth;

#[path = "real_weights.rs"]
mod real_weights;

#[path = "snapshot_hf.rs"]
mod snapshot_hf;

#[path = "speculative.rs"]
mod speculative;

#[path = "stop_strings.rs"]
mod stop_strings;

#[path = "streaming.rs"]
mod streaming;

#[path = "structured.rs"]
mod structured;

#[path = "thinking.rs"]
mod thinking;

#[path = "throughput_breakdown.rs"]
mod throughput_breakdown;
