//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "cfg_off_smoke.rs"]
mod cfg_off_smoke;

#[path = "chatglm_parity.rs"]
mod chatglm_parity;

#[path = "conditioned_curated_smoke.rs"]
mod conditioned_curated_smoke;

#[path = "controlnet_ip_parity.rs"]
mod controlnet_ip_parity;

#[path = "controlnet_parity.rs"]
mod controlnet_parity;

#[path = "decode_quality_admission.rs"]
mod decode_quality_admission;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "img2img_parity.rs"]
mod img2img_parity;

#[path = "ip_adapter_parity.rs"]
mod ip_adapter_parity;

#[path = "lora_parity.rs"]
mod lora_parity;

#[path = "memory_ladder_real_weights.rs"]
mod memory_ladder_real_weights;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "quant_parity.rs"]
mod quant_parity;

#[path = "registry_parity.rs"]
mod registry_parity;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "t2i_parity.rs"]
mod t2i_parity;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "unet_parity.rs"]
mod unet_parity;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;
