//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "conformance.rs"]
mod conformance;

#[path = "conformance_14b.rs"]
mod conformance_14b;

#[path = "trainer_conformance.rs"]
mod trainer_conformance;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "training_modes_cuda.rs"]
mod training_modes_cuda;

#[path = "vae16_decode_sweep.rs"]
mod vae16_decode_sweep;

#[path = "vae16_tiling_cuda.rs"]
mod vae16_tiling_cuda;

#[path = "vae_decode_sweep.rs"]
mod vae_decode_sweep;

#[path = "vae_tiling_cuda.rs"]
mod vae_tiling_cuda;

#[path = "vram_probe.rs"]
mod vram_probe;
