//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "accel_sampler_parity.rs"]
mod accel_sampler_parity;

#[path = "atomic_cache.rs"]
mod atomic_cache;

#[path = "block_residency_real_weights.rs"]
mod block_residency_real_weights;

#[path = "causal_mask_equiv.rs"]
mod causal_mask_equiv;

#[path = "lora_train_probe.rs"]
mod lora_train_probe;

#[path = "mlx_write_bound_probe.rs"]
mod mlx_write_bound_probe;

#[path = "preview_readback.rs"]
mod preview_readback;

#[path = "qkv_family_fixtures.rs"]
mod qkv_family_fixtures;

#[path = "quant_parity.rs"]
mod quant_parity;

#[path = "rung4_block_residency_spike.rs"]
mod rung4_block_residency_spike;

#[path = "scheduler.rs"]
mod scheduler;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;
