//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// mlx-gen's atomic-cache fixture, shared by the four real-weight producer/consumer modules.
// Declared once here (a per-file `#[path]` copy trips `clippy::duplicate_mod`); the modules
// say `use crate::atomic_cache;`.
#[path = "../../tests/support/atomic_cache.rs"]
#[allow(dead_code)] // not every module assembles symlink components
mod atomic_cache;
// --- generated modules (do not edit) ---

#[path = "adapter_real_weights.rs"]
mod adapter_real_weights;

#[path = "caption_upsample_golden.rs"]
mod caption_upsample_golden;

#[path = "caption_upsample_real_weights.rs"]
mod caption_upsample_real_weights;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "compile_parity.rs"]
mod compile_parity;

#[path = "control_parity.rs"]
mod control_parity;

#[path = "control_real_weights.rs"]
mod control_real_weights;

#[path = "convert_real_weights.rs"]
mod convert_real_weights;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dev_adapter_real_weights.rs"]
mod dev_adapter_real_weights;

#[path = "dev_e2e_real_weights.rs"]
mod dev_e2e_real_weights;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "edit_real_weights.rs"]
mod edit_real_weights;

#[path = "execution_domain_reachability.rs"]
mod execution_domain_reachability;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "fun_control_parity.rs"]
mod fun_control_parity;

#[path = "img2img_real_weights.rs"]
mod img2img_real_weights;

#[path = "img_guidance_spike.rs"]
mod img_guidance_spike;

#[path = "klein_rehost_real_weights.rs"]
mod klein_rehost_real_weights;

#[path = "kv_cache_parity.rs"]
mod kv_cache_parity;

#[path = "kv_cache_real_weights.rs"]
mod kv_cache_real_weights;

#[path = "perf.rs"]
mod perf;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "quant_prequantize_real_weights.rs"]
mod quant_prequantize_real_weights;

#[path = "quant_real_weights.rs"]
mod quant_real_weights;

#[path = "registry.rs"]
mod registry;

#[path = "s0_parity.rs"]
mod s0_parity;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "te_dev_parity.rs"]
mod te_dev_parity;

#[path = "te_dev_real_weights.rs"]
mod te_dev_real_weights;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "te_real_weights.rs"]
mod te_real_weights;

#[path = "thirdparty_lycoris_real_weights.rs"]
mod thirdparty_lycoris_real_weights;

#[path = "transformer_chunk_equiv.rs"]
mod transformer_chunk_equiv;

#[path = "transformer_dev_real_weights.rs"]
mod transformer_dev_real_weights;

#[path = "transformer_parity.rs"]
mod transformer_parity;

#[path = "transformer_real_weights.rs"]
mod transformer_real_weights;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;

#[path = "vae_real_weights.rs"]
mod vae_real_weights;

#[path = "vision_parity.rs"]
mod vision_parity;
