//! Cross-backend σ-schedule goldens (epic 20414, sc-20416).
//!
//! The scheduler math is host math in `gen_core::sampling::schedulers`, and both engines reach it
//! through the same one-line seam (`candle_gen::resolve_schedule` / `mlx_gen::resolve_schedule`).
//! That seam is the thing this module tests: given a backend's resolver, it replays a checked-in
//! table of independently derived σ vectors and reports any drift. MLX and candle both run it, so
//! "the two backends receive identical coefficients" is a CI failure when it stops being true rather
//! than a parity report months later.
//!
//! The fixture (`fixtures/schedule_golden.json`) is regenerated by the standalone
//! `fixtures/gen_schedule_golden.py`, which transcribes the published closed forms in plain Python
//! and shares no code with the Rust port — see that script's header for the derivations, the licence
//! reasoning, and the documented ambiguity in `bong_tangent`'s defaults.
//!
//! ```ignore
//! // candle lane
//! gen_core_testkit::schedules::schedule_conformance("candle", &|name, ms, steps| {
//!     candle_gen::resolve_schedule(Some(name), ms, steps, &[])
//! });
//! ```

use gen_core::sampling::{FlowModelSampling, ModelSampling, TimestepConvention};

/// The checked-in golden table. Lives inside this crate so the `include_str!` cannot escape the
/// crate root (which breaks the Docker build).
const GOLDEN_JSON: &str = include_str!("../fixtures/schedule_golden.json");

/// Absolute tolerance for a golden comparison. The Rust port computes in `f64` and emits `f32`; the
/// generator stays in `f64`, so the measured drift is at the `f32` rounding floor.
pub const SCHEDULE_GOLDEN_TOLERANCE: f32 = 1e-6;

/// One golden schedule: the coefficients `scheduler` must produce for `steps` denoise steps over
/// `model`.
#[derive(Clone, Debug)]
pub struct ScheduleGoldenCase {
    /// The canonical scheduler id (`linear_quadratic` / `bong_tangent`).
    pub scheduler: String,
    /// Which `ModelSampling` the golden was generated against — see [`golden_model_sampling`].
    pub model: String,
    /// The denoise step count. The schedule is `steps + 1` long.
    pub steps: usize,
    /// Why this length is in the table (e.g. the epic-20414 KreaMania passes).
    pub note: String,
    /// The expected σ schedule, descending with a trailing `0.0`.
    pub sigmas: Vec<f32>,
}

/// A backend's schedule seam: `(scheduler id, model sampling, steps) -> σ schedule`.
pub type ScheduleResolver<'a> = dyn Fn(&str, &dyn ModelSampling, usize) -> Vec<f32> + 'a;

/// The golden table, parsed. Panics if the fixture is missing or malformed — it is compiled in, so
/// that can only be a bad edit.
pub fn schedule_goldens() -> Vec<ScheduleGoldenCase> {
    let doc: serde_json::Value =
        serde_json::from_str(GOLDEN_JSON).expect("parse fixtures/schedule_golden.json");
    let cases = doc["cases"]
        .as_array()
        .expect("schedule_golden.json has a `cases` array");
    cases
        .iter()
        .map(|c| ScheduleGoldenCase {
            scheduler: c["scheduler"].as_str().expect("scheduler").to_owned(),
            model: c["model"].as_str().expect("model").to_owned(),
            steps: c["steps"].as_u64().expect("steps") as usize,
            note: c["note"].as_str().unwrap_or_default().to_owned(),
            sigmas: c["sigmas"]
                .as_array()
                .expect("sigmas")
                .iter()
                .map(|s| s.as_f64().expect("sigma") as f32)
                .collect(),
        })
        .collect()
}

/// The [`ModelSampling`] a golden's `model` field names. Only `flow` (σ_max = 1) is generated: the
/// two advanced schedules are pure shape × σ_max, a property gen-core's own suite pins separately,
/// so a σ_max = 1 table is the complete numeric statement.
pub fn golden_model_sampling(model: &str) -> Box<dyn ModelSampling> {
    match model {
        "flow" => Box::new(FlowModelSampling::new(TimestepConvention::Sigma)),
        other => panic!("schedule golden names an unknown model sampling: {other:?}"),
    }
}

/// Replay every golden through `resolve` and collect the mismatches.
pub fn check_schedule_goldens(resolve: &ScheduleResolver<'_>) -> Result<(), String> {
    let goldens = schedule_goldens();
    if goldens.is_empty() {
        return Err("schedule goldens: the fixture table is empty".to_owned());
    }
    let mut failures: Vec<String> = Vec::new();
    for case in &goldens {
        let ms = golden_model_sampling(&case.model);
        let got = resolve(&case.scheduler, ms.as_ref(), case.steps);
        let label = format!(
            "{} @ {} steps ({})",
            case.scheduler,
            case.steps,
            if case.note.is_empty() {
                "shape"
            } else {
                &case.note
            }
        );
        if got.len() != case.sigmas.len() {
            failures.push(format!(
                "{label}: length {} != golden {}",
                got.len(),
                case.sigmas.len()
            ));
            continue;
        }
        for (i, (g, w)) in got.iter().zip(&case.sigmas).enumerate() {
            if !g.is_finite() {
                failures.push(format!("{label}: sigma[{i}] is not finite ({g})"));
                break;
            }
            if (g - w).abs() > SCHEDULE_GOLDEN_TOLERANCE {
                failures.push(format!(
                    "{label}: sigma[{i}] = {g} != golden {w} (tolerance {SCHEDULE_GOLDEN_TOLERANCE})"
                ));
                break;
            }
        }
    }
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("\n  - "))
    }
}

/// Whether a golden for `scheduler` must be exactly `steps + 1` long. The advanced pair and most
/// curated builders preserve the requested length; ComfyUI's `ddim_uniform` re-strides and the two
/// beta variants dedup consecutive table indices, so their recorded lengths are whatever the
/// builder produced (still pinned byte-for-byte by [`check_schedule_goldens`]).
fn golden_length_is_exact(scheduler: &str) -> bool {
    !matches!(scheduler, "ddim_uniform" | "beta" | "beta57")
}

/// The golden table's own coverage contract: representative short and production-length schedules,
/// including the epic-20414 KreaMania 10-step and 4-step passes, for **every** scheduler id — the
/// advanced pair (sc-20416) and the curated eight (byte-pinned in sc-20418).
pub fn check_schedule_golden_coverage() -> Result<(), String> {
    use gen_core::sampling::Scheduler;
    let goldens = schedule_goldens();
    let mut failures: Vec<String> = Vec::new();
    for scheduler in Scheduler::EVERY.iter().map(|s| s.name()) {
        let steps: Vec<usize> = goldens
            .iter()
            .filter(|c| c.scheduler == scheduler)
            .map(|c| c.steps)
            .collect();
        for required in [1_usize, 4, 10, 50] {
            if !steps.contains(&required) {
                failures.push(format!(
                    "schedule goldens: {scheduler} has no {required}-step case (have {steps:?})"
                ));
            }
        }
    }
    for case in &goldens {
        if golden_length_is_exact(&case.scheduler) && case.sigmas.len() != case.steps + 1 {
            failures.push(format!(
                "schedule goldens: {} @ {} steps has {} sigmas, expected {}",
                case.scheduler,
                case.steps,
                case.sigmas.len(),
                case.steps + 1
            ));
        }
        if case.sigmas.len() < 2 {
            failures.push(format!(
                "schedule goldens: {} @ {} steps is degenerate ({} node(s))",
                case.scheduler,
                case.steps,
                case.sigmas.len()
            ));
        }
        if case.sigmas.last() != Some(&0.0) {
            failures.push(format!(
                "schedule goldens: {} @ {} steps does not terminate on 0.0",
                case.scheduler, case.steps
            ));
        }
        if !case.sigmas.windows(2).all(|w| w[0] > w[1]) {
            failures.push(format!(
                "schedule goldens: {} @ {} steps is not strictly descending",
                case.scheduler, case.steps
            ));
        }
    }
    if failures.is_empty() {
        Ok(())
    } else {
        Err(failures.join("\n  - "))
    }
}

/// Run every schedule check against one backend's seam, panicking with the aggregated failures.
/// `backend` only labels the panic (`"candle"` / `"mlx"`).
pub fn schedule_conformance(backend: &str, resolve: &ScheduleResolver<'_>) {
    let failures: Vec<String> = [
        check_schedule_golden_coverage(),
        check_schedule_goldens(resolve),
    ]
    .into_iter()
    .filter_map(|r| r.err())
    .collect();
    if !failures.is_empty() {
        panic!(
            "shared σ-schedule conformance FAILED for the {backend} seam (gen-core {}):\n  - {}",
            gen_core::VERSION,
            failures.join("\n  - ")
        );
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use gen_core::sampling::{schedule_sigmas, Scheduler};

    /// The shared host math itself matches the independently derived goldens. Every backend seam
    /// then only has to prove it delegates here unchanged.
    #[test]
    fn shared_gen_core_math_matches_the_goldens() {
        schedule_conformance("gen-core", &|name, ms, steps| {
            let sched = Scheduler::from_name(name)
                .unwrap_or_else(|| panic!("golden names an unknown scheduler: {name:?}"));
            schedule_sigmas(sched, ms, steps)
        });
    }

    /// The table covers exactly the known scheduler vocabulary — the advanced pair AND (since
    /// sc-20418) the curated eight, whose builder math previously had no external byte-pin (its
    /// only guard recomputed both sides from the same Rust builders). No unknown id may appear.
    #[test]
    fn goldens_cover_every_scheduler_and_nothing_else() {
        let known: Vec<&str> = Scheduler::EVERY.iter().map(|s| s.name()).collect();
        let goldens = schedule_goldens();
        for case in &goldens {
            assert!(
                known.contains(&case.scheduler.as_str()),
                "unexpected golden scheduler {:?}",
                case.scheduler
            );
        }
        for id in known {
            assert!(
                goldens.iter().any(|c| c.scheduler == id),
                "scheduler {id:?} has no golden cases"
            );
        }
    }

    #[test]
    fn a_drifting_seam_is_reported_not_silently_passed() {
        let err = check_schedule_goldens(&|name, ms, steps| {
            let sched = Scheduler::from_name(name).unwrap();
            let mut s = schedule_sigmas(sched, ms, steps);
            if let Some(x) = s.get_mut(0) {
                *x += 0.01;
            }
            s
        })
        .expect_err("a perturbed seam must fail");
        assert!(err.contains("sigma[0]"), "{err}");
    }
}
