//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "eva_clip_parity.rs"]
mod eva_clip_parity;

#[path = "idformer_parity.rs"]
mod idformer_parity;

#[path = "pulid_ca_parity.rs"]
mod pulid_ca_parity;

#[path = "pulid_flux_e2e.rs"]
mod pulid_flux_e2e;

#[path = "pulid_flux_quant.rs"]
mod pulid_flux_quant;

#[path = "registration.rs"]
mod registration;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;
