//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "encoder_parity.rs"]
mod encoder_parity;

#[path = "memory_parity.rs"]
mod memory_parity;

#[path = "photo_parity.rs"]
mod photo_parity;

#[path = "segmenter_parity.rs"]
mod segmenter_parity;

#[path = "video_parity.rs"]
mod video_parity;

#[path = "weights_load.rs"]
mod weights_load;
