//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod rung4_support;

#[path = "capped_pool_vram_ceiling.rs"]
mod capped_pool_vram_ceiling;

#[path = "cublaslt_8bit_numerics.rs"]
mod cublaslt_8bit_numerics;

#[path = "cublaslt_nvfp4_gemm.rs"]
mod cublaslt_nvfp4_gemm;

#[path = "cuda_quant_smoke.rs"]
mod cuda_quant_smoke;

#[path = "int8_per_channel_numerics.rs"]
mod int8_per_channel_numerics;

#[path = "mlx_repack_real_weights.rs"]
mod mlx_repack_real_weights;

#[path = "nvfp4_linear_gpu.rs"]
mod nvfp4_linear_gpu;

#[path = "nvfp4_w4a4_ondevice_gpu.rs"]
mod nvfp4_w4a4_ondevice_gpu;

#[path = "rung4_block_streaming_spike.rs"]
mod rung4_block_streaming_spike;

#[path = "rung4_block_window_real_weights.rs"]
mod rung4_block_window_real_weights;
