//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "adapter_routing.rs"]
mod adapter_routing;

#[path = "base_real_weights.rs"]
mod base_real_weights;

#[path = "config_conformance.rs"]
mod config_conformance;

#[path = "dit_real_weights.rs"]
mod dit_real_weights;

#[path = "edit_quant_real_weights.rs"]
mod edit_quant_real_weights;

#[path = "edit_real_weights.rs"]
mod edit_real_weights;

#[path = "gaussian_shading_parity.rs"]
mod gaussian_shading_parity;

#[path = "mage_flow_small.rs"]
mod mage_flow_small;

#[path = "msrope_golden.rs"]
mod msrope_golden;

#[path = "pipeline_real_weights.rs"]
mod pipeline_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "quant_real_weights.rs"]
mod quant_real_weights;

#[path = "request_memory_scope_real_weights.rs"]
mod request_memory_scope_real_weights;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "te_parity_real_weights.rs"]
mod te_parity_real_weights;

#[path = "text_encoder_forward.rs"]
mod text_encoder_forward;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "turbo_real_weights.rs"]
mod turbo_real_weights;

#[path = "vae_decode_fixture.rs"]
mod vae_decode_fixture;

#[path = "vae_decode_real_weights.rs"]
mod vae_decode_real_weights;

#[path = "vae_encode_real_weights.rs"]
mod vae_encode_real_weights;

#[path = "variable_geometry_real_weights.rs"]
mod variable_geometry_real_weights;
