//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "conformance.rs"]
mod conformance;

#[path = "connector_parity.rs"]
mod connector_parity;

#[path = "duration_head_golden.rs"]
mod duration_head_golden;

#[path = "ltx_2_5_vae_conformance.rs"]
mod ltx_2_5_vae_conformance;

#[path = "ltx_2_5_vae_real_weights.rs"]
mod ltx_2_5_vae_real_weights;

#[path = "packed_tier_validate.rs"]
mod packed_tier_validate;

#[path = "sc18758_ff_bias_keyframes_conformance.rs"]
mod sc18758_ff_bias_keyframes_conformance;

#[path = "split_checkpoint.rs"]
mod split_checkpoint;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "trainer_conformance.rs"]
mod trainer_conformance;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "upsampler_parity.rs"]
mod upsampler_parity;

#[path = "vae_decode_sweep.rs"]
mod vae_decode_sweep;

#[path = "vae_encode_parity.rs"]
mod vae_encode_parity;
