//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "adapter_parity.rs"]
mod adapter_parity;

#[path = "cfg_gate_equivalence.rs"]
mod cfg_gate_equivalence;

#[path = "conformance.rs"]
mod conformance;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "dit_quant_parity.rs"]
mod dit_quant_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "encoder_cancel.rs"]
mod encoder_cancel;

#[path = "encoder_parity.rs"]
mod encoder_parity;

#[path = "encoder_quant_parity.rs"]
mod encoder_quant_parity;

#[path = "gptoss_attn_parity.rs"]
mod gptoss_attn_parity;

#[path = "gptoss_layer_parity.rs"]
mod gptoss_layer_parity;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "reasoner_parity.rs"]
mod reasoner_parity;

#[path = "schedule_parity.rs"]
mod schedule_parity;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "text_encoder_request_peak_real_weights.rs"]
mod text_encoder_request_peak_real_weights;

#[path = "text_encoder_window_real_weights.rs"]
mod text_encoder_window_real_weights;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "vae_parity.rs"]
mod vae_parity;

#[path = "vae_tiling_inheritance.rs"]
mod vae_tiling_inheritance;
