//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "cpu_golden.rs"]
mod cpu_golden;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "registration.rs"]
mod registration;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "tier_parity.rs"]
mod tier_parity;

#[path = "tier_seam.rs"]
mod tier_seam;

#[path = "vae_parity.rs"]
mod vae_parity;
