#!/usr/bin/env python3
"""One integration-test binary per crate (sc-21383).

Cargo links every `tests/*.rs` file into its own test binary. On the macOS MLX lane that
was 666 integration-test binaries per run, each statically linking the 187 MB libmlx.a:
the link step dominated the lane and `target/` reached 35-38 GB on the hosted runner.

A converted crate sets `autotests = false`, declares a single `[[test]]` target named
`integration` whose entry point is `tests/main.rs`, and `tests/main.rs` declares every
sibling `tests/<name>.rs` as `#[path = "<name>.rs"] mod <name>;`. Test files stay where
they are; cases are addressed as `<name>::<case>` (`cargo test --test integration --
<name>::` replaces the old `--test <name>`).

Shared fixtures: every `tests/<dir>/mod.rs` directory module (`common`, `rung4_support`, ...) is
declared ONCE in `tests/main.rs` (`mod <dir>;`) and the test files say `use crate::<dir>;`
where they used to say `mod <dir>;` -- a
per-file `mod common;` inside a `#[path]`-loaded module would resolve to
`tests/<name>/common.rs`, and `#[path = "common/mod.rs"]` per file trips
`clippy::duplicate_mod`. Anything else shared (e.g. a `#[path]` include of another crate's
support module) goes in the hand-maintained preamble of `tests/main.rs`, between the
`SHARED_BEGIN`/`SHARED_END` markers; `regen` and `check` preserve that block verbatim.

Subcommands:
  convert <crate_dir>...   add the manifest entries and generate `tests/main.rs`
  regen                    regenerate `tests/main.rs` for every converted crate
  check                    pure check: exit 1 if any converted crate's `tests/main.rs`
                           does not match what `regen` would write (a new `tests/<name>.rs`
                           that silently never compiles is the failure this guards)
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MAIN = "main.rs"
TARGET_NAME = "integration"
AUTOTESTS_LINE = "autotests = false"
TEST_TABLE = f'''
# sc-21383: one integration-test binary per crate. `tests/main.rs` is generated by
# scripts/ci/consolidate_integration_tests.py; add a `tests/<name>.rs` file and run
# `python3 scripts/ci/consolidate_integration_tests.py regen`. `cargo test --test integration
# -- <name>::` selects one former per-file target.
[[test]]
name = "{TARGET_NAME}"
path = "tests/{MAIN}"
'''
HEADER = """\
//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.
"""
SHARED_BEGIN = "// --- shared modules (hand-maintained; preserved by regen) ---"
SHARED_END = "// --- generated modules (do not edit) ---"

IDENT = re.compile(r"^[a-z_][a-z0-9_]*$")


def test_dir(crate_dir: Path) -> Path:
    return crate_dir / "tests"


def sibling_test_files(crate_dir: Path) -> list[Path]:
    files = sorted(p for p in test_dir(crate_dir).glob("*.rs") if p.name != MAIN)
    for path in files:
        if not IDENT.match(path.stem):
            raise SystemExit(f"{path}: stem is not a valid module identifier")
    return files


def shared_block(crate_dir: Path) -> str:
    """The hand-maintained block of an existing `tests/main.rs`, or an empty one."""
    main = test_dir(crate_dir) / MAIN
    if main.exists():
        text = main.read_text(encoding="utf-8")
        if SHARED_BEGIN in text and SHARED_END in text:
            start = text.index(SHARED_BEGIN) + len(SHARED_BEGIN)
            end = text.index(SHARED_END)
            return text[start:end]
    return "\n"


def shared_dir_modules(crate_dir: Path) -> list[str]:
    """`tests/<dir>/mod.rs` directory modules (e.g. `common`, `rung4_support`), declared once.

    Fixture directories without a `mod.rs` (`tests/fixtures/`, `tests/parity/`) are data, not
    modules, and are not declared.
    """
    return sorted(
        d.name
        for d in test_dir(crate_dir).iterdir()
        if d.is_dir() and (d / "mod.rs").exists() and IDENT.match(d.name)
    )


def render_main(crate_dir: Path) -> str:
    lines = [HEADER, "\n", SHARED_BEGIN, shared_block(crate_dir), SHARED_END, "\n"]
    for shared in shared_dir_modules(crate_dir):
        # A shared module is compiled even when every module that uses it is `#![cfg]`'d out on
        # this lane (e.g. cuda-only users on Linux), so its items must be allowed to be dead --
        # unless the module already allows that itself, in which case repeating it here trips
        # `clippy::duplicated_attributes`.
        text = (test_dir(crate_dir) / shared / "mod.rs").read_text(encoding="utf-8")
        allow = "" if "#![allow(dead_code)]" in text else "#[allow(dead_code)]\n"
        lines.append(f"\n{allow}mod {shared};\n")
    for path in sibling_test_files(crate_dir):
        lines.append(f'\n#[path = "{path.name}"]\nmod {path.stem};\n')
    return "".join(lines)


def converted_crates() -> list[Path]:
    out = []
    for manifest in ROOT.glob("crates/**/Cargo.toml"):
        if "target" in manifest.parts:
            continue
        text = manifest.read_text(encoding="utf-8")
        if AUTOTESTS_LINE in text and (manifest.parent / "tests" / MAIN).exists():
            out.append(manifest.parent)
    return sorted(out)


def convert(crate_dir: Path) -> None:
    manifest = crate_dir / "Cargo.toml"
    text = manifest.read_text(encoding="utf-8")
    if AUTOTESTS_LINE not in text:
        # `autotests` belongs to `[package]`: insert it as the last key of that table.
        m = re.search(r"^\[package\]\n(?:.*\n)*?(?=^\[|\Z)", text, re.M)
        if m is None:
            raise SystemExit(f"{manifest}: no [package] table")
        end = m.end()
        block = text[:end].rstrip("\n") + f"\n{AUTOTESTS_LINE}\n"
        rest = text[end:]
        text = block + ("\n" + rest if rest and not rest.startswith("\n") else rest)
    if f'name = "{TARGET_NAME}"' not in text:
        text = text.rstrip("\n") + "\n" + TEST_TABLE
    manifest.write_text(text, encoding="utf-8")
    (test_dir(crate_dir) / MAIN).write_text(render_main(crate_dir), encoding="utf-8")


def check_errors() -> list[str]:
    errors = []
    for crate_dir in converted_crates():
        main = test_dir(crate_dir) / MAIN
        want = render_main(crate_dir)
        have = main.read_text(encoding="utf-8")
        if have != want:
            rel = main.relative_to(ROOT)
            missing = [
                p.name
                for p in sibling_test_files(crate_dir)
                if f'#[path = "{p.name}"]' not in have
            ]
            errors.append(
                f"{rel} is stale (missing: {', '.join(missing) or 'none'}; run "
                "`python3 scripts/ci/consolidate_integration_tests.py regen`)"
            )
    return errors


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    conv = sub.add_parser("convert")
    conv.add_argument("crate_dir", nargs="+")
    sub.add_parser("regen")
    sub.add_parser("check")
    args = parser.parse_args(argv)
    if args.cmd == "convert":
        for d in args.crate_dir:
            crate_dir = Path(d).resolve()
            if len(sibling_test_files(crate_dir)) == 0:
                raise SystemExit(f"{crate_dir}: no tests/*.rs to consolidate")
            convert(crate_dir)
            print(f"converted {crate_dir.relative_to(ROOT)}")
        return 0
    if args.cmd == "regen":
        for crate_dir in converted_crates():
            (test_dir(crate_dir) / MAIN).write_text(render_main(crate_dir), encoding="utf-8")
        print(f"regenerated {len(converted_crates())} crates")
        return 0
    errors = check_errors()
    for e in errors:
        print(e, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
