//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "config.rs"]
mod config;

#[path = "convert.rs"]
mod convert;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_empty_negative_real_weights.rs"]
mod e2e_empty_negative_real_weights;

#[path = "e2e_medium_real_weights.rs"]
mod e2e_medium_real_weights;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "e2e_turbo_real_weights.rs"]
mod e2e_turbo_real_weights;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "medium.rs"]
mod medium;

#[path = "medium_transformer.rs"]
mod medium_transformer;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "profile_memory.rs"]
mod profile_memory;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "transformer.rs"]
mod transformer;

#[path = "vae_wiring.rs"]
mod vae_wiring;
