//! sc-18765 — **LTX-2.5 conv video VAE + audio VAE conformance against the shipped 2.3 ports.**
//!
//! Epic 18755 §1.2 claims LTX-2.5's `vae/ltx-2.5-video-vae-conv-bf16` and `vae/ltx-2.5-audio-vae-bf16`
//! are "drop-in reuse" for the ports this crate already ships. "Drop-in" is a claim about **names,
//! shapes and layout**, and nothing in the engine would notice if upstream quietly changed one: a
//! renamed block would surface as a missing-key error at render time on a 42 GB pipeline, and a
//! re-laid-out conv would surface as *plausible garbage*. So the claim is asserted here, key by key,
//! against a committed key-set fixture
//! (`docs/reference/sc-18765-vae-keysets/ltx-vae-keysets.json`, regenerated by
//! `crates/media/mlx-gen/tools/dump_ltx_vae_keysets.py`).
//!
//! These tests need **no weights and no GPU** — the fixture carries the recorded key/shape lists —
//! so they run in ordinary CI. The real-weight round trip lives in `ltx_2_5_vae_real_weights.rs`.
//!
//! ## The structural differences that are real (documented, not absorbed)
//!
//! | | LTX-2.3 all-in-one | LTX-2.5 component file |
//! |---|---|---|
//! | video VAE tensor namespace | `vae.decoder.*` / `vae.encoder.*` | `decoder.*` / `encoder.*` (file root) |
//! | per-channel stats | `vae.per_channel_statistics.{mean,std}-of-means` | same names, at the root |
//! | audio VAE / vocoder namespace | `audio_vae.*` / `vocoder.*` | **identical** |
//! | conv layout on disk | PyTorch (upstream), channels-last in the `ltx-2.3-mlx` rehost | PyTorch |
//! | `latent_log_var` | absent (⇒ `uniform`) | `uniform` (conv) / `constant` (DiffVAE encoder) |
//!
//! Everything else — block lists, `patch_size`, `latent_channels`, `norm_layer`,
//! `spatial_padding_mode`, `timestep_conditioning`, every audio-VAE and vocoder config value, and
//! every tensor name below the namespace — is byte-for-byte the same, which is what makes the reuse
//! legitimate rather than convenient.

use std::collections::{BTreeMap, HashMap};
use std::path::PathBuf;

use mlx_rs::Array;

use mlx_gen::weights::Weights;
use mlx_gen_ltx::config::{LatentLogVar, LtxVaeConfig};
use mlx_gen_ltx::convert::convert_vae_components;

const KEYSETS: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../../../docs/reference/sc-18765-vae-keysets/ltx-vae-keysets.json"
);

// ---------------------------------------------------------------------------------------------
// Fixture access
// ---------------------------------------------------------------------------------------------

fn fixture() -> serde_json::Value {
    let text = std::fs::read_to_string(KEYSETS).unwrap_or_else(|e| {
        panic!("read {KEYSETS}: {e} (regenerate with tools/dump_ltx_vae_keysets.py)")
    });
    serde_json::from_str(&text).expect("parse ltx-vae-keysets.json")
}

fn component(fixture: &serde_json::Value, name: &str) -> serde_json::Value {
    fixture
        .get("components")
        .and_then(|c| c.get(name))
        .unwrap_or_else(|| panic!("fixture component {name} missing"))
        .clone()
}

/// `{tensor name -> shape}` for one fixture component.
fn tensors(fixture: &serde_json::Value, name: &str) -> BTreeMap<String, Vec<i32>> {
    component(fixture, name)
        .get("tensors")
        .and_then(serde_json::Value::as_object)
        .unwrap_or_else(|| panic!("fixture component {name} has no tensors"))
        .iter()
        .map(|(k, v)| {
            let shape = v
                .as_array()
                .expect("shape array")
                .iter()
                .map(|d| d.as_i64().expect("shape dim") as i32)
                .collect();
            (k.clone(), shape)
        })
        .collect()
}

fn config_of(fixture: &serde_json::Value, name: &str) -> serde_json::Value {
    component(fixture, name)
        .get("config")
        .unwrap_or_else(|| panic!("fixture component {name} has no config"))
        .clone()
}

/// Report a set difference as a sorted, readable list (empty ⇒ `[]`).
fn missing(from: &BTreeMap<String, Vec<i32>>, against: &BTreeMap<String, Vec<i32>>) -> Vec<String> {
    from.keys()
        .filter(|k| !against.contains_key(*k))
        .cloned()
        .collect()
}

// ---------------------------------------------------------------------------------------------
// 1. Key names: the 2.5 component files carry exactly the 2.3 components' tensors
// ---------------------------------------------------------------------------------------------

/// The 2.3 split-MLX key a 2.5 conv-VAE key maps to, per half — the mapping
/// `convert::sanitize_vae_{decoder,encoder}` implements. `None` ⇒ the key belongs to the other half.
fn video_key_for_half(key: &str, half: &str) -> Option<String> {
    match key {
        "per_channel_statistics.mean-of-means" => Some(if half == "decoder" {
            "per_channel_statistics.mean".into()
        } else {
            "per_channel_statistics._mean_of_means".into()
        }),
        "per_channel_statistics.std-of-means" => Some(if half == "decoder" {
            "per_channel_statistics.std".into()
        } else {
            "per_channel_statistics._std_of_means".into()
        }),
        _ => key.strip_prefix(&format!("{half}.")).map(str::to_string),
    }
}

#[test]
fn conv_vae_component_carries_exactly_the_2_3_split_key_sets() {
    let fx = fixture();
    let conv = tensors(&fx, "ltx_2_5_video_vae_conv");
    for (half, component_name) in [
        ("decoder", "ltx_2_3_mlx_vae_decoder"),
        ("encoder", "ltx_2_3_mlx_vae_encoder"),
    ] {
        let want = tensors(&fx, component_name);
        let got: BTreeMap<String, Vec<i32>> = conv
            .iter()
            .filter_map(|(k, v)| video_key_for_half(k, half).map(|nk| (nk, v.clone())))
            .collect();
        assert_eq!(
            missing(&got, &want),
            Vec::<String>::new(),
            "LTX-2.5 {half} tensors absent from the shipped 2.3 {component_name} port"
        );
        assert_eq!(
            missing(&want, &got),
            Vec::<String>::new(),
            "shipped 2.3 {component_name} tensors absent from the LTX-2.5 {half}"
        );
        assert_eq!(
            got.len(),
            want.len(),
            "{half}: 2.5 supplies {} tensors, the 2.3 port consumes {}",
            got.len(),
            want.len()
        );
    }
}

/// The 2.3 split-MLX key a 2.5 audio-VAE key maps to (`convert::sanitize_audio_vae` /
/// `sanitize_vocoder`), and which component it lands in.
fn audio_key(key: &str) -> Option<(&'static str, String)> {
    if let Some(rest) = key.strip_prefix("audio_vae.decoder.") {
        return Some(("audio_vae", rest.to_string()));
    }
    if let Some(stat) = key.strip_prefix("audio_vae.per_channel_statistics.") {
        return match stat {
            "mean-of-means" => Some(("audio_vae", "per_channel_statistics._mean_of_means".into())),
            "std-of-means" => Some(("audio_vae", "per_channel_statistics._std_of_means".into())),
            _ => None,
        };
    }
    if key.starts_with("vocoder.") {
        // The reference strips EVERY `vocoder.` occurrence, not just the leading one.
        return Some(("vocoder", key.replace("vocoder.", "")));
    }
    None
}

#[test]
fn audio_vae_and_vocoder_components_carry_exactly_the_2_3_key_sets() {
    let fx = fixture();
    let audio = tensors(&fx, "ltx_2_5_audio_vae");
    let mut mapped: HashMap<&str, BTreeMap<String, Vec<i32>>> = HashMap::new();
    let mut unmapped: Vec<&String> = Vec::new();
    for (k, v) in &audio {
        match audio_key(k) {
            Some((component, nk)) => {
                mapped.entry(component).or_default().insert(nk, v.clone());
            }
            // The 2.3 audio path drops the audio VAE's ENCODER (the pipeline only ever decodes),
            // so those keys are expected to be unconsumed — see the assertion below.
            None => unmapped.push(k),
        }
    }
    assert!(
        unmapped.iter().all(|k| k.starts_with("audio_vae.encoder.")),
        "LTX-2.5 audio VAE carries tensors the 2.3 mapping does not recognise: {:?}",
        unmapped
            .iter()
            .filter(|k| !k.starts_with("audio_vae.encoder."))
            .collect::<Vec<_>>()
    );
    assert_eq!(
        unmapped.len(),
        44,
        "the audio VAE encoder is 44 tensors in both 2.3 and 2.5; a change here means the audio \
         encoder was restructured"
    );

    for (component, fixture_name) in [
        ("audio_vae", "ltx_2_3_mlx_audio_vae"),
        ("vocoder", "ltx_2_3_mlx_vocoder"),
    ] {
        let want = tensors(&fx, fixture_name);
        let got = mapped.remove(component).unwrap_or_default();
        assert_eq!(
            missing(&got, &want),
            Vec::<String>::new(),
            "LTX-2.5 {component} tensors absent from the shipped 2.3 port"
        );
        assert_eq!(
            missing(&want, &got),
            Vec::<String>::new(),
            "shipped 2.3 {component} tensors absent from LTX-2.5"
        );
    }
}

// ---------------------------------------------------------------------------------------------
// 2. Layout: the recorded 2.5 shapes are the PyTorch pre-image of the shipped channels-last ones
// ---------------------------------------------------------------------------------------------

fn permute(shape: &[i32], axes: &[usize]) -> Vec<i32> {
    axes.iter().map(|&a| shape[a]).collect()
}

/// The channels-last shape `convert::conv_channels_last` produces for a video/audio VAE tensor:
/// Conv3d `[O,I,D,H,W] -> [O,D,H,W,I]`, Conv2d `[O,I,H,W] -> [O,H,W,I]`, gated on `conv`+`weight`.
fn vae_channels_last(key: &str, shape: &[i32]) -> Vec<i32> {
    if !(key.to_ascii_lowercase().contains("conv") && key.contains("weight")) {
        return shape.to_vec();
    }
    match shape.len() {
        5 => permute(shape, &[0, 2, 3, 4, 1]),
        4 => permute(shape, &[0, 2, 3, 1]),
        _ => shape.to_vec(),
    }
}

/// `convert::sanitize_vocoder`'s rank-3 transposes, gated on `weight` (NOT on `conv`):
/// `ups` ConvTranspose1d `[I,O,K] -> [O,K,I]`, every other Conv1d `[O,I,K] -> [O,K,I]`.
fn vocoder_channels_last(key: &str, shape: &[i32]) -> Vec<i32> {
    if key.contains("weight") && shape.len() == 3 {
        if key.contains("ups") {
            permute(shape, &[1, 2, 0])
        } else {
            permute(shape, &[0, 2, 1])
        }
    } else {
        shape.to_vec()
    }
}

#[test]
fn recorded_2_5_shapes_are_the_pytorch_preimage_of_the_shipped_channels_last_shapes() {
    let fx = fixture();
    let conv = tensors(&fx, "ltx_2_5_video_vae_conv");
    let mut checked = 0usize;
    for (half, fixture_name) in [
        ("decoder", "ltx_2_3_mlx_vae_decoder"),
        ("encoder", "ltx_2_3_mlx_vae_encoder"),
    ] {
        let want = tensors(&fx, fixture_name);
        for (k, shape) in &conv {
            let Some(nk) = video_key_for_half(k, half) else {
                continue;
            };
            let expected = &want[&nk];
            assert_eq!(
                &vae_channels_last(&nk, shape),
                expected,
                "{half} {nk}: LTX-2.5 stores {shape:?}, which does not transpose to the shipped \
                 {expected:?}"
            );
            checked += 1;
        }
    }

    let audio = tensors(&fx, "ltx_2_5_audio_vae");
    let want_audio = tensors(&fx, "ltx_2_3_mlx_audio_vae");
    let want_voc = tensors(&fx, "ltx_2_3_mlx_vocoder");
    for (k, shape) in &audio {
        match audio_key(k) {
            Some(("audio_vae", nk)) => {
                assert_eq!(
                    &vae_channels_last(&nk, shape),
                    &want_audio[&nk],
                    "audio {nk}"
                );
                checked += 1;
            }
            Some(("vocoder", nk)) => {
                assert_eq!(
                    &vocoder_channels_last(&nk, shape),
                    &want_voc[&nk],
                    "vocoder {nk}"
                );
                checked += 1;
            }
            _ => {}
        }
    }
    // Guard the loop itself: a mapping helper that silently returned `None` everywhere would make
    // every assertion above vacuous.
    assert_eq!(
        checked,
        86 + 86 + 58 + 1227,
        "expected every shipped 2.3 tensor to be shape-checked against its 2.5 source"
    );
}

// ---------------------------------------------------------------------------------------------
// 3. Config: block lists and audio/vocoder values are unchanged; only `latent_log_var` differs
// ---------------------------------------------------------------------------------------------

#[test]
fn conv_vae_config_block_lists_match_the_shipped_2_3_structure() {
    let fx = fixture();
    let vae = config_of(&fx, "ltx_2_5_video_vae_conv");
    let vae = vae.get("vae").expect("config.vae");
    let cfg = LtxVaeConfig::from_embedded_vae(vae).expect("parse the 2.5 conv VAE config");
    let base = LtxVaeConfig::defaults();

    assert_eq!(cfg.latent_channels, base.latent_channels);
    assert_eq!(cfg.patch_size, base.patch_size);
    assert_eq!(cfg.timestep_conditioning, base.timestep_conditioning);
    assert_eq!(cfg.spatial_padding_mode, base.spatial_padding_mode);
    assert_eq!(
        cfg.encoder_blocks, base.encoder_blocks,
        "2.5 encoder_blocks diverged from the shipped 2.3 block list"
    );
    assert_eq!(
        cfg.decoder_blocks, base.decoder_blocks,
        "2.5 decoder_blocks diverged from the shipped 2.3 block list"
    );
    assert_eq!(
        vae.get("_class_name").and_then(serde_json::Value::as_str),
        Some("CausalVideoAutoencoder")
    );
    assert_eq!(
        vae.get("norm_layer").and_then(serde_json::Value::as_str),
        Some("pixel_norm")
    );
    assert_eq!(cfg.latent_log_var, LatentLogVar::Uniform);
}

#[test]
fn audio_vae_and_vocoder_configs_are_unchanged_from_2_3() {
    let fx = fixture();
    let cfg = config_of(&fx, "ltx_2_5_audio_vae");
    let dd = cfg
        .pointer("/audio_vae/model/params/ddconfig")
        .expect("audio_vae ddconfig");
    let audio = mlx_gen_ltx::config::AudioVaeConfig::from_ddconfig(dd);
    assert_eq!(
        audio,
        mlx_gen_ltx::config::AudioVaeConfig::defaults(),
        "the 2.5 audio VAE structure diverged from the shipped 2.3 one"
    );
    assert_eq!(
        cfg.pointer("/audio_vae/model/params/sampling_rate")
            .and_then(serde_json::Value::as_i64),
        Some(16_000),
        "the audio VAE latent rate is what the vocoder's BWE stage keys off"
    );

    let vocoder =
        mlx_gen_ltx::config::VocoderConfig::from_embedded_vocoder(cfg.get("vocoder").unwrap());
    assert!(vocoder.bwe.is_some(), "2.5 still ships the BWE stage");
    assert!(vocoder.core.is_bigvgan(), "2.5 core is still BigVGAN");
    assert!(vocoder.core.stereo && vocoder.bwe.as_ref().unwrap().stereo);
    assert_eq!(vocoder.core.upsample_rates, vec![5, 2, 2, 2, 2, 2]);
    assert_eq!(vocoder.core.upsample_initial_channel, 1536);
    assert_eq!(vocoder.bwe_input_sample_rate, 16_000);
    assert_eq!(vocoder.bwe_output_sample_rate, 48_000);
    assert_eq!(vocoder.final_sample_rate(), 48_000);
}

/// The DiffVAE (`CausalDiffusionVAE`) reuses the conv VAE's **encoder module verbatim** — same
/// tensor names, same shapes, right down to the 129-channel `conv_out` head — and differs only in
/// the declared `latent_log_var`. That is the whole reason a conv-VAE-only 2.5 build is viable.
#[test]
fn diffvae_encoder_is_the_conv_encoder_with_only_the_logvar_mode_changed() {
    let fx = fixture();
    let conv = tensors(&fx, "ltx_2_5_video_vae_conv");
    let diff = tensors(&fx, "ltx_2_5_video_vae_diffusion");
    let conv_enc: BTreeMap<_, _> = conv
        .iter()
        .filter(|(k, _)| k.starts_with("encoder.") || k.starts_with("per_channel_statistics."))
        .map(|(k, v)| (k.clone(), v.clone()))
        .collect();
    assert_eq!(
        conv_enc, diff,
        "the DiffVAE's encoder is no longer tensor-identical to the conv VAE's"
    );
    assert_eq!(
        conv_enc["encoder.conv_out.conv.weight"],
        vec![129, 1024, 3, 3, 3],
        "both modes emit latent_channels + 1 = 129 conv_out channels"
    );

    let diff_cfg = config_of(&fx, "ltx_2_5_video_vae_diffusion");
    let diff_vae = diff_cfg.get("vae").expect("config.vae");
    let parsed =
        LtxVaeConfig::from_embedded_vae(diff_vae).expect("parse the nested DiffVAE config");
    assert_eq!(parsed.latent_log_var, LatentLogVar::Constant);
    assert_eq!(parsed.latent_channels, 128, "nested `encoder.out_channels`");
    assert_eq!(parsed.patch_size, 4);
    assert_eq!(
        parsed.encoder_blocks,
        LtxVaeConfig::defaults().encoder_blocks,
        "the DiffVAE encoder's `blocks` list diverged from the conv encoder's"
    );
    assert_eq!(
        diff_vae
            .pointer("/decoder/_class_name")
            .and_then(serde_json::Value::as_str),
        Some("NADiffusionDecoder"),
        "the DiffVAE decoder is a different architecture (sc-18766 / sc-18767), not this port's"
    );
    // Recorded but unused: the reference's CONSTANT branch fills the log-variance with a hardcoded
    // `approx_ln_0 = -30`, never with this value. Asserted so a future upstream change that starts
    // honouring it cannot pass unnoticed.
    assert_eq!(
        diff_vae
            .pointer("/encoder/latent_log_var_value")
            .and_then(serde_json::Value::as_f64),
        Some(-7.824046010856292)
    );
}

/// Both log-variance widths are declared, and a mode that disagrees with the checkpoint's
/// `conv_out` width is a load error rather than a silently mis-sliced latent.
#[test]
fn latent_log_var_modes_declare_their_conv_out_widths() {
    assert_eq!(LatentLogVar::Uniform.conv_out_channels(128), 129);
    assert_eq!(LatentLogVar::Constant.conv_out_channels(128), 129);
    assert_eq!(LatentLogVar::PerChannel.conv_out_channels(128), 256);
    assert_eq!(LatentLogVar::None.conv_out_channels(128), 128);
    assert!(LatentLogVar::parse("gaussian").is_err());
    for (s, want) in [
        ("uniform", LatentLogVar::Uniform),
        ("constant", LatentLogVar::Constant),
        ("per_channel", LatentLogVar::PerChannel),
        ("none", LatentLogVar::None),
    ] {
        assert_eq!(LatentLogVar::parse(s).unwrap(), want);
    }
}

// ---------------------------------------------------------------------------------------------
// 4. The converter, end to end, on synthetic checkpoints shaped like the real ones
// ---------------------------------------------------------------------------------------------

/// A rank-preserving stand-in for a recorded tensor: the sanitizers only ever look at a tensor's
/// RANK (to pick a transpose), so a 2-per-axis dummy exercises exactly the same code path at a
/// millionth of the bytes.
fn dummy(shape: &[i32]) -> Array {
    let dims: Vec<i32> = shape.iter().map(|_| 2).collect();
    let n: i32 = dims.iter().product();
    Array::from_slice(&(0..n).map(|i| i as f32).collect::<Vec<_>>(), &dims)
}

/// Write a synthetic component checkpoint carrying the fixture's key set and the fixture's config.
fn synthetic_component(
    dir: &std::path::Path,
    file: &str,
    keys: &BTreeMap<String, Vec<i32>>,
    config: &serde_json::Value,
) -> PathBuf {
    let arrays: Vec<(String, Array)> = keys.iter().map(|(k, s)| (k.clone(), dummy(s))).collect();
    let metadata: HashMap<String, String> = HashMap::from([
        ("config".to_string(), config.to_string()),
        ("model_version".to_string(), "2.5.0".to_string()),
    ]);
    let path = dir.join(file);
    Array::save_safetensors(
        arrays.iter().map(|(k, v)| (k.as_str(), v)),
        Some(&metadata),
        &path,
    )
    .expect("write synthetic component");
    path
}

fn keys_of(path: &std::path::Path) -> BTreeMap<String, Vec<i32>> {
    let w = Weights::from_file(path).expect("read emitted component");
    let names: Vec<String> = w.keys().map(str::to_string).collect();
    names
        .into_iter()
        .map(|k| {
            let shape = w.require(&k).expect("emitted key").shape().to_vec();
            (k, shape)
        })
        .collect()
}

#[test]
fn convert_vae_components_emits_the_2_3_component_key_sets_from_2_5_inputs() {
    let fx = fixture();
    let tmp = tempfile::tempdir().unwrap();
    let src = tmp.path().join("src");
    std::fs::create_dir_all(&src).unwrap();

    let video = synthetic_component(
        &src,
        "ltx-2.5-video-vae-conv-bf16.safetensors",
        &tensors(&fx, "ltx_2_5_video_vae_conv"),
        &config_of(&fx, "ltx_2_5_video_vae_conv"),
    );
    let audio = synthetic_component(
        &src,
        "ltx-2.5-audio-vae-bf16.safetensors",
        &tensors(&fx, "ltx_2_5_audio_vae"),
        &config_of(&fx, "ltx_2_5_audio_vae"),
    );

    let out = tmp.path().join("split");
    let mut components = convert_vae_components(&video, Some(&audio), &out).expect("convert");
    components.sort();
    assert_eq!(
        components,
        vec!["audio_vae", "vae_decoder", "vae_encoder", "vocoder"]
    );

    for (component, fixture_name) in [
        ("vae_decoder", "ltx_2_3_mlx_vae_decoder"),
        ("vae_encoder", "ltx_2_3_mlx_vae_encoder"),
        ("audio_vae", "ltx_2_3_mlx_audio_vae"),
        ("vocoder", "ltx_2_3_mlx_vocoder"),
    ] {
        let got = keys_of(&out.join(format!("{component}.safetensors")));
        let want = tensors(&fx, fixture_name);
        assert_eq!(
            got.keys().cloned().collect::<Vec<_>>(),
            want.keys().cloned().collect::<Vec<_>>(),
            "converted {component} key set differs from the shipped 2.3 component"
        );
    }

    // The emitted sidecar must be directly loadable by the shipped config readers — that is what
    // makes the output dir a drop-in model dir for the existing ports.
    let cfg = LtxVaeConfig::from_model_dir(&out).expect("emitted embedded_config.json");
    assert_eq!(cfg.latent_log_var, LatentLogVar::Uniform);
    assert_eq!(cfg.encoder_blocks, LtxVaeConfig::defaults().encoder_blocks);
    let voc = mlx_gen_ltx::config::VocoderConfig::from_model_dir(&out).expect("vocoder config");
    assert_eq!(voc.final_sample_rate(), 48_000);
    let av = mlx_gen_ltx::config::AudioVaeConfig::from_model_dir(&out).expect("audio vae config");
    assert_eq!(av, mlx_gen_ltx::config::AudioVaeConfig::defaults());
}

/// The DiffVAE file shares the conv encoder, so the converter emits that encoder — and **refuses to
/// emit a `vae_decoder`**, because its decoder is an `NADiffusionDecoder`. Without this branch the
/// output dir would load through `LtxVideoVae` and render garbage.
#[test]
fn convert_vae_components_takes_only_the_encoder_from_a_diffvae_file() {
    let fx = fixture();
    let tmp = tempfile::tempdir().unwrap();
    let video = synthetic_component(
        tmp.path(),
        "ltx-2.5-video-vae-bf16.safetensors",
        &tensors(&fx, "ltx_2_5_video_vae_diffusion"),
        &config_of(&fx, "ltx_2_5_video_vae_diffusion"),
    );
    let out = tmp.path().join("split");
    let components =
        convert_vae_components(&video, None::<&std::path::Path>, &out).expect("convert diffvae");
    assert_eq!(components, vec!["vae_encoder"]);
    assert!(
        !out.join("vae_decoder.safetensors").exists(),
        "a conv `vae_decoder` must never be emitted from a CausalDiffusionVAE checkpoint"
    );
    let got = keys_of(&out.join("vae_encoder.safetensors"));
    let want = tensors(&fx, "ltx_2_3_mlx_vae_encoder");
    assert_eq!(
        got.keys().cloned().collect::<Vec<_>>(),
        want.keys().cloned().collect::<Vec<_>>()
    );
    let cfg = LtxVaeConfig::from_model_dir(&out).expect("emitted embedded_config.json");
    assert_eq!(cfg.latent_log_var, LatentLogVar::Constant);
}

/// An unknown VAE class is refused rather than converted on the assumption it is conv-shaped.
#[test]
fn convert_vae_components_refuses_an_unknown_vae_class() {
    let fx = fixture();
    let tmp = tempfile::tempdir().unwrap();
    let mut config = config_of(&fx, "ltx_2_5_video_vae_conv");
    config["vae"]["_class_name"] = serde_json::Value::String("SomeFutureVAE".into());
    let video = synthetic_component(
        tmp.path(),
        "future-vae.safetensors",
        &tensors(&fx, "ltx_2_5_video_vae_conv"),
        &config,
    );
    let err = convert_vae_components(&video, None::<&std::path::Path>, tmp.path().join("split"))
        .expect_err("an unknown VAE class must not convert");
    assert!(
        format!("{err}").contains("SomeFutureVAE"),
        "the refusal must name the class it saw, got: {err}"
    );
}
