//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "audio_vae_parity.rs"]
mod audio_vae_parity;

#[path = "av_dit_parity.rs"]
mod av_dit_parity;

#[path = "av_e2e_parity.rs"]
mod av_e2e_parity;

#[path = "av_lora_e2e_parity.rs"]
mod av_lora_e2e_parity;

#[path = "bf16_sdpa_bug.rs"]
mod bf16_sdpa_bug;

#[path = "block_parity.rs"]
mod block_parity;

#[path = "build_bf16_tier.rs"]
mod build_bf16_tier;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "connector_parity.rs"]
mod connector_parity;

#[path = "convert_parity.rs"]
mod convert_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "duration_head_golden.rs"]
mod duration_head_golden;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "enhance_parity.rs"]
mod enhance_parity;

#[path = "gemma_parity.rs"]
mod gemma_parity;

#[path = "gemma_tokenizer.rs"]
mod gemma_tokenizer;

#[path = "i2v_parity.rs"]
mod i2v_parity;

#[path = "keyframe_cond_parity.rs"]
mod keyframe_cond_parity;

#[path = "lora_real_weights.rs"]
mod lora_real_weights;

#[path = "ltx_2_5_diffvae_parity.rs"]
mod ltx_2_5_diffvae_parity;

#[path = "ltx_2_5_tiers_real_weights.rs"]
mod ltx_2_5_tiers_real_weights;

#[path = "ltx_2_5_vae_conformance.rs"]
mod ltx_2_5_vae_conformance;

#[path = "ltx_2_5_vae_real_weights.rs"]
mod ltx_2_5_vae_real_weights;

#[path = "perf.rs"]
mod perf;

#[path = "pipeline_parity.rs"]
mod pipeline_parity;

#[path = "registration.rs"]
mod registration;

#[path = "replace_mask_parity.rs"]
mod replace_mask_parity;

#[path = "s0_parity.rs"]
mod s0_parity;

#[path = "sc18758_ff_bias_keyframes_conformance.rs"]
mod sc18758_ff_bias_keyframes_conformance;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "split_checkpoint.rs"]
mod split_checkpoint;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "upsampler_parity.rs"]
mod upsampler_parity;

#[path = "vae_decode_sweep.rs"]
mod vae_decode_sweep;

#[path = "vae_decode_tiling_parity.rs"]
mod vae_decode_tiling_parity;

#[path = "vae_parity.rs"]
mod vae_parity;

#[path = "vocoder_parity.rs"]
mod vocoder_parity;
