//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "accel_real_weights.rs"]
mod accel_real_weights;

#[path = "cfgpp_real_weights.rs"]
mod cfgpp_real_weights;

#[path = "compile_micro.rs"]
mod compile_micro;

#[path = "controlnet_real_weights.rs"]
mod controlnet_real_weights;

#[path = "decode_quality_admission.rs"]
mod decode_quality_admission;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "img2img_real_weights.rs"]
mod img2img_real_weights;

#[path = "inpaint_real_weights.rs"]
mod inpaint_real_weights;

#[path = "instantid_convert_smoke.rs"]
mod instantid_convert_smoke;

#[path = "instantid_resampler_real_weights.rs"]
mod instantid_resampler_real_weights;

#[path = "ip_adapter_decoupled.rs"]
mod ip_adapter_decoupled;

#[path = "ip_adapter_real_weights.rs"]
mod ip_adapter_real_weights;

#[path = "lokr_real_weights.rs"]
mod lokr_real_weights;

#[path = "lora_complete_real_weights.rs"]
mod lora_complete_real_weights;

#[path = "lora_real_weights.rs"]
mod lora_real_weights;

#[path = "memory_ladder_real_weights.rs"]
mod memory_ladder_real_weights;

#[path = "perf.rs"]
mod perf;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "q8_1024_probe.rs"]
mod q8_1024_probe;

#[path = "quant_real_weights.rs"]
mod quant_real_weights;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "text_encoder_real_weights.rs"]
mod text_encoder_real_weights;

#[path = "thirdparty_lycoris_real_weights.rs"]
mod thirdparty_lycoris_real_weights;

#[path = "tokenizer_real_weights.rs"]
mod tokenizer_real_weights;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "unet_fp16_real_weights.rs"]
mod unet_fp16_real_weights;

#[path = "unet_real_weights.rs"]
mod unet_real_weights;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;

#[path = "vae_real_weights.rs"]
mod vae_real_weights;
