//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "decode_parity.rs"]
mod decode_parity;

#[path = "depthwise_conv_gpu.rs"]
mod depthwise_conv_gpu;

#[path = "encode_parity.rs"]
mod encode_parity;

#[path = "nvfp4_sana_dit_gpu.rs"]
mod nvfp4_sana_dit_gpu;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "preview_wiring.rs"]
mod preview_wiring;

#[path = "sprint_scm.rs"]
mod sprint_scm;

#[path = "text_encoder.rs"]
mod text_encoder;

#[path = "transformer_parity.rs"]
mod transformer_parity;
