//! Shared loaders for the committed protocol fixtures (`tests/fixtures/protocol/`, generated by
//! `scripts/reference/yue2/protocol_fixtures.py` from the pinned upstream).

use std::path::PathBuf;
use std::sync::OnceLock;

use serde_json::Value;

use crate::tokenizer::Yue2TextTokenizer;

/// The fixture directory.
pub(crate) fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/protocol")
}

/// A fixture JSON file, parsed.
pub(crate) fn json(name: &str) -> Value {
    let path = dir().join(name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("{}: {e}", path.display()))
}

/// The tokenizer over the committed synthetic rank table (the stand-in for `qwen.tiktoken`).
pub(crate) fn synthetic() -> &'static Yue2TextTokenizer {
    static TOKENIZER: OnceLock<Yue2TextTokenizer> = OnceLock::new();
    TOKENIZER.get_or_init(|| {
        let bytes = std::fs::read(dir().join("synthetic.tiktoken")).expect("synthetic.tiktoken");
        Yue2TextTokenizer::from_partial_ranks_for_tests(&bytes).expect("synthetic table parses")
    })
}

/// Token IDs from a fixture array.
pub(crate) fn ids(value: &Value) -> Vec<u32> {
    value
        .as_array()
        .unwrap_or_else(|| panic!("not an id array: {value}"))
        .iter()
        .map(|v| u32::try_from(v.as_u64().expect("id")).expect("u32 id"))
        .collect()
}

/// Fixture floats that JSON cannot hold are written `{"float": "nan" | "inf" | "-inf"}`:
/// `Some(f)` when `value` is a `{"float": ...}` marker.
pub(crate) fn float_of(value: &Value) -> Option<f64> {
    let name = value.as_object()?.get("float")?.as_str()?;
    Some(match name {
        "nan" => f64::NAN,
        "inf" => f64::INFINITY,
        "-inf" => f64::NEG_INFINITY,
        other => panic!("unknown float marker {other}"),
    })
}

/// JSON equality with numbers compared by value (Python writes `0` where Rust writes `0.0`).
pub(crate) fn same(a: &Value, b: &Value) -> bool {
    match (a, b) {
        (Value::Number(x), Value::Number(y)) => x.as_f64() == y.as_f64(),
        (Value::Array(x), Value::Array(y)) => {
            x.len() == y.len() && x.iter().zip(y).all(|(a, b)| same(a, b))
        }
        (Value::Object(x), Value::Object(y)) => {
            x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).is_some_and(|w| same(v, w)))
        }
        _ => a == b,
    }
}
