//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "comfyui_real_weights.rs"]
mod comfyui_real_weights;

#[path = "conformance.rs"]
mod conformance;

#[path = "control_vram_probe.rs"]
mod control_vram_probe;

#[path = "packed_tier_validate.rs"]
mod packed_tier_validate;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "request_scoped_residency_shape.rs"]
mod request_scoped_residency_shape;

#[path = "sequential_vram_probe.rs"]
mod sequential_vram_probe;

#[path = "trainer_conformance.rs"]
mod trainer_conformance;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;
