set -o pipefail
run_one() {
  local name="$1"
  local out
  out="$(cargo test --locked --release -p candle-audio-moss-tts-realtime --test conformance \
    "$name" -- --exact --ignored --nocapture 2>&1 | tee /dev/stderr)"
  if ! grep -qE "test result: ok\. 1 passed" <<<"$out"; then
    echo "::error::'$name' did not run exactly one passing test — a rename would make this step vacuously green" >&2
    return 1
  fi
}
# Codec-only (no AR): the RLFQ decode path turns synthetic in-range codes into a non-silent
# 1920-samples-per-frame waveform. Isolates a codec-decode bug from an AR->codec mapping bug.
run_one codec_only_decodes_synthetic_frames
# FULLY GATED as of sc-17270. Both halves run with no provisioning: the self-contained
# decode -> encode -> decode round-trip (reconstruction correlation, non-silent) AND the
# reference-parity arm comparing this port's encode against the reference PyTorch
# `codec.encode` across all 16 codebooks. That arm used to sit behind
# `if let Ok(MOSS_CODEC_CLIP), Ok(MOSS_CODEC_REF_CODES)` with neither variable set
# anywhere in the repo, so it took the `else` branch, printed "SKIPPED", and still
# reported `1 passed` — a false green the run-count assertion could not see, the same
# shape sc-17250 fixed in joycaption.rs one level further out. Both now default to a
# committed fixture (`crates/audio/candle-audio-moss-tts-realtime/tests/fixtures/`,
# regenerated by `scripts/reference/moss_audio_codec_reference.py`); the variables
# survive only as an override for a different clip. Nothing to provision here.
run_one moss_audio_codec_encode_roundtrip_and_reference
# The sc-14181 DoD: chunked/streaming encode reproduces single-shot codes exactly (0/6400
# differing at both chunk durations) AND bounds the first stage's quadratic attention.
# Was unwired while its memory half sampled `ps -o rss=` on a 5 ms timer — a wall-clock
# proxy for a transient, so a faster box caught less of the spike and the gate's verdict
# tracked machine speed (it read 291 MB of a 1669 MB spike here and failed a >200 MB bar).
# sc-17263 moved that half to an allocator high-water mark: +68 MB chunked vs +1669 MB
# single-shot, and it goes RED when `forward_chunked` is degraded to the unbounded
# `forward` (which the identity half alone does NOT catch). The bounds carry deliberate
# headroom over those dev-box figures — this runner is not that box, and rayon scratch
# scales with core count.
# KEEP THIS LANE FEATURELESS. The memory half counts HEAP, so it REFUSES to run when the
# codec loads onto a non-CPU device — it asserts rather than skipping, precisely so it
# cannot go green while measuring nothing (sc-17270's rule, gated by
# scripts/tests/test_moss_audio_codec_reference.py). Adding `--features metal` here turns
# this step RED with an explanatory message rather than silently dropping the coverage.
run_one moss_audio_codec_chunked_encode_matches_single_shot
# AR stage: a fixed text + seed emits >= 2 real 16-codebook RVQ frames, every token in
# [0, 1027), deterministic run-to-run and non-degenerate. A broken backbone / weight mapping /
# RoPE / multi-embedding sum / local-transformer head would fail here.
run_one moss_tts_realtime_emits_valid_rvq_frames
# The AR loop is genuinely incremental: time-to-first-frame is materially below time-to-budget.
run_one moss_tts_realtime_is_incremental
# The sc-13334 streaming acceptance gate through the REAL registered provider: >= 2 PCM chunks
# before completion, concat(chunks) byte-identical to one-shot generate(), a valid non-silent
# 24 kHz mono track, and first-chunk latency below full-generation latency.
run_one moss_tts_realtime_streaming_gate
# sc-13433 text fidelity: a curated prompt set is synthesized and transcribed back with
# whisper_base; each transcript must match within a CER bound (and the metric must
# discriminate — an unrelated reference does NOT pass the same bound). This is the regression
# gate for the pre-sc-13433 spurious early-EOS failure.
run_one moss_tts_realtime_asr_roundtrip_fidelity
# sc-14150/14151 multi-turn: one warm core across turns. Cross-turn speaker continuity is
# measured with the Chatterbox CAMPPlus x-vector encoder; the user-context arm proves a later
# turn actually conditions on the earlier one.
run_one moss_tts_realtime_multi_turn_conversation
run_one moss_tts_realtime_multi_turn_user_context
# sc-14149/sc-14151 voice cloning, wired by sc-17264. Both condition on a committed
# reference clip (`tests/fixtures/moss_voiceclone_ref_clip.f32`, rendered by Kokoro),
# so `MOSS_VOICECLONE_REF` no longer has to be provisioned — it only overrides.
# Single-turn: the cloned and default renders are both intelligible (Whisper CER), differ
# from each other, and the clone's CAMPPlus x-vector resembles the reference MORE than the
# default voice does. Measured on an M5 Max: clone<->ref 0.912 vs default<->ref 0.719.
run_one moss_tts_realtime_voice_clone
# Multi-turn: the sc-14151 DoD that the clone is held across the WHOLE conversation, not
# just turn 0 — every turn must carry the reference speaker more than the default voice,
# and the turns must be mutually the same speaker. Measured: turn0 0.837 vs 0.555,
# turn1 0.883 vs 0.621, cross-turn 0.870.
run_one moss_tts_realtime_multi_turn_voice_clone
