//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "cuda_1024.rs"]
mod cuda_1024;

#[path = "edit_parity.rs"]
mod edit_parity;

#[path = "memory_ladder_real_weights.rs"]
mod memory_ladder_real_weights;

#[path = "quant_real_weights.rs"]
mod quant_real_weights;

#[path = "real_parity.rs"]
mod real_parity;

#[path = "trainer_cuda_smoke.rs"]
mod trainer_cuda_smoke;
