//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "adapter_routing.rs"]
mod adapter_routing;

#[path = "approximator_parity.rs"]
mod approximator_parity;

#[path = "auxiliary_pack_identity.rs"]
mod auxiliary_pack_identity;

#[path = "auxiliary_tier_comparison.rs"]
mod auxiliary_tier_comparison;

#[path = "decode_quality_admission.rs"]
mod decode_quality_admission;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "memory_ladder_real_weights.rs"]
mod memory_ladder_real_weights;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "registry.rs"]
mod registry;

#[path = "text_mask_parity.rs"]
mod text_mask_parity;

#[path = "transformer_parity.rs"]
mod transformer_parity;

#[path = "vae_tiling_inheritance.rs"]
mod vae_tiling_inheritance;
