//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "bench_phases.rs"]
mod bench_phases;

#[path = "cancellation_conformance.rs"]
mod cancellation_conformance;

#[path = "convert_parity.rs"]
mod convert_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "progress_conformance.rs"]
mod progress_conformance;

#[path = "quant_parity.rs"]
mod quant_parity;

#[path = "registry_e2e.rs"]
mod registry_e2e;

#[path = "tiling_parity.rs"]
mod tiling_parity;

#[path = "vae_parity.rs"]
mod vae_parity;

#[path = "video_parity.rs"]
mod video_parity;
