//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "conformance.rs"]
mod conformance;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "generator.rs"]
mod generator;

#[path = "mllm_image_parity.rs"]
mod mllm_image_parity;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "pipeline_e2e.rs"]
mod pipeline_e2e;

#[path = "quant_profile.rs"]
mod quant_profile;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "turbo_curated_smoke.rs"]
mod turbo_curated_smoke;

#[path = "turnkey.rs"]
mod turnkey;

#[path = "unified_sampler_smoke.rs"]
mod unified_sampler_smoke;

#[path = "vae_parity.rs"]
mod vae_parity;

#[path = "vision_parity.rs"]
mod vision_parity;
