//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "assembly_parity.rs"]
mod assembly_parity;

#[path = "clip_diff_parity.rs"]
mod clip_diff_parity;

#[path = "gpu_smoke.rs"]
mod gpu_smoke;

#[path = "handoff_parity.rs"]
mod handoff_parity;

#[path = "mar_mt19937_parity.rs"]
mod mar_mt19937_parity;

#[path = "mar_parity.rs"]
mod mar_parity;

#[path = "process_parity.rs"]
mod process_parity;

#[path = "qwen_backbone_parity.rs"]
mod qwen_backbone_parity;

#[path = "template_parity.rs"]
mod template_parity;

#[path = "vision_tower_parity.rs"]
mod vision_tower_parity;

#[path = "vit_guidance_parity.rs"]
mod vit_guidance_parity;

#[path = "vit_preprocess_parity.rs"]
mod vit_preprocess_parity;
