//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "bf16_perf_smoke.rs"]
mod bf16_perf_smoke;

#[path = "block_parity.rs"]
mod block_parity;

#[path = "build_tiers.rs"]
mod build_tiers;

#[path = "chunked_decode.rs"]
mod chunked_decode;

#[path = "decode_memory_real_weights.rs"]
mod decode_memory_real_weights;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "quant_parity.rs"]
mod quant_parity;

#[path = "registration.rs"]
mod registration;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "vae_parity.rs"]
mod vae_parity;
