#!/usr/bin/env python3
"""Bump both pinned backends (MLX + Candle) to the latest upstream commit, in one shot.

The MLX (`pmetal-mlx-rs`) and Candle backends are pinned by full commit SHA. Each pin is
replicated in three places that MUST advance together or the workspace gate rejects the tree:

  1. root ``Cargo.toml`` ``[workspace.dependencies]``  -- the active pins cargo resolves;
  2. ``scripts/check-workspace.py`` ``PINNED_WORKSPACE_DEPENDENCIES`` -- the drift tripwire,
     which hardcodes the *expected* SHA and fails the build if the pin moves without it;
  3. ``Cargo.lock``                                    -- regenerated by ``cargo update``.

This tool resolves each backend's latest commit (``git ls-remote``), rewrites sites 1 and 2 for
whichever backends moved, regenerates the lockfile, and re-runs the gate. Run it with no arguments.

What it deliberately does NOT touch, and reports instead:
  * ``crates/media/mlx-gen/Cargo.toml`` ``[package.metadata.legacy-workspace-dependencies]`` --
    inert metadata carrying a hand-written SHA-lineage changelog; a new SHA needs a human rationale
    line, not a mechanical substitution;
  * ``docs/migration/*.md`` -- historical checkpoints that record a past state and must not move.

Usage:
    python3 scripts/bump_pins.py              # bump both to latest, regen lock, run the gate
    python3 scripts/bump_pins.py --dry-run    # show current -> latest for both, write nothing
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CARGO_TOML = ROOT / "Cargo.toml"
GATE = ROOT / "scripts" / "check-workspace.py"

SHA_RE = re.compile(r"^[0-9a-f]{40}$")
ANY_SHA = r"[0-9a-f]{40}"


@dataclass(frozen=True)
class PinGroup:
    """One git-pinned backend and every artifact that repeats its SHA.

    ``manifest_deps`` are the ``[workspace.dependencies]`` keys in the root ``Cargo.toml``;
    ``lock_packages`` are the resolved cargo package names (``cargo update -p`` specs), which
    differ from the dependency key when the dep aliases a package (``mlx-rs`` -> ``pmetal-mlx-rs``).
    This mapping is asserted to match ``check-workspace.py`` by ``test_bump_pins.py`` so the two
    files cannot drift. ``ref`` is the remote ref whose latest commit we track (default branch).
    """

    key: str
    git: str
    manifest_deps: tuple[str, ...]
    lock_packages: tuple[str, ...]
    ref: str = "HEAD"


PIN_GROUPS = {
    "mlx": PinGroup(
        key="mlx",
        git="https://github.com/michaeltrefry/mlx-rs",
        manifest_deps=("mlx-rs", "mlx-sys"),
        lock_packages=("pmetal-mlx-rs", "pmetal-mlx-sys"),
    ),
    "candle": PinGroup(
        key="candle",
        git="https://github.com/huggingface/candle",
        # candle-flash-attn is CUDA-only and absent from the default resolved graph, but the root
        # manifest pin and the gate's PINNED_WORKSPACE_DEPENDENCIES both list it, so it bumps here.
        manifest_deps=("candle-core", "candle-nn", "candle-transformers", "candle-flash-attn"),
        lock_packages=("candle-core", "candle-nn", "candle-transformers", "candle-flash-attn"),
    ),
}


class BumpError(Exception):
    """A precondition failed -- the tree is not in a state this tool will edit."""


# --- pure functions (no filesystem, no subprocess: unit-tested offline) ---------------------


def _dep_rev_pattern(dep: str) -> re.Pattern[str]:
    # Match `<dep> = { ... rev = "<40hex>" ... }` on one line, capturing the SHA. The manifest
    # keeps each pin on a single line, and the [patch] table overrides candle-kernels by path
    # (no rev), so a per-dep-name, whole-file match is unambiguous in the root manifest.
    return re.compile(
        rf'(?m)^(?P<head>{re.escape(dep)}\s*=\s*\{{[^}}\n]*?\brev\s*=\s*")(?P<rev>{ANY_SHA})(?P<tail>")'
    )


def _gate_rev_pattern(dep: str) -> re.Pattern[str]:
    # Match the gate's `"<dep>": ("<package>", "<40hex>"),` entry, capturing the SHA.
    return re.compile(
        rf'(?P<head>"{re.escape(dep)}"\s*:\s*\(\s*"[^"]+"\s*,\s*")(?P<rev>{ANY_SHA})(?P<tail>")'
    )


def read_group_rev(text: str, group: PinGroup, *, patterns) -> str:
    """Return the single SHA the group is currently pinned at, or raise on drift/absence.

    ``patterns`` builds the per-dep regex (``_dep_rev_pattern`` for the manifest,
    ``_gate_rev_pattern`` for the gate) so the same consistency check covers both files.
    """
    found: dict[str, str] = {}
    for dep in group.manifest_deps:
        matches = patterns(dep).findall(text)
        if len(matches) != 1:
            raise BumpError(f"expected exactly one pin line for {dep!r}, found {len(matches)}")
        found[dep] = matches[0][1]
    revs = set(found.values())
    if len(revs) != 1:
        raise BumpError(f"{group.key} pins are inconsistent (mid-bump?): {found}")
    return revs.pop()


def rewrite(text: str, group: PinGroup, old_rev: str, new_rev: str, *, patterns) -> str:
    """Replace ``old_rev`` with ``new_rev`` on every group dep line; assert each was hit once."""
    result = text
    for dep in group.manifest_deps:
        pattern = patterns(dep)

        def _sub(match: re.Match[str]) -> str:
            if match.group("rev") != old_rev:
                raise BumpError(
                    f"{dep!r} is pinned at {match.group('rev')}, not the expected {old_rev}"
                )
            return f"{match.group('head')}{new_rev}{match.group('tail')}"

        result, count = pattern.subn(_sub, result)
        if count != 1:
            raise BumpError(f"expected to update {dep!r} exactly once, updated {count}")
    return result


def parse_ls_remote(output: str) -> str:
    """Pull the commit SHA out of ``git ls-remote <url> <ref>`` output (`<sha>\\t<ref>`)."""
    lines = [line for line in output.splitlines() if line.strip()]
    if not lines:
        raise BumpError("git ls-remote returned no ref")
    sha = lines[0].split()[0].strip()
    if not SHA_RE.match(sha):
        raise BumpError(f"git ls-remote returned a non-SHA head: {sha!r}")
    return sha


# --- filesystem + git/cargo orchestration ---------------------------------------------------


def latest_rev(group: PinGroup) -> str:
    """The latest commit on the backend's tracked ref, without cloning (needs network)."""
    result = subprocess.run(
        ["git", "ls-remote", group.git, group.ref],
        cwd=ROOT,
        check=False,
        capture_output=True,
        encoding="utf-8",
    )
    if result.returncode:
        raise BumpError(f"git ls-remote {group.git} {group.ref} failed: {result.stderr.strip()}")
    return parse_ls_remote(result.stdout)


def plan_edits(group: PinGroup, new_rev: str) -> tuple[str, str, str] | None:
    """Compute the new contents of the manifest and gate for a group bump.

    Returns ``(old_rev, new_cargo_toml, new_gate)`` or ``None`` if already at ``new_rev``.
    Raises ``BumpError`` if the two files disagree on the current pin (a half-applied bump).
    """
    cargo_text = CARGO_TOML.read_text(encoding="utf-8")
    gate_text = GATE.read_text(encoding="utf-8")

    manifest_rev = read_group_rev(cargo_text, group, patterns=_dep_rev_pattern)
    gate_rev = read_group_rev(gate_text, group, patterns=_gate_rev_pattern)
    if manifest_rev != gate_rev:
        raise BumpError(
            f"{group.key}: Cargo.toml is at {manifest_rev} but check-workspace.py is at "
            f"{gate_rev}; resolve this half-applied state before bumping"
        )
    if manifest_rev == new_rev:
        return None

    new_cargo = rewrite(cargo_text, group, manifest_rev, new_rev, patterns=_dep_rev_pattern)
    new_gate = rewrite(gate_text, group, manifest_rev, new_rev, patterns=_gate_rev_pattern)
    return manifest_rev, new_cargo, new_gate


def stale_occurrences(old_rev: str) -> list[str]:
    """`git grep` for the retired SHA so leftover references get surfaced, not silently missed.

    Expected leftovers are the mlx-gen legacy metadata block and the migration docs -- both
    intentionally human-owned (rationale, historical record).
    """
    result = subprocess.run(
        ["git", "grep", "-n", old_rev],
        cwd=ROOT,
        check=False,
        capture_output=True,
        encoding="utf-8",
    )
    return [line for line in result.stdout.splitlines() if line.strip()]


def run_cargo_update(packages: list[str]) -> int:
    """Re-pin the lockfile to the manifest's new revs (fetches the new commits; needs network)."""
    command = ["cargo", "update"]
    for package in packages:
        command += ["-p", package]
    print(f"$ {' '.join(command)}")
    return subprocess.run(command, cwd=ROOT, check=False).returncode


def run_gate() -> int:
    print("$ python3 scripts/check-workspace.py")
    return subprocess.run([sys.executable, str(GATE)], cwd=ROOT, check=False).returncode


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="show current -> latest for both backends and write nothing",
    )
    args = parser.parse_args(argv)

    # Resolve latest + plan every group up front, so a precondition failure aborts before any write.
    plans: list[tuple[PinGroup, str, str]] = []  # (group, old_rev, latest_rev)
    try:
        for group in PIN_GROUPS.values():
            latest = latest_rev(group)
            if plan_edits(group, latest) is None:
                print(f"{group.key}: already at latest {latest}")
                continue
            old_rev = read_group_rev(
                CARGO_TOML.read_text(encoding="utf-8"), group, patterns=_dep_rev_pattern
            )
            plans.append((group, old_rev, latest))
            print(f"{group.key}: {old_rev} -> {latest}")
    except BumpError as error:
        print(f"bump_pins: FAIL: {error}", file=sys.stderr)
        return 1

    if not plans:
        print("bump_pins: both pins already at their latest commit")
        return 0
    if args.dry_run:
        print("bump_pins: dry run, no files written")
        return 0

    # Write. Each group re-plans against the just-written files, so the second group's edit
    # preserves the first's (both backends share the same two files).
    for group, _old_rev, latest in plans:
        replan = plan_edits(group, latest)
        if replan is None:
            continue
        _, new_cargo, new_gate = replan
        CARGO_TOML.write_text(new_cargo, encoding="utf-8")
        GATE.write_text(new_gate, encoding="utf-8")
        print(f"{group.key}: wrote Cargo.toml + scripts/check-workspace.py")

    for group, old_rev, _latest in plans:
        leftovers = stale_occurrences(old_rev)
        if leftovers:
            print(f"\n{group.key}: retired {old_rev} still referenced (update by hand if intended):")
            for line in leftovers:
                print(f"  {line}")

    # Regenerate the lockfile and prove the tree passes the gate it must pass in CI.
    packages = [package for group, _, _ in plans for package in group.lock_packages]
    if run_cargo_update(packages):
        print("bump_pins: FAIL: `cargo update` failed", file=sys.stderr)
        return 1
    return run_gate()


if __name__ == "__main__":
    raise SystemExit(main())
