//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "adapter_parity.rs"]
mod adapter_parity;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "dit_quant_parity.rs"]
mod dit_quant_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "encoder_quant_parity.rs"]
mod encoder_quant_parity;

#[path = "gptoss_parity.rs"]
mod gptoss_parity;

#[path = "packed_tier_validate.rs"]
mod packed_tier_validate;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "reasoner_parity.rs"]
mod reasoner_parity;

#[path = "schedule_parity.rs"]
mod schedule_parity;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "trainer_conformance.rs"]
mod trainer_conformance;

#[path = "trainer_e2e.rs"]
mod trainer_e2e;

#[path = "vae_encode_parity.rs"]
mod vae_encode_parity;

#[path = "vae_parity.rs"]
mod vae_parity;
