//! Anima candle-port parity goldens (sc-10525, epic 10512) — the **CPU / CI-runnable** stages. They
//! read the committed golden JSON (regenerated by the MLX lane's `gen_anima_parity_goldens.py`,
//! diffusers 0.39.0) — **no Python at test time** — and need **no** licensed weights, so they run in
//! the plain `cargo test` (CPU) lane and prove framework-independent correctness against the SAME
//! goldens the MLX port asserts.
//!
//! Covered here:
//!   * **Stage 1** — Qwen2 + T5 tokenizers → exact token ids (integer-exact; must MATCH the MLX lane).
//!   * **Stage 5** — `linspace(1, 1/N, N)` sigma schedule + static `shift=3.0` → sigmas (exact CPU math).
//!
//! The real-weights stages (2 Qwen3, 3 conditioner, 4 DiT) live in `parity_real_weights.rs`,
//! `#[ignore]`d + weights-gated. RoPE traps + the 17-channel patch input are unit tests in the crate.

use serde_json::Value;

use candle_gen_anima::pipeline::anima_sigmas;
use candle_gen_anima::tokenizer::AnimaTokenizers;

fn load_golden(name: &str) -> Value {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn as_i32_vec(v: &Value) -> Vec<i32> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_i64().expect("int") as i32)
        .collect()
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_f64().expect("float"))
        .collect()
}

// -------------------------------------------------------------------------------------------------
// Stage 1 — tokenizers → exact token ids (integer-exact; CPU/scalar; identical to the MLX lane).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage1_tokenizers_match_golden_ids() {
    let g = load_golden("tokenizer_golden.json");
    let cases = g["cases"].as_array().expect("cases array");
    assert_eq!(cases.len(), 6, "expected 6 fixture-prompt cases");

    let tk = AnimaTokenizers::load().expect("load vendored tokenizers");
    for case in cases {
        let prompt = case["prompt"].as_str().expect("prompt");
        let want_qwen = as_i32_vec(&case["qwen_ids"]);
        let want_qwen_mask = as_i32_vec(&case["qwen_mask"]);
        let want_t5 = as_i32_vec(&case["t5_ids"]);

        let (got_qwen, got_qmask) = tk.encode_qwen(prompt).expect("encode_qwen");
        let got_t5 = tk.encode_t5(prompt).expect("encode_t5");

        assert_eq!(
            got_qwen, want_qwen,
            "Qwen ids mismatch for prompt {prompt:?}"
        );
        assert_eq!(
            got_qmask, want_qwen_mask,
            "Qwen mask mismatch for prompt {prompt:?}"
        );
        assert_eq!(got_t5, want_t5, "T5 ids mismatch for prompt {prompt:?}");
    }

    // The empty prompt is the load-bearing edge (reference: Qwen [[0]]/mask[[0]], T5 [[1]] EOS).
    let empty = cases
        .iter()
        .find(|c| c["prompt"].as_str() == Some(""))
        .expect("empty-prompt case present");
    assert_eq!(as_i32_vec(&empty["qwen_ids"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["qwen_mask"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["t5_ids"]), vec![1]);
}

// -------------------------------------------------------------------------------------------------
// Stage 5 — the sigma schedule (exact CPU arithmetic; must match the diffusers reference exactly).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage5_sigma_schedule_matches_golden() {
    let g = load_golden("sigma_schedule_golden.json");
    let schedules = g["schedules"].as_object().expect("schedules object");
    assert!(!schedules.is_empty(), "no schedules in golden");

    for (steps_str, sched) in schedules {
        let steps: usize = steps_str.parse().expect("steps key is an int");
        let want = as_f64_vec(&sched["sigmas"]);
        let got = anima_sigmas(steps);
        assert_eq!(
            got.len(),
            want.len(),
            "sigma length mismatch for N={steps} (got {}, want {})",
            got.len(),
            want.len()
        );
        for (i, (g, w)) in got.iter().zip(want.iter()).enumerate() {
            assert!(
                (*g as f64 - *w).abs() < 1e-5,
                "sigma[{i}] mismatch for N={steps}: got {g}, want {w}"
            );
        }
    }
}
