//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "encode_dtype.rs"]
mod encode_dtype;

#[path = "lora_injection.rs"]
mod lora_injection;

#[path = "packed_adapters.rs"]
mod packed_adapters;

#[path = "parity_goldens.rs"]
mod parity_goldens;

#[path = "parity_real_weights.rs"]
mod parity_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;

#[path = "real_weights.rs"]
mod real_weights;

#[path = "scale_convention.rs"]
mod scale_convention;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "training.rs"]
mod training;

#[path = "velocity_convention.rs"]
mod velocity_convention;
