//! Anima MLX-port parity goldens (sc-10524, epic 10512) — the **CI-runnable** stages: they read the
//! committed golden JSON (no Python at test time) and need **no** licensed weights, so they run in the
//! macOS `cargo test --workspace` lane.
//!
//! Covered here:
//!   * **Stage 1** — Qwen2 + T5 tokenizers → exact token ids for the fixture prompts.
//!   * **Stage 5** — `linspace(1, 1/N, N)` sigma schedule + static `shift=3.0` → sigmas/timesteps.
//!   * **Stage 6** — assert the VAE is REUSED (`mlx_gen_qwen_image::QwenVae`), not forked.
//!   * **DiT forward (synthetic)** — a small deterministic-random-weight Cosmos DiT run on the CI Metal
//!     GPU (NO licensed weights, NO snapshot), pinned to a committed golden. This is the CI numeric
//!     protection for the transformer forward (the real-weights DiT stages are `#[ignore]`d).
//!   * **Trap** — 17-channel patch-embed input (`concat_padding_mask`).
//!   * **Trap** — per-axis RoPE OOD reject (never index OOB).
//!   * **Trap** — prompt weighting is **not yet implemented** (documented finding → follow-up story).
//!
//! The real-weights stages (2 Qwen3, 3 conditioner, 4 DiT, 7 e2e) live in `tests/parity_real_weights.rs`
//! and `tests/real_weights.rs`, all `#[ignore]`d + weights-gated (they never run in CI).
//!
//! Goldens regenerated by `tests/fixtures/gen_anima_parity_goldens.py` (diffusers 0.39.0, Apache-2.0).

use mlx_rs::{Array, Dtype};
use serde_json::Value;

use mlx_gen::weights::Weights;
use mlx_gen_anima::config::DitConfig;
use mlx_gen_anima::pipeline::anima_sigmas;
use mlx_gen_anima::rope::cosmos_image_rope;
use mlx_gen_anima::tokenizer::AnimaTokenizers;
use mlx_gen_anima::transformer::CosmosDiT;

fn load_golden(name: &str) -> Value {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn as_i32_vec(v: &Value) -> Vec<i32> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_i64().expect("int") as i32)
        .collect()
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_f64().expect("float"))
        .collect()
}

// -------------------------------------------------------------------------------------------------
// Stage 1 — tokenizers → exact token ids (integer-exact; CPU/scalar).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage1_tokenizers_match_golden_ids() {
    let g = load_golden("tokenizer_golden.json");
    let cases = g["cases"].as_array().expect("cases array");
    // Hard-assert element count first — a loop over an empty array would assert nothing.
    assert_eq!(cases.len(), 6, "expected 6 fixture-prompt cases");

    let tk = AnimaTokenizers::load().expect("load vendored tokenizers");
    for case in cases {
        let prompt = case["prompt"].as_str().expect("prompt");
        let want_qwen = as_i32_vec(&case["qwen_ids"]);
        let want_qwen_mask = as_i32_vec(&case["qwen_mask"]);
        let want_t5 = as_i32_vec(&case["t5_ids"]);

        let (qids, qmask) = tk.encode_qwen(prompt).expect("encode_qwen");
        let got_qwen = qids.as_slice::<i32>().to_vec();
        let got_qmask = qmask.as_slice::<i32>().to_vec();
        let t5 = tk.encode_t5(prompt).expect("encode_t5");
        let got_t5 = t5.as_slice::<i32>().to_vec();

        assert_eq!(
            got_qwen, want_qwen,
            "Qwen ids mismatch for prompt {prompt:?}"
        );
        assert_eq!(
            got_qmask, want_qwen_mask,
            "Qwen mask mismatch for prompt {prompt:?}"
        );
        assert_eq!(got_t5, want_t5, "T5 ids mismatch for prompt {prompt:?}");
    }

    // The empty prompt is the load-bearing edge (reference: Qwen [[0]]/mask[[0]], T5 [[1]] EOS).
    let empty = cases
        .iter()
        .find(|c| c["prompt"].as_str() == Some(""))
        .expect("empty-prompt case present");
    assert_eq!(as_i32_vec(&empty["qwen_ids"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["qwen_mask"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["t5_ids"]), vec![1]);
}

// -------------------------------------------------------------------------------------------------
// Stage 5 — sigma schedule + timestep convention (~1e-6; CPU/scalar).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage5_sigma_schedule_matches_golden() {
    let g = load_golden("sigma_schedule_golden.json");
    let schedules = g["schedules"].as_object().expect("schedules object");
    assert_eq!(schedules.len(), 4, "expected schedules for N = 1,10,30,50");

    for n in [1usize, 10, 30, 50] {
        let entry = &schedules[&n.to_string()];
        let want_sigmas = as_f64_vec(&entry["sigmas"]);
        let want_timesteps = as_f64_vec(&entry["timesteps"]);
        // Reference appends a terminal 0.0 → N+1 sigmas; N timesteps (pre-terminal).
        assert_eq!(want_sigmas.len(), n + 1, "N={n}: sigma count");
        assert_eq!(want_timesteps.len(), n, "N={n}: timestep count");

        let got = anima_sigmas(n);
        assert_eq!(got.len(), n + 1, "N={n}: anima_sigmas length");
        for (i, (&a, &b)) in got.iter().zip(&want_sigmas).enumerate() {
            assert!(
                (a as f64 - b).abs() < 1e-6,
                "N={n} sigma[{i}]: got {a}, want {b}"
            );
        }
        // The DiT consumes the RAW σ as its timestep; the diffusers scheduler stores σ·1000 and divides
        // it back before the DiT (denoise.py:47). Assert BOTH: (a) golden self-consistency
        // timesteps[i] == sigmas[i]·1000, and (b) our σ·1000 reproduces the golden timesteps.
        for i in 0..n {
            assert!(
                (want_timesteps[i] - want_sigmas[i] * 1000.0).abs() < 1e-2,
                "N={n} golden timestep[{i}] != sigma·1000"
            );
            assert!(
                (got[i] as f64 * 1000.0 - want_timesteps[i]).abs() < 1e-2,
                "N={n} σ·1000[{i}]: got {}, want {}",
                got[i] as f64 * 1000.0,
                want_timesteps[i]
            );
        }
    }

    // N=1 is the degenerate single-step case (shift(1.0)=1.0).
    assert_eq!(anima_sigmas(1), vec![1.0, 0.0]);
}

// -------------------------------------------------------------------------------------------------
// Stage 6 — the VAE is REUSED, not forked. `mlx_gen_anima::QwenVae` is a re-export of the Qwen-Image
// `AutoencoderKLQwenImage` port; its own numeric parity is locked by
// `mlx-gen-qwen-image/tests/vae_real_weights.rs`. Asserting type identity proves we did not re-port it.
// -------------------------------------------------------------------------------------------------

#[test]
fn stage6_vae_is_reused_qwen_image_type() {
    let anima_ty = std::any::type_name::<mlx_gen_anima::QwenVae>();
    let qwen_ty = std::any::type_name::<mlx_gen_qwen_image::QwenVae>();
    assert_eq!(
        anima_ty, qwen_ty,
        "Anima must REUSE mlx_gen_qwen_image::QwenVae, not fork it (got {anima_ty} vs {qwen_ty})"
    );
    assert!(
        qwen_ty.starts_with("mlx_gen_qwen_image::"),
        "VAE type should live in mlx_gen_qwen_image, got {qwen_ty}"
    );
}

// -------------------------------------------------------------------------------------------------
// Trap — patch-embed input is 17 channels (concat_padding_mask: true ⇒ 16 latent + 1 mask).
// -------------------------------------------------------------------------------------------------

#[test]
fn trap_patch_embed_input_is_17_channels() {
    let c = DitConfig::anima();
    assert!(c.concat_padding_mask, "concat_padding_mask must be true");
    assert_eq!(c.in_channels, 16, "latent channels");
    assert_eq!(
        c.patch_in_channels(),
        17,
        "patch-embed sees 16 latent + 1 padding-mask channel"
    );
}

// -------------------------------------------------------------------------------------------------
// Trap — per-axis RoPE OOD reject: a request above ~1920 px/side (post-patch > 120/axis) must ERROR,
// never index OOB. max_size/patch = (128,120,120).
// -------------------------------------------------------------------------------------------------

#[test]
fn trap_rope_rejects_per_axis_ood_never_indexes_oob() {
    let cfg = DitConfig::anima();
    assert_eq!(cfg.max_size, (128, 120, 120), "post-patch max_size");
    // 121 positions on either spatial axis exceeds the trained range -> must reject.
    assert!(
        cosmos_image_rope(&cfg, 1, 121, 96).is_err(),
        "h-axis 121 > 120 must be rejected"
    );
    assert!(
        cosmos_image_rope(&cfg, 1, 96, 121).is_err(),
        "w-axis 121 > 120 must be rejected"
    );
    // The 1920² boundary (post-patch 120) fits; 1536² (post-patch 96, the shipped ceiling) fits.
    assert!(
        cosmos_image_rope(&cfg, 1, 120, 120).is_ok(),
        "120 is in-range"
    );
    assert!(cosmos_image_rope(&cfg, 1, 96, 96).is_ok(), "96 is in-range");
    // A correctly-sized 1024² request (post-patch 64) produces the right table shape.
    let r = cosmos_image_rope(&cfg, 1, 64, 64).expect("64x64 ok");
    assert_eq!(r.cos.shape(), &[1, 4096, 128]);
}

// -------------------------------------------------------------------------------------------------
// Prompt weighting (sc-10566). ComfyUI (`comfy/text_encoders/anima.py`) forces the Qwen token weights
// to 1.0 and carries `t5xxl_weights` separately, so weighting hits the **T5 query tokens**, not Qwen.
// mlx-gen-anima now parses `(text:weight)` emphasis and carries a per-token weight vector on the T5
// side only. This test (which REPLACES the sc-10524 `trap_prompt_weighting_absent_*` guard) proves the
// weight syntax is PARSED OUT — not fed as literal characters — and that an unweighted prompt is a
// strict no-op. The numeric both-directions / mutation / image proofs (real weights + Metal) live in
// `tests/real_weights.rs` (`#[ignore]`d). No licensed weights are needed here — tokenizers only.
// -------------------------------------------------------------------------------------------------

#[test]
fn prompt_weighting_is_parsed_out_and_plain_is_strict_noop() {
    use mlx_gen_anima::strip_prompt_weights;
    let tk = AnimaTokenizers::load().expect("load tokenizers");

    // `(chibi:2)` is PARSED, not literal: the T5 stream tokenizes `chibi` (emphasis removed) — the
    // SAME ids as bare `chibi` — with a per-token weight 2.0, not the characters `( c h i b i : 2 )`.
    let (bare_ids, bare_w) = tk.encode_t5_weighted("chibi").unwrap();
    let (wt_ids, wt_w) = tk.encode_t5_weighted("(chibi:2)").unwrap();
    assert_eq!(
        bare_ids.as_slice::<i32>(),
        wt_ids.as_slice::<i32>(),
        "T5 ids for `(chibi:2)` must equal bare `chibi` (weight syntax stripped, not tokenized)"
    );
    assert!(
        bare_w.iter().all(|&w| w == 1.0),
        "bare `chibi` weights must all be 1.0, got {bare_w:?}"
    );
    // The `chibi` token(s) carry weight 2.0; the trailing EOS stays 1.0.
    assert!(
        wt_w.iter().any(|&w| (w - 2.0).abs() < 1e-6),
        "weighted `(chibi:2)` must carry a 2.0 token weight, got {wt_w:?}"
    );
    assert_eq!(*wt_w.last().unwrap(), 1.0, "T5 EOS weight must be 1.0");

    // Qwen tower is weight-BLIND: it is tokenized on the de-weighted text, so `(chibi:2)` gives the
    // exact same Qwen ids as `chibi` (the weight never reaches the Qwen path).
    let (q_bare, _) = tk.encode_qwen("chibi").unwrap();
    let (q_wt, _) = tk.encode_qwen(&strip_prompt_weights("(chibi:2)")).unwrap();
    assert_eq!(
        q_bare.as_slice::<i32>(),
        q_wt.as_slice::<i32>(),
        "Qwen ids must be identical for `chibi` and (de-weighted) `(chibi:2)`"
    );

    // Strict no-op: an unweighted prompt yields the SAME T5 ids as `encode_t5` and all-1.0 weights.
    for plain in ["1girl, silver hair, masterpiece", "a cat", ""] {
        let (pw_ids, pw_w) = tk.encode_t5_weighted(plain).unwrap();
        let base_ids = tk.encode_t5(plain).unwrap();
        assert_eq!(
            pw_ids.as_slice::<i32>(),
            base_ids.as_slice::<i32>(),
            "encode_t5_weighted must match encode_t5 for the unweighted prompt {plain:?}"
        );
        assert!(
            pw_w.iter().all(|&w| w == 1.0),
            "unweighted prompt {plain:?} must have all-1.0 weights, got {pw_w:?}"
        );
    }
}

// =================================================================================================
// CI DiT-forward golden — SYNTHETIC deterministic-random weights (sc-10524 review). Closes the hole
// the review flagged: the real-weights DiT stages (2/3/4/7) are `#[ignore]`d + snapshot-gated, so a
// numeric regression in the transformer forward shipped GREEN — CI had ZERO numeric protection for it.
//
// This test runs a SMALL Cosmos DiT (2 layers, hidden 12, NON-SQUARE 4×6 latent) with weights from a
// fixed-seed deterministic RNG — NO licensed weights, NO HF snapshot — on the CI Metal GPU, and pins
// committed numbers. It catches structural regressions with no weights: the 17-vs-16 padding-mask
// concat, adaLN modulation wiring, the h/w RoPE axis (the grid is non-square, so a transposition
// changes the output), a wrong checkpoint prefix, and any shape drift.
//
// The pinned numbers are the reviewer-verified-correct Rust forward frozen as a REGRESSION LOCK (the
// correctness ORACLE is the real-weights stages, which the reviewer independently reproduced). Its
// sensitivity — that it is NOT a vacuous self-check — is proven by the PR's mutation checks: breaking
// the channel concat and the adaLN modulation each make this test fail.
//
// Regenerate the golden (only when the forward legitimately changes) with:
//   ANIMA_BLESS_SYNTH=1 cargo test -p mlx-gen-anima --test parity_goldens -- \
//       --ignored bless_synthetic_dit_golden --nocapture
// =================================================================================================

/// A tiny Cosmos DiT config with the SAME structure as [`DitConfig::anima`] (17-ch concat, 3-axis NTK
/// RoPE, adaLN-LoRA, patch `(1,2,2)`) but small dims, so the forward is cheap and the golden is tiny.
fn synth_cfg() -> DitConfig {
    DitConfig {
        in_channels: 16, // → 17 after the padding-mask concat (the 17-vs-16 regression surface)
        out_channels: 16,
        num_attention_heads: 2,
        attention_head_dim: 6, // hidden = 12; head_dim 6 splits cleanly for the RoPE (dim_t/h/w = 2/2/2)
        num_layers: 2,
        mlp_ratio: 4.0,
        text_embed_dim: 8, // cross-attn context (encoder) dim
        adaln_lora_dim: 8,
        max_size: (128, 120, 120),
        patch_size: (1, 2, 2),
        rope_scale: (1.0, 4.0, 4.0),
        concat_padding_mask: true,
    }
}

/// FNV-1a of the key → a stable, order-independent, portable per-tensor seed.
fn key_seed(key: &str) -> u64 {
    let mut h = 0xcbf2_9ce4_8422_2325u64;
    for b in key.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01b3);
    }
    h
}

/// Deterministic LCG in `[-1, 1)` — the same integer recurrence as the real-weights tests' `lcg_fill`,
/// so weights reproduce bit-for-bit across machines and runs.
fn synth_lcg(n: usize, seed: u64) -> Vec<f32> {
    let mut s = seed & 0x7fff_ffff;
    (0..n)
        .map(|_| {
            s = (s.wrapping_mul(1103515245).wrapping_add(12345)) & 0x7fff_ffff;
            (s as f64 / 2147483647.0 * 2.0 - 1.0) as f32
        })
        .collect()
}

/// Insert a synthetic tensor for `key`. Norm/scale weights (`*norm.weight`) init near 1.0; linear
/// weights init at `0.3·lcg` — large enough that adaLN scale/shift/gate are O(1) (so a modulation-wiring
/// regression actually moves the output), yet small enough that the LayerNorm-gated two-layer forward
/// stays finite and well-behaved (verified: no NaN; std ~O(0.1–1)).
fn synth_tensor(w: &mut Weights, key: &str, shape: &[i32]) {
    let n: usize = shape.iter().map(|&d| d as usize).product();
    let raw = synth_lcg(n, key_seed(key));
    let data: Vec<f32> = if key.ends_with("norm.weight") {
        raw.iter().map(|&v| 1.0 + 0.1 * v).collect()
    } else {
        raw.iter().map(|&v| 0.3 * v).collect()
    };
    w.insert(key, Array::from_slice(&data, shape));
}

/// Build the full dense-f32 weight set the [`CosmosDiT`] loader requires (prefix `"net"`, Cosmos-original
/// key names). Every shape is derived from `cfg`, so this stays in lockstep with the loader.
fn synth_weights(cfg: &DitConfig) -> Weights {
    let h = cfg.hidden_size() as i32; // 12
    let hd = cfg.attention_head_dim as i32; // 6
    let lora = cfg.adaln_lora_dim as i32; // 8
    let ctx = cfg.text_embed_dim as i32; // 8 (cross-attn kv input)
    let ff = (cfg.mlp_ratio * cfg.hidden_size() as f32) as i32; // 48
    let (pt, ph, pw) = cfg.patch_size;
    let (pt, ph, pw) = (pt as i32, ph as i32, pw as i32);
    let patch_in = cfg.patch_in_channels() as i32 * pt * ph * pw; // 17·1·2·2 = 68
    let proj_out = ph * pw * pt * cfg.out_channels as i32; // 2·2·1·16 = 64
    let mut w = Weights::empty();
    synth_tensor(&mut w, "net.x_embedder.proj.1.weight", &[h, patch_in]);
    synth_tensor(&mut w, "net.t_embedder.1.linear_1.weight", &[3 * h, h]);
    synth_tensor(&mut w, "net.t_embedder.1.linear_2.weight", &[3 * h, 3 * h]);
    synth_tensor(&mut w, "net.t_embedding_norm.weight", &[h]);
    for i in 0..cfg.num_layers {
        let b = format!("net.blocks.{i}");
        for m in [
            "adaln_modulation_self_attn",
            "adaln_modulation_cross_attn",
            "adaln_modulation_mlp",
        ] {
            synth_tensor(&mut w, &format!("{b}.{m}.1.weight"), &[lora, h]);
            synth_tensor(&mut w, &format!("{b}.{m}.2.weight"), &[3 * h, lora]);
        }
        for (attn, kv_in) in [("self_attn", h), ("cross_attn", ctx)] {
            synth_tensor(&mut w, &format!("{b}.{attn}.q_proj.weight"), &[h, h]);
            synth_tensor(&mut w, &format!("{b}.{attn}.k_proj.weight"), &[h, kv_in]);
            synth_tensor(&mut w, &format!("{b}.{attn}.v_proj.weight"), &[h, kv_in]);
            synth_tensor(&mut w, &format!("{b}.{attn}.output_proj.weight"), &[h, h]);
            synth_tensor(&mut w, &format!("{b}.{attn}.q_norm.weight"), &[hd]);
            synth_tensor(&mut w, &format!("{b}.{attn}.k_norm.weight"), &[hd]);
        }
        synth_tensor(&mut w, &format!("{b}.mlp.layer1.weight"), &[ff, h]);
        synth_tensor(&mut w, &format!("{b}.mlp.layer2.weight"), &[h, ff]);
    }
    synth_tensor(
        &mut w,
        "net.final_layer.adaln_modulation.1.weight",
        &[lora, h],
    );
    synth_tensor(
        &mut w,
        "net.final_layer.adaln_modulation.2.weight",
        &[2 * h, lora],
    );
    synth_tensor(&mut w, "net.final_layer.linear.weight", &[proj_out, h]);
    w
}

/// The deterministic synthetic inputs: a NON-SQUARE latent `[1,16,1,4,6]` (post-patch grid 2×3 — so an
/// h/w RoPE swap is detectable) + encoder `[1,5,8]` + `sigma=0.7`. Seeds match nothing licensed.
fn synth_inputs() -> (Array, Array, Array) {
    let latent = Array::from_slice(&synth_lcg(16 * 4 * 6, 1), &[1, 16, 1, 4, 6]);
    let encoder = Array::from_slice(&synth_lcg(5 * 8, 2), &[1, 5, 8]);
    let sigma = Array::from_slice(&[0.7f32], &[1]);
    (latent, encoder, sigma)
}

/// Run block0 + the full forward with the synthetic weights (fp32 on the Metal GPU).
fn synth_run() -> (Array, Array) {
    let cfg = synth_cfg();
    let w = synth_weights(&cfg);
    let dit = CosmosDiT::from_weights(&w, "net", cfg).expect("synthetic DiT loads");
    let (latent, encoder, sigma) = synth_inputs();
    let block0 = dit
        .forward_hidden(&latent, &sigma, &encoder, Dtype::Float32, Some(1))
        .expect("forward_hidden");
    let full = dit
        .forward(&latent, &sigma, &encoder, Dtype::Float32)
        .expect("forward");
    (block0, full)
}

/// mean/std/l2 + a strided sample set of a tensor, as a JSON summary (mirrors the Python `summarize`).
fn synth_summarize(arr: &Array, n_samples: usize) -> Value {
    let flat: Vec<f64> = arr
        .as_dtype(Dtype::Float32)
        .unwrap()
        .as_slice::<f32>()
        .iter()
        .map(|&x| x as f64)
        .collect();
    let total = flat.len();
    let mean = flat.iter().sum::<f64>() / total as f64;
    let std = (flat.iter().map(|&x| (x - mean).powi(2)).sum::<f64>() / total as f64).sqrt();
    let l2 = flat.iter().map(|&x| x * x).sum::<f64>().sqrt();
    let mut idx: Vec<usize> = if total <= n_samples {
        (0..total).collect()
    } else {
        (0..n_samples)
            .map(|i| (i as f64 * (total as f64 - 1.0) / (n_samples as f64 - 1.0)).round() as usize)
            .collect()
    };
    idx.dedup();
    let samples: Vec<f64> = idx.iter().map(|&i| flat[i]).collect();
    serde_json::json!({
        "shape": arr.shape().to_vec(),
        "count": total,
        "mean": mean,
        "std": std,
        "l2": l2,
        "sample_indices": idx,
        "sample_values": samples,
    })
}

/// Assert a synthetic output against its committed summary with a **distribution / relative-L2** gate —
/// the SAME shape the real-weights stages use (`parity_real_weights::assert_sampled_rel_l2`), and for the
/// same reason. A per-**element** `atol`/`rtol` gate is the WRONG shape here: cross-**device** Metal fp32
/// matmul reorders its reductions, so a single small-magnitude element of a RAW pre-norm block hidden can
/// differ by a few e-3 *relative* between the Mac that blessed this golden and the CI runner — the CI
/// failure that motivated this change was |Δ| 5.9e-4 on |want| ≈ 0.153 (≈3.9e-3 relative), squarely
/// inside this codebase's long-documented ~1e-3 Metal-matmul relative spread. The old per-element bound
/// (`atol 1e-4 + rtol 1e-3` ≈ 2.5e-4 there) sat *below* that spread and so was red on CI while green on
/// the blessing machine — a device-portability bug in the gate, not a numeric regression.
///
/// So we gate the DISTRIBUTION instead: aggregate stats (mean/std/l2 within `stat_rtol`) plus a sampled
/// relative-L2 `‖got−want‖₂ / ‖want‖₂` over the fixed index set (under `max_rel_l2`). rel-L2 is
/// norm-weighted — it is NOT dominated by one small-magnitude element's relative rounding (the thing that
/// varies device-to-device), yet a structural regression (dropped 17→16 concat, swapped adaLN
/// scale/shift, transposed h/w RoPE axis) still moves it by ORDERS of magnitude. Returns the sampled
/// rel-L2 so the caller can log it. NOTE: `stat_rtol`/`max_rel_l2` absorb cross-**device** Metal fp32
/// matmul variance — not merely single-machine run-to-run noise.
fn assert_synth(got: &Array, g: &Value, label: &str, stat_rtol: f64, max_rel_l2: f64) -> f64 {
    let want_shape: Vec<i32> = g["shape"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_i64().unwrap() as i32)
        .collect();
    assert_eq!(got.shape(), &want_shape[..], "{label}: shape");
    let flat: Vec<f64> = got
        .as_dtype(Dtype::Float32)
        .unwrap()
        .as_slice::<f32>()
        .iter()
        .map(|&x| x as f64)
        .collect();
    let count = g["count"].as_u64().unwrap() as usize;
    assert_eq!(flat.len(), count, "{label}: count");
    // (1) Aggregate distribution gate — cross-device fp32 reordering barely moves these sums; a
    //     structural bug shifts them by orders of magnitude.
    let mean = flat.iter().sum::<f64>() / count as f64;
    let std = (flat.iter().map(|&x| (x - mean).powi(2)).sum::<f64>() / count as f64).sqrt();
    let l2 = flat.iter().map(|&x| x * x).sum::<f64>().sqrt();
    let (gm, gs, gl) = (
        g["mean"].as_f64().unwrap(),
        g["std"].as_f64().unwrap(),
        g["l2"].as_f64().unwrap(),
    );
    let rel = |a: f64, b: f64| (a - b).abs() / b.abs().max(1e-6);
    assert!(
        (mean - gm).abs() < stat_rtol * gs.abs().max(1e-3),
        "{label}: mean drift {mean} vs {gm}"
    );
    assert!(rel(std, gs) < stat_rtol, "{label}: std drift {std} vs {gs}");
    assert!(rel(l2, gl) < stat_rtol, "{label}: l2 drift {l2} vs {gl}");
    // (2) Sampled relative-L2 gate — the primary structural check.
    let idx: Vec<usize> = g["sample_indices"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_u64().unwrap() as usize)
        .collect();
    let vals: Vec<f64> = g["sample_values"]
        .as_array()
        .unwrap()
        .iter()
        .map(|x| x.as_f64().unwrap())
        .collect();
    assert!(idx.len() >= 16, "{label}: too few samples ({})", idx.len());
    let mut num = 0f64;
    let mut den = 0f64;
    for (&i, &want) in idx.iter().zip(&vals) {
        let d = flat[i] - want;
        num += d * d;
        den += want * want;
    }
    let rel_l2 = (num / den.max(1e-12)).sqrt();
    println!(
        "[{label}] rel-L2 = {rel_l2:.4e} (bound {max_rel_l2:.1e}); stats mean {mean:.5}/{gm:.5} \
         std {std:.5}/{gs:.5} l2 {l2:.4}/{gl:.4}"
    );
    assert!(
        rel_l2 < max_rel_l2,
        "{label}: sampled rel-L2 {rel_l2:.4e} exceeds {max_rel_l2:.1e} — a structural regression, \
         not cross-device fp32 noise"
    );
    rel_l2
}

/// **CI numeric protection for the DiT forward** — runs the synthetic-weight Cosmos DiT on Metal (no
/// licensed weights, no snapshot) and asserts block0 + the full velocity against the committed golden.
#[test]
fn synthetic_dit_forward_golden() {
    let g = load_golden("dit_synthetic_golden.json");
    let (block0, full) = synth_run();
    // block0 is the RAW pre-norm block-0 hidden — the worst-conditioned tensor in the forward, and the one
    // whose small-magnitude elements diverge most device-to-device (the CI failure that motivated this gate
    // was a block0 element). Gate its distribution LOOSELY, as a corroborating backstop: `max_rel_l2 =
    // 1.2e-2` is ~3.1× above the worst-case cross-device spread (~3.9e-3 relative) and ~24× above the
    // realistic aggregate spread (~5e-4), while still tripping on every structural mutation (measured on
    // this fixture: drop-concat 1.30, adaLN-swap 0.170, RoPE-h/w-swap 0.038 — the last only ~3.2× over this
    // bound because a 2×3 grid barely reshuffles under an axis swap; the FINAL-velocity gate below is what
    // carries the >10× guarantee for it).
    assert_synth(&block0, &g["block0"], "synth_block0", 5e-3, 1.2e-2);
    // The final velocity is norm_out + proj_out (LayerNorm-conditioned → the small-magnitude blow-ups that
    // make block0 noisy are gone), so it is the TIGHT gate. `max_rel_l2 = 5e-3` clears the (larger,
    // accumulated) cross-device spread with ~6× headroom yet catches ALL three mutations with margin —
    // measured: drop-concat 1.29 (258×), adaLN-swap 0.313 (63×), RoPE-h/w-swap 0.065 (13×, the smallest).
    assert_synth(&full, &g["full"], "synth_full", 3e-3, 5e-3);
}

/// Regenerate `dit_synthetic_golden.json` (gated on `ANIMA_BLESS_SYNTH=1` so a bare `--ignored` run is a
/// no-op and never rewrites the committed fixture). Run only when the forward legitimately changes.
#[test]
#[ignore = "golden regenerator — set ANIMA_BLESS_SYNTH=1 to write the fixture"]
fn bless_synthetic_dit_golden() {
    if std::env::var("ANIMA_BLESS_SYNTH").is_err() {
        println!("bless_synthetic_dit_golden: set ANIMA_BLESS_SYNTH=1 to regenerate (skipping)");
        return;
    }
    let cfg = synth_cfg();
    let (block0, full) = synth_run();
    let doc = serde_json::json!({
        "meta": {
            "story": "sc-10524",
            "epic": "10512",
            "kind": "synthetic-random-weight Cosmos DiT forward (CI, no licensed weights, no snapshot)",
            "note": "REGRESSION LOCK for the DiT forward in CI. Weights are a fixed-seed deterministic \
                     LCG (portable, bit-reproducible); the golden is the reviewer-verified-correct Rust \
                     forward frozen as committed numbers. Correctness oracle = the real-weights stages \
                     (2/3/4/7). Sensitivity proven by the PR's mutation checks (break the channel concat \
                     / adaLN → this fails). Catches: 17-vs-16 concat, adaLN wiring, h/w RoPE axis (grid \
                     is NON-SQUARE 2×3), wrong prefix, shape drift.",
            "config": {
                "num_layers": cfg.num_layers,
                "hidden": cfg.hidden_size(),
                "heads": cfg.num_attention_heads,
                "head_dim": cfg.attention_head_dim,
                "patch_in_channels": cfg.patch_in_channels(),
                "adaln_lora_dim": cfg.adaln_lora_dim,
                "text_embed_dim": cfg.text_embed_dim,
            },
            "inputs": {
                "latent_shape": [1, 16, 1, 4, 6],
                "latent_seed": 1,
                "encoder_shape": [1, 5, 8],
                "encoder_seed": 2,
                "sigma": 0.7,
                "post_patch_grid": [1, 2, 3],
            },
            "regen_command": "ANIMA_BLESS_SYNTH=1 cargo test -p mlx-gen-anima --test parity_goldens -- \
                              --ignored bless_synthetic_dit_golden --nocapture",
        },
        "block0": synth_summarize(&block0, 64),
        "full": synth_summarize(&full, 64),
    });
    let path = format!(
        "{}/tests/fixtures/dit_synthetic_golden.json",
        env!("CARGO_MANIFEST_DIR")
    );
    std::fs::write(&path, serde_json::to_string_pretty(&doc).unwrap() + "\n").unwrap();
    println!("wrote {path}");
}
