//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

mod common;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "generator_contract.rs"]
mod generator_contract;

#[path = "pipeline_parity.rs"]
mod pipeline_parity;

#[path = "registration.rs"]
mod registration;

#[path = "scheduler_parity.rs"]
mod scheduler_parity;

#[path = "text_encoder_parity.rs"]
mod text_encoder_parity;

#[path = "tiers.rs"]
mod tiers;

#[path = "transformer_parity.rs"]
mod transformer_parity;

#[path = "vae_parity.rs"]
mod vae_parity;
