//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "conformance.rs"]
mod conformance;

#[path = "fit_preview_rgb.rs"]
mod fit_preview_rgb;

#[path = "it2i_real_weights.rs"]
mod it2i_real_weights;

#[path = "preview_real_weights.rs"]
mod preview_real_weights;
