//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "backbone_parity.rs"]
mod backbone_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "distill_merge_realweight.rs"]
mod distill_merge_realweight;

#[path = "distill_parity.rs"]
mod distill_parity;

#[path = "fast_realweight.rs"]
mod fast_realweight;

#[path = "fm_parity.rs"]
mod fm_parity;

#[path = "interleave_parity.rs"]
mod interleave_parity;

#[path = "interleave_realweight.rs"]
mod interleave_realweight;

#[path = "it2i_parity.rs"]
mod it2i_parity;

#[path = "it2i_realweight.rs"]
mod it2i_realweight;

#[path = "model_realweight.rs"]
mod model_realweight;

#[path = "prequantize_real_weights.rs"]
mod prequantize_real_weights;

#[path = "quant_realweight.rs"]
mod quant_realweight;

#[path = "quant_smoke.rs"]
mod quant_smoke;

#[path = "runtime_parity.rs"]
mod runtime_parity;

#[path = "shared_memory_ladder.rs"]
mod shared_memory_ladder;

#[path = "shared_memory_ladder_real_weights.rs"]
mod shared_memory_ladder_real_weights;

#[path = "t2i_parity.rs"]
mod t2i_parity;

#[path = "t2i_realweight.rs"]
mod t2i_realweight;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "vision_parity.rs"]
mod vision_parity;

#[path = "vqa_parity.rs"]
mod vqa_parity;

#[path = "vqa_realweight.rs"]
mod vqa_realweight;

#[path = "weight_map_coverage.rs"]
mod weight_map_coverage;
