//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "backbone_parity.rs"]
mod backbone_parity;

#[path = "caption_real.rs"]
mod caption_real;

#[path = "e2e_real_weights.rs"]
mod e2e_real_weights;

#[path = "from_clean_decode.rs"]
mod from_clean_decode;

#[path = "from_ldm_decode.rs"]
mod from_ldm_decode;

#[path = "gemma_parity.rs"]
mod gemma_parity;

#[path = "hotpath_equivalence.rs"]
mod hotpath_equivalence;

#[path = "lq_parity.rs"]
mod lq_parity;

#[path = "sampler_parity.rs"]
mod sampler_parity;

#[path = "tiling_ab.rs"]
mod tiling_ab;

#[path = "v1pt5_real_weights.rs"]
mod v1pt5_real_weights;
