//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[allow(dead_code)]
mod common;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "edit_smoke.rs"]
mod edit_smoke;

#[path = "generator.rs"]
mod generator;

#[path = "memprofile.rs"]
mod memprofile;

#[path = "pid_decode_real_weights.rs"]
mod pid_decode_real_weights;

#[path = "prequantize.rs"]
mod prequantize;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "smoke.rs"]
mod smoke;

#[path = "te_parity.rs"]
mod te_parity;

#[path = "tokenizer_parity.rs"]
mod tokenizer_parity;

#[path = "turbo.rs"]
mod turbo;

#[path = "vae_parity.rs"]
mod vae_parity;
