//! Anima MLX-port parity goldens (sc-10524, epic 10512) — the **CI-runnable** stages: they read the
//! committed golden JSON (no Python at test time) and need **no** licensed weights, so they run in the
//! macOS `cargo test --workspace` lane.
//!
//! Covered here:
//!   * **Stage 1** — Qwen2 + T5 tokenizers → exact token ids for the fixture prompts.
//!   * **Stage 5** — `linspace(1, 1/N, N)` sigma schedule + static `shift=3.0` → sigmas/timesteps.
//!   * **Stage 6** — assert the VAE is REUSED (`mlx_gen_qwen_image::QwenVae`), not forked.
//!   * **Trap** — 17-channel patch-embed input (`concat_padding_mask`).
//!   * **Trap** — per-axis RoPE OOD reject (never index OOB).
//!   * **Trap** — prompt weighting is **not yet implemented** (documented finding → follow-up story).
//!
//! The real-weights stages (2 Qwen3, 3 conditioner, 4 DiT, 7 e2e) live in `tests/parity_real_weights.rs`
//! and `tests/real_weights.rs`, all `#[ignore]`d + weights-gated (they never run in CI).
//!
//! Goldens regenerated by `tests/fixtures/gen_anima_parity_goldens.py` (diffusers 0.39.0, Apache-2.0).

use serde_json::Value;

use mlx_gen_anima::config::DitConfig;
use mlx_gen_anima::pipeline::anima_sigmas;
use mlx_gen_anima::rope::cosmos_image_rope;
use mlx_gen_anima::tokenizer::AnimaTokenizers;

fn load_golden(name: &str) -> Value {
    let path = format!("{}/tests/fixtures/{}", env!("CARGO_MANIFEST_DIR"), name);
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {path}: {e}"));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parse {path}: {e}"))
}

fn as_i32_vec(v: &Value) -> Vec<i32> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_i64().expect("int") as i32)
        .collect()
}

fn as_f64_vec(v: &Value) -> Vec<f64> {
    v.as_array()
        .expect("json array")
        .iter()
        .map(|x| x.as_f64().expect("float"))
        .collect()
}

// -------------------------------------------------------------------------------------------------
// Stage 1 — tokenizers → exact token ids (integer-exact; CPU/scalar).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage1_tokenizers_match_golden_ids() {
    let g = load_golden("tokenizer_golden.json");
    let cases = g["cases"].as_array().expect("cases array");
    // Hard-assert element count first — a loop over an empty array would assert nothing.
    assert_eq!(cases.len(), 6, "expected 6 fixture-prompt cases");

    let tk = AnimaTokenizers::load().expect("load vendored tokenizers");
    for case in cases {
        let prompt = case["prompt"].as_str().expect("prompt");
        let want_qwen = as_i32_vec(&case["qwen_ids"]);
        let want_qwen_mask = as_i32_vec(&case["qwen_mask"]);
        let want_t5 = as_i32_vec(&case["t5_ids"]);

        let (qids, qmask) = tk.encode_qwen(prompt).expect("encode_qwen");
        let got_qwen = qids.as_slice::<i32>().to_vec();
        let got_qmask = qmask.as_slice::<i32>().to_vec();
        let t5 = tk.encode_t5(prompt).expect("encode_t5");
        let got_t5 = t5.as_slice::<i32>().to_vec();

        assert_eq!(
            got_qwen, want_qwen,
            "Qwen ids mismatch for prompt {prompt:?}"
        );
        assert_eq!(
            got_qmask, want_qwen_mask,
            "Qwen mask mismatch for prompt {prompt:?}"
        );
        assert_eq!(got_t5, want_t5, "T5 ids mismatch for prompt {prompt:?}");
    }

    // The empty prompt is the load-bearing edge (reference: Qwen [[0]]/mask[[0]], T5 [[1]] EOS).
    let empty = cases
        .iter()
        .find(|c| c["prompt"].as_str() == Some(""))
        .expect("empty-prompt case present");
    assert_eq!(as_i32_vec(&empty["qwen_ids"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["qwen_mask"]), vec![0]);
    assert_eq!(as_i32_vec(&empty["t5_ids"]), vec![1]);
}

// -------------------------------------------------------------------------------------------------
// Stage 5 — sigma schedule + timestep convention (~1e-6; CPU/scalar).
// -------------------------------------------------------------------------------------------------

#[test]
fn stage5_sigma_schedule_matches_golden() {
    let g = load_golden("sigma_schedule_golden.json");
    let schedules = g["schedules"].as_object().expect("schedules object");
    assert_eq!(schedules.len(), 4, "expected schedules for N = 1,10,30,50");

    for n in [1usize, 10, 30, 50] {
        let entry = &schedules[&n.to_string()];
        let want_sigmas = as_f64_vec(&entry["sigmas"]);
        let want_timesteps = as_f64_vec(&entry["timesteps"]);
        // Reference appends a terminal 0.0 → N+1 sigmas; N timesteps (pre-terminal).
        assert_eq!(want_sigmas.len(), n + 1, "N={n}: sigma count");
        assert_eq!(want_timesteps.len(), n, "N={n}: timestep count");

        let got = anima_sigmas(n);
        assert_eq!(got.len(), n + 1, "N={n}: anima_sigmas length");
        for (i, (&a, &b)) in got.iter().zip(&want_sigmas).enumerate() {
            assert!(
                (a as f64 - b).abs() < 1e-6,
                "N={n} sigma[{i}]: got {a}, want {b}"
            );
        }
        // The DiT consumes the RAW σ as its timestep; the diffusers scheduler stores σ·1000 and divides
        // it back before the DiT (denoise.py:47). Assert BOTH: (a) golden self-consistency
        // timesteps[i] == sigmas[i]·1000, and (b) our σ·1000 reproduces the golden timesteps.
        for i in 0..n {
            assert!(
                (want_timesteps[i] - want_sigmas[i] * 1000.0).abs() < 1e-2,
                "N={n} golden timestep[{i}] != sigma·1000"
            );
            assert!(
                (got[i] as f64 * 1000.0 - want_timesteps[i]).abs() < 1e-2,
                "N={n} σ·1000[{i}]: got {}, want {}",
                got[i] as f64 * 1000.0,
                want_timesteps[i]
            );
        }
    }

    // N=1 is the degenerate single-step case (shift(1.0)=1.0).
    assert_eq!(anima_sigmas(1), vec![1.0, 0.0]);
}

// -------------------------------------------------------------------------------------------------
// Stage 6 — the VAE is REUSED, not forked. `mlx_gen_anima::QwenVae` is a re-export of the Qwen-Image
// `AutoencoderKLQwenImage` port; its own numeric parity is locked by
// `mlx-gen-qwen-image/tests/vae_real_weights.rs`. Asserting type identity proves we did not re-port it.
// -------------------------------------------------------------------------------------------------

#[test]
fn stage6_vae_is_reused_qwen_image_type() {
    let anima_ty = std::any::type_name::<mlx_gen_anima::QwenVae>();
    let qwen_ty = std::any::type_name::<mlx_gen_qwen_image::QwenVae>();
    assert_eq!(
        anima_ty, qwen_ty,
        "Anima must REUSE mlx_gen_qwen_image::QwenVae, not fork it (got {anima_ty} vs {qwen_ty})"
    );
    assert!(
        qwen_ty.starts_with("mlx_gen_qwen_image::"),
        "VAE type should live in mlx_gen_qwen_image, got {qwen_ty}"
    );
}

// -------------------------------------------------------------------------------------------------
// Trap — patch-embed input is 17 channels (concat_padding_mask: true ⇒ 16 latent + 1 mask).
// -------------------------------------------------------------------------------------------------

#[test]
fn trap_patch_embed_input_is_17_channels() {
    let c = DitConfig::anima();
    assert!(c.concat_padding_mask, "concat_padding_mask must be true");
    assert_eq!(c.in_channels, 16, "latent channels");
    assert_eq!(
        c.patch_in_channels(),
        17,
        "patch-embed sees 16 latent + 1 padding-mask channel"
    );
}

// -------------------------------------------------------------------------------------------------
// Trap — per-axis RoPE OOD reject: a request above ~1920 px/side (post-patch > 120/axis) must ERROR,
// never index OOB. max_size/patch = (128,120,120).
// -------------------------------------------------------------------------------------------------

#[test]
fn trap_rope_rejects_per_axis_ood_never_indexes_oob() {
    let cfg = DitConfig::anima();
    assert_eq!(cfg.max_size, (128, 120, 120), "post-patch max_size");
    // 121 positions on either spatial axis exceeds the trained range -> must reject.
    assert!(
        cosmos_image_rope(&cfg, 1, 121, 96).is_err(),
        "h-axis 121 > 120 must be rejected"
    );
    assert!(
        cosmos_image_rope(&cfg, 1, 96, 121).is_err(),
        "w-axis 121 > 120 must be rejected"
    );
    // The 1920² boundary (post-patch 120) fits; 1536² (post-patch 96, the shipped ceiling) fits.
    assert!(
        cosmos_image_rope(&cfg, 1, 120, 120).is_ok(),
        "120 is in-range"
    );
    assert!(cosmos_image_rope(&cfg, 1, 96, 96).is_ok(), "96 is in-range");
    // A correctly-sized 1024² request (post-patch 64) produces the right table shape.
    let r = cosmos_image_rope(&cfg, 1, 64, 64).expect("64x64 ok");
    assert_eq!(r.cos.shape(), &[1, 4096, 128]);
}

// -------------------------------------------------------------------------------------------------
// Trap — prompt weighting. ComfyUI (`comfy/text_encoders/anima.py`) forces the Qwen token weights to
// 1.0 and carries `t5xxl_weights` separately, so weighting must hit the **T5 query tokens**, not Qwen.
// mlx-gen-anima does NOT implement prompt weighting yet: the pipeline tokenizes plain text with no
// per-token weight vector on either side. This test PINS that current reality (weight syntax like
// `(chibi:2)` is literal text to both tokenizers) so the gap is explicit and can't silently regress.
// Wiring T5-side weighting (and pinning Qwen weights to 1.0) is tracked as a follow-up.
// -------------------------------------------------------------------------------------------------

#[test]
fn trap_prompt_weighting_absent_weight_syntax_is_literal_text() {
    let tk = AnimaTokenizers::load().expect("load tokenizers");
    // `(chibi:2)` tokenizes to MORE tokens than bare `chibi` on both sides — proof the weight is not
    // parsed out; it is fed as literal characters. There is no weight vector applied anywhere.
    let (bare_q, _) = tk.encode_qwen("chibi").unwrap();
    let (wt_q, _) = tk.encode_qwen("(chibi:2)").unwrap();
    let bare_t5 = tk.encode_t5("chibi").unwrap();
    let wt_t5 = tk.encode_t5("(chibi:2)").unwrap();
    assert!(
        wt_q.shape()[1] > bare_q.shape()[1],
        "Qwen: `(chibi:2)` is literal text (more tokens than `chibi`) — weighting not parsed"
    );
    assert!(
        wt_t5.shape()[1] > bare_t5.shape()[1],
        "T5: `(chibi:2)` is literal text (more tokens than `chibi`) — weighting not parsed"
    );
    // NOTE (sc-10524 finding): the T5-vs-Qwen prompt-weighting behaviour cannot be tested for real
    // until weighting is implemented. Tracked as a follow-up story; see the PR description.
}
