//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "detr_parity.rs"]
mod detr_parity;

#[path = "dynmask_parity.rs"]
mod dynmask_parity;

#[path = "e2e_parity.rs"]
mod e2e_parity;

#[path = "geometry_parity.rs"]
mod geometry_parity;

#[path = "maskcond_parity.rs"]
mod maskcond_parity;

#[path = "memattn_parity.rs"]
mod memattn_parity;

#[path = "memcond_parity.rs"]
mod memcond_parity;

#[path = "memory_parity.rs"]
mod memory_parity;

#[path = "quant_smoke.rs"]
mod quant_smoke;

#[path = "text_parity.rs"]
mod text_parity;

#[path = "tracker_parity.rs"]
mod tracker_parity;

#[path = "trackframe_parity.rs"]
mod trackframe_parity;

#[path = "video_parity.rs"]
mod video_parity;

#[path = "vision_parity.rs"]
mod vision_parity;
