//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "instantid_curated_smoke.rs"]
mod instantid_curated_smoke;

#[path = "instantid_e2e.rs"]
mod instantid_e2e;

#[path = "instantid_kps.rs"]
mod instantid_kps;

#[path = "instantid_openpose.rs"]
mod instantid_openpose;
