//! Single integration-test binary for this crate (sc-21383).
//!
//! GENERATED by `scripts/ci/consolidate_integration_tests.py` -- do not edit by hand. To add
//! tests, add a `tests/<name>.rs` file and run
//! `python3 scripts/ci/consolidate_integration_tests.py regen`; `check` (run by
//! `scripts/tests/test_ci_workflow_policy.py`) fails when a file is missing here.
//!
//! Each module below was one per-file test binary. Select one with
//! `cargo test -p <crate> --test integration -- <name>::`.

// --- shared modules (hand-maintained; preserved by regen) ---
// --- generated modules (do not edit) ---

#[path = "cancellation_conformance.rs"]
mod cancellation_conformance;

#[path = "clip_parity.rs"]
mod clip_parity;

#[path = "clip_real_parity.rs"]
mod clip_real_parity;

#[path = "descriptor_conformance.rs"]
mod descriptor_conformance;

#[path = "dit_chunk_equiv.rs"]
mod dit_chunk_equiv;

#[path = "dit_parity.rs"]
mod dit_parity;

#[path = "dit_real_parity.rs"]
mod dit_real_parity;

#[path = "generate_smoke.rs"]
mod generate_smoke;

#[path = "lora.rs"]
mod lora;

#[path = "mask_parity.rs"]
mod mask_parity;

#[path = "quantize_snapshot.rs"]
mod quantize_snapshot;

#[path = "registration.rs"]
mod registration;

#[path = "resize_parity.rs"]
mod resize_parity;

#[path = "sequential_residency_real_weights.rs"]
mod sequential_residency_real_weights;

#[path = "snapshot_load.rs"]
mod snapshot_load;

#[path = "vae_decode_tiling_parity.rs"]
mod vae_decode_tiling_parity;

#[path = "vae_tiling_inheritance.rs"]
mod vae_tiling_inheritance;
